// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

func layerEncodeWire02b78156BareBody(profile LayerProfile, value *tg.KeyboardButton, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			historicalPresent1, historicalPresent2, historicalPresent3, historicalPresent4, historicalValue4, historicalValue5, historicalValue6, historicalValue7, historicalValue8, historicalHookErr := layerAdaptLegacyInputKeyboardButtonRequestPeerEncode(profile, value)
			if historicalHookErr != nil {
				return fmt.Errorf("adapt historical constructor for encoding: %w", historicalHookErr)
			}
			layerHistoricalPresent1 := historicalPresent4
			layerHistoricalEncoded2 := &bin.Buffer{}
			if layerHistoricalPresent1 {
				layerHistoricalErr3 := func() error {
					layerHistoricalEncoded2.PutID(0x4fdd3430)
					if err := layerEncodeWire4fdd3430BareBody(profile, &(historicalValue4), layerHistoricalEncoded2, state); err != nil {
						return fmt.Errorf("encode historical field style: %w", err)
					}
					return nil
				}()
				if layerHistoricalErr3 != nil {
					if IsLayerProjectionDrop(layerHistoricalErr3) {
						layerHistoricalPresent1 = false
						layerHistoricalEncoded2.Reset()
					} else {
						return fmt.Errorf("encode historical optional field style: %w", layerHistoricalErr3)
					}
				}
			}
			if (historicalPresent1) && !historicalPresent1 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "historical adapter returned a partial shared flag group flags.0"}
			}
			if (historicalPresent2) && !historicalPresent2 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "historical adapter returned a partial shared flag group flags.1"}
			}
			if (historicalPresent3) && !historicalPresent3 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "historical adapter returned a partial shared flag group flags.2"}
			}
			if (layerHistoricalPresent1) && !layerHistoricalPresent1 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "historical adapter returned a partial shared flag group flags.10"}
			}
			var wireFlags0 bin.Fields
			if historicalPresent1 {
				wireFlags0.Set(0)
			}
			if historicalPresent2 {
				wireFlags0.Set(1)
			}
			if historicalPresent3 {
				wireFlags0.Set(2)
			}
			if layerHistoricalPresent1 {
				wireFlags0.Set(10)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode historical flags flags: %w", err)
			}
			if wireFlags0.Has(10) {
				b.Buf = append(b.Buf, layerHistoricalEncoded2.Buf...)
			}
			if err := b.PutStringChecked(historicalValue5); err != nil {
				return fmt.Errorf("encode historical field text: %w", err)
			}
			b.PutInt(historicalValue6)
			if err := layerEncodeClassRequestPeerTypeBody(profile, historicalValue7, b, state); err != nil {
				return fmt.Errorf("encode historical field peer_type: %w", err)
			}
			b.PutInt(historicalValue8)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire02b78156(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.KeyboardButton, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x02b78156); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x02b78156: %w", err)
	}
	return layerDecodeWire02b78156Bare(profile, b, state)

}

func layerDecodeWire02b78156Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.KeyboardButton, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.KeyboardButton)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode historical flags flags: %w", err)
			}
			historicalPresent1 := wireFlags0.Has(0)
			historicalPresent2 := wireFlags0.Has(1)
			historicalPresent3 := wireFlags0.Has(2)
			historicalPresent4 := wireFlags0.Has(10)
			var historicalValue4 tg.KeyboardButtonStyle
			if historicalPresent4 {
				layerConcrete1, err := layerDecodeWire4fdd3430(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode historical field style: %w", err)
				}
				historicalValue4 = *layerConcrete1
			}
			var historicalValue5 string
			layerPrimitive2, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode historical field text: %w", err)
			}
			historicalValue5 = layerPrimitive2
			var historicalValue6 int
			layerPrimitive3, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode historical field button_id: %w", err)
			}
			historicalValue6 = layerPrimitive3
			var historicalValue7 tg.RequestPeerTypeClass
			layerClass4, err := layerDecodeClassRequestPeerType(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode historical field peer_type: %w", err)
			}
			historicalValue7 = layerClass4
			var historicalValue8 int
			layerPrimitive5, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode historical field max_quantity: %w", err)
			}
			historicalValue8 = layerPrimitive5
			adapted, err := layerAdaptLegacyInputKeyboardButtonRequestPeerDecode(profile, historicalPresent1, historicalPresent2, historicalPresent3, historicalPresent4, historicalValue4, historicalValue5, historicalValue6, historicalValue7, historicalValue8)
			if err != nil {
				return nil, fmt.Errorf("adapt historical constructor after decoding: %w", err)
			}
			if adapted == nil {
				return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "historical adapter returned nil canonical value"}
			}
			return adapted, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeInputKeyboardButtonRequestPeer, WireID: 0x02b78156, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire068e9916Bare(profile LayerProfile, value *tg.AuthLoginTokenMigrateTo, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthLoginTokenMigrateTo, WireID: 0x068e9916, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire068e9916BareBody(profile LayerProfile, value *tg.AuthLoginTokenMigrateTo, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire068e9916Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire0d999256Bare(profile LayerProfile, value *tg.MessageActionTopicCreate, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionTopicCreate, WireID: 0x0d999256, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire0d999256BareBody(profile LayerProfile, value *tg.MessageActionTopicCreate, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire0d999256Bare(profile, value, b, state)
}
func layerDecodeWire0d999256(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionTopicCreate, error) {
	value := new(tg.MessageActionTopicCreate)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire1142bd56Bare(profile LayerProfile, value *tg.SavedPhoneContact, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSavedPhoneContact, WireID: 0x1142bd56, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire1142bd56BareBody(profile LayerProfile, value *tg.SavedPhoneContact, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire1142bd56Bare(profile, value, b, state)
}

func layerEncodeWire16115a96BareBody(profile LayerProfile, value *tg.PageBlockRelatedArticles, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassRichTextBody(profile, value.Title, b, state); err != nil {
				return fmt.Errorf("encode field title: %w", err)
			}
			if len(value.Articles) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart6 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset7 := layerVectorStart6 + 4
			layerLength4 := 0
			for layerIndex5 := range value.Articles {
				layerItemStart8 := len(b.Buf)
				layerErr9 := func() error {
					b.PutID(0xb390dc08)
					if err := layerEncodeWireb390dc08BareBody(profile, &(value.Articles[layerIndex5]), b, state); err != nil {
						return fmt.Errorf("encode field articles element: %w", err)
					}
					return nil
				}()
				if layerErr9 != nil {
					b.Buf = b.Buf[:layerItemStart8]
					if IsLayerProjectionDrop(layerErr9) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart6]
					return fmt.Errorf("encode field articles: %w", layerErr9)
				}
				layerLength4++
			}
			b.Buf[layerCountOffset7] = byte(layerLength4)
			b.Buf[layerCountOffset7+1] = byte(layerLength4 >> 8)
			b.Buf[layerCountOffset7+2] = byte(layerLength4 >> 16)
			b.Buf[layerCountOffset7+3] = byte(layerLength4 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePageBlockRelatedArticles, WireID: 0x16115a96, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire16115a96(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PageBlockRelatedArticles, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypePageBlockRelatedArticles, WireID: 0x16115a96, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x16115a96); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x16115a96: %w", err)
	}
	return layerDecodeWire16115a96Bare(profile, b, state)

}

func layerDecodeWire16115a96Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PageBlockRelatedArticles, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PageBlockRelatedArticles)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded10 tg.RichTextClass
			layerClass11, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field title: %w", err)
			}
			layerDecoded10 = layerClass11
			var layerDecoded12 []tg.PageRelatedArticle
			layerDecodeState13, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field articles vector depth: %w", err)
			}
			layerLength14, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState13)
			if err != nil {
				return nil, fmt.Errorf("decode field articles: %w", err)
			}
			var layerVector15 []tg.PageRelatedArticle
			if layerLength14 > 0 {
				capacity := layerLength14
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector15 = make([]tg.PageRelatedArticle, 0, capacity)
			}
			for index := 0; index < layerLength14; index++ {
				var element tg.PageRelatedArticle
				layerConcrete16, err := layerDecodeWireb390dc08(profile, b, &layerDecodeState13)
				if err != nil {
					return nil, fmt.Errorf("decode field articles element: %w", err)
				}
				element = *layerConcrete16
				layerVector15 = append(layerVector15, element)
			}
			layerDecoded12 = layerVector15
			if true {
				value.Title = layerDecoded10
			}
			if true {
				value.Articles = layerDecoded12
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypePageBlockRelatedArticles, WireID: 0x16115a96, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire1710f156Bare(profile LayerProfile, value *tg.UpdateEncryptedChatTyping, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateEncryptedChatTyping, WireID: 0x1710f156, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire1710f156BareBody(profile LayerProfile, value *tg.UpdateEncryptedChatTyping, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire1710f156Bare(profile, value, b, state)
}
func layerDecodeWire1710f156(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateEncryptedChatTyping, error) {
	value := new(tg.UpdateEncryptedChatTyping)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire199fed96BareBody(profile LayerProfile, value *tg.InputPollAnswer, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if value.Flags.Has(0) && value.Media == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputPollAnswer, Reason: "malformed canonical value: explicit flag has nil interface field media"}
			}
			layerEncoded3 := &bin.Buffer{}
			layerPresent5 := (value.Flags.Has(0) || value.Media != nil)
			if layerPresent5 {
				layerErr4 := func() error {
					if err := layerEncodeClassInputMediaBody(profile, value.Media, layerEncoded3, state); err != nil {
						return fmt.Errorf("encode prepared field media: %w", err)
					}
					return nil
				}()
				if layerErr4 != nil {
					if IsLayerProjectionDrop(layerErr4) {
						layerPresent5 = false
						layerEncoded3.Reset()
					} else {
						return fmt.Errorf("encode optional field media: %w", layerErr4)
					}
				}
			}
			var wireFlags0 bin.Fields
			if layerPresent5 {
				wireFlags0.Set(0)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			b.PutID(0x751f3146)
			if err := layerEncodeWire751f3146BareBody(profile, &(value.Text), b, state); err != nil {
				return fmt.Errorf("encode field text: %w", err)
			}
			if wireFlags0.Has(0) {
				b.Buf = append(b.Buf, layerEncoded3.Buf...)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputPollAnswer, WireID: 0x199fed96, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire199fed96(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputPollAnswer, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeInputPollAnswer, WireID: 0x199fed96, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x199fed96); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x199fed96: %w", err)
	}
	return layerDecodeWire199fed96Bare(profile, b, state)

}

func layerDecodeWire199fed96Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputPollAnswer, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.InputPollAnswer)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			var layerDecoded6 tg.TextWithEntities
			layerConcrete7, err := layerDecodeWire751f3146(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field text: %w", err)
			}
			layerDecoded6 = *layerConcrete7
			var layerDecoded8 tg.InputMediaClass
			if wireFlags0.Has(0) {
				layerClass9, err := layerDecodeClassInputMedia(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field media: %w", err)
				}
				layerDecoded8 = layerClass9
			}
			if true {
				value.Text = layerDecoded6
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Media = layerDecoded8
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeInputPollAnswer, WireID: 0x199fed96, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire1bd54456Bare(profile LayerProfile, value *tg.ChannelParticipant, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChannelParticipant, WireID: 0x1bd54456, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire1bd54456BareBody(profile LayerProfile, value *tg.ChannelParticipant, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire1bd54456Bare(profile, value, b, state)
}
func layerDecodeWire1bd54456(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChannelParticipant, error) {
	value := new(tg.ChannelParticipant)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire41cbf256BareBody(profile LayerProfile, value *tg.Chat, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if value.Flags.Has(6) && value.MigratedTo == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChat, Reason: "malformed canonical value: explicit flag has nil interface field migrated_to"}
			}
			layerEncoded5 := &bin.Buffer{}
			layerPresent7 := (value.Flags.Has(6) || value.MigratedTo != nil)
			if layerPresent7 {
				layerErr6 := func() error {
					if err := layerEncodeClassInputChannelBody(profile, value.MigratedTo, layerEncoded5, state); err != nil {
						return fmt.Errorf("encode prepared field migrated_to: %w", err)
					}
					return nil
				}()
				if layerErr6 != nil {
					if IsLayerProjectionDrop(layerErr6) {
						layerPresent7 = false
						layerEncoded5.Reset()
					} else {
						return fmt.Errorf("encode optional field migrated_to: %w", layerErr6)
					}
				}
			}
			layerEncoded8 := &bin.Buffer{}
			layerPresent10 := (value.Flags.Has(14) || !value.AdminRights.Zero())
			if layerPresent10 {
				layerErr9 := func() error {
					layerEncoded8.PutID(0x5fb224d5)
					if err := layerEncodeWire5fb224d5BareBody(profile, &(value.AdminRights), layerEncoded8, state); err != nil {
						return fmt.Errorf("encode prepared field admin_rights: %w", err)
					}
					return nil
				}()
				if layerErr9 != nil {
					if IsLayerProjectionDrop(layerErr9) {
						layerPresent10 = false
						layerEncoded8.Reset()
					} else {
						return fmt.Errorf("encode optional field admin_rights: %w", layerErr9)
					}
				}
			}
			layerEncoded11 := &bin.Buffer{}
			layerPresent13 := (value.Flags.Has(18) || !value.DefaultBannedRights.Zero())
			if layerPresent13 {
				layerErr12 := func() error {
					layerEncoded11.PutID(0x9f120418)
					if err := layerEncodeWire9f120418BareBody(profile, &(value.DefaultBannedRights), layerEncoded11, state); err != nil {
						return fmt.Errorf("encode prepared field default_banned_rights: %w", err)
					}
					return nil
				}()
				if layerErr12 != nil {
					if IsLayerProjectionDrop(layerErr12) {
						layerPresent13 = false
						layerEncoded11.Reset()
					} else {
						return fmt.Errorf("encode optional field default_banned_rights: %w", layerErr12)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.Creator {
				wireFlags0.Set(0)
			}
			if value.Flags.Has(2) || value.Left {
				wireFlags0.Set(2)
			}
			if value.Flags.Has(5) || value.Deactivated {
				wireFlags0.Set(5)
			}
			if layerPresent7 {
				wireFlags0.Set(6)
			}
			if layerPresent10 {
				wireFlags0.Set(14)
			}
			if layerPresent13 {
				wireFlags0.Set(18)
			}
			if value.Flags.Has(23) || value.CallActive {
				wireFlags0.Set(23)
			}
			if value.Flags.Has(24) || value.CallNotEmpty {
				wireFlags0.Set(24)
			}
			if value.Flags.Has(25) || value.Noforwards {
				wireFlags0.Set(25)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			b.PutLong(value.ID)
			if err := b.PutStringChecked(value.Title); err != nil {
				return fmt.Errorf("encode field title: %w", err)
			}
			if err := layerEncodeClassChatPhotoBody(profile, value.Photo, b, state); err != nil {
				return fmt.Errorf("encode field photo: %w", err)
			}
			b.PutInt(value.ParticipantsCount)
			b.PutInt(value.Date)
			b.PutInt(value.Version)
			if wireFlags0.Has(6) {
				b.Buf = append(b.Buf, layerEncoded5.Buf...)
			}
			if wireFlags0.Has(14) {
				b.Buf = append(b.Buf, layerEncoded8.Buf...)
			}
			if wireFlags0.Has(18) {
				b.Buf = append(b.Buf, layerEncoded11.Buf...)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChat, WireID: 0x41cbf256, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire41cbf256(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.Chat, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeChat, WireID: 0x41cbf256, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x41cbf256); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x41cbf256: %w", err)
	}
	return layerDecodeWire41cbf256Bare(profile, b, state)

}

func layerDecodeWire41cbf256Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.Chat, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.Chat)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded14 := wireFlags0.Has(0)
			layerDecoded15 := wireFlags0.Has(2)
			layerDecoded16 := wireFlags0.Has(5)
			layerDecoded17 := wireFlags0.Has(23)
			layerDecoded18 := wireFlags0.Has(24)
			layerDecoded19 := wireFlags0.Has(25)
			var layerDecoded20 int64
			layerPrimitive21, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field id: %w", err)
			}
			layerDecoded20 = layerPrimitive21
			var layerDecoded22 string
			layerPrimitive23, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field title: %w", err)
			}
			layerDecoded22 = layerPrimitive23
			var layerDecoded24 tg.ChatPhotoClass
			layerClass25, err := layerDecodeClassChatPhoto(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field photo: %w", err)
			}
			layerDecoded24 = layerClass25
			var layerDecoded26 int
			layerPrimitive27, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field participants_count: %w", err)
			}
			layerDecoded26 = layerPrimitive27
			var layerDecoded28 int
			layerPrimitive29, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field date: %w", err)
			}
			layerDecoded28 = layerPrimitive29
			var layerDecoded30 int
			layerPrimitive31, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field version: %w", err)
			}
			layerDecoded30 = layerPrimitive31
			var layerDecoded32 tg.InputChannelClass
			if wireFlags0.Has(6) {
				layerClass33, err := layerDecodeClassInputChannel(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field migrated_to: %w", err)
				}
				layerDecoded32 = layerClass33
			}
			var layerDecoded34 tg.ChatAdminRights
			if wireFlags0.Has(14) {
				layerConcrete35, err := layerDecodeWire5fb224d5(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field admin_rights: %w", err)
				}
				layerDecoded34 = *layerConcrete35
			}
			var layerDecoded36 tg.ChatBannedRights
			if wireFlags0.Has(18) {
				layerConcrete37, err := layerDecodeWire9f120418(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field default_banned_rights: %w", err)
				}
				layerDecoded36 = *layerConcrete37
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Creator = layerDecoded14
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.Left = layerDecoded15
			}
			if wireFlags0.Has(5) {
				value.Flags.Set(5)
				value.Deactivated = layerDecoded16
			}
			if wireFlags0.Has(23) {
				value.Flags.Set(23)
				value.CallActive = layerDecoded17
			}
			if wireFlags0.Has(24) {
				value.Flags.Set(24)
				value.CallNotEmpty = layerDecoded18
			}
			if wireFlags0.Has(25) {
				value.Flags.Set(25)
				value.Noforwards = layerDecoded19
			}
			if true {
				value.ID = layerDecoded20
			}
			if true {
				value.Title = layerDecoded22
			}
			if true {
				value.Photo = layerDecoded24
			}
			if true {
				value.ParticipantsCount = layerDecoded26
			}
			if true {
				value.Date = layerDecoded28
			}
			if true {
				value.Version = layerDecoded30
			}
			if wireFlags0.Has(6) {
				value.Flags.Set(6)
				value.MigratedTo = layerDecoded32
			}
			if wireFlags0.Has(14) {
				value.Flags.Set(14)
				value.AdminRights = layerDecoded34
			}
			if wireFlags0.Has(18) {
				value.Flags.Set(18)
				value.DefaultBannedRights = layerDecoded36
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeChat, WireID: 0x41cbf256, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire4b3e14d6Bare(profile LayerProfile, value *tg.Boost, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeBoost, WireID: 0x4b3e14d6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire4b3e14d6BareBody(profile LayerProfile, value *tg.Boost, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire4b3e14d6Bare(profile, value, b, state)
}
func layerDecodeWire4b3e14d6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.Boost, error) {
	value := new(tg.Boost)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire4e90bfd6Bare(profile LayerProfile, value *tg.UpdateMessageID, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateMessageID, WireID: 0x4e90bfd6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire4e90bfd6BareBody(profile LayerProfile, value *tg.UpdateMessageID, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire4e90bfd6Bare(profile, value, b, state)
}
func layerDecodeWire4e90bfd6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateMessageID, error) {
	value := new(tg.UpdateMessageID)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire5f206716BareBody(profile LayerProfile, value *tg.MessagesMessagesSlice, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			layerEncoded10 := &bin.Buffer{}
			layerPresent12 := (value.Flags.Has(3) || !value.SearchFlood.Zero())
			if layerPresent12 {
				layerErr11 := func() error {
					layerEncoded10.PutID(0x3e0b5b6a)
					if err := layerEncodeWire3e0b5b6aBareBody(profile, &(value.SearchFlood), layerEncoded10, state); err != nil {
						return fmt.Errorf("encode prepared field search_flood: %w", err)
					}
					return nil
				}()
				if layerErr11 != nil {
					if IsLayerProjectionDrop(layerErr11) {
						layerPresent12 = false
						layerEncoded10.Reset()
					} else {
						return fmt.Errorf("encode optional field search_flood: %w", layerErr11)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.NextRate != 0 {
				wireFlags0.Set(0)
			}
			if value.Flags.Has(1) || value.Inexact {
				wireFlags0.Set(1)
			}
			if value.Flags.Has(2) || value.OffsetIDOffset != 0 {
				wireFlags0.Set(2)
			}
			if layerPresent12 {
				wireFlags0.Set(3)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			b.PutInt(value.Count)
			if wireFlags0.Has(0) {
				b.PutInt(value.NextRate)
			}
			if wireFlags0.Has(2) {
				b.PutInt(value.OffsetIDOffset)
			}
			if wireFlags0.Has(3) {
				b.Buf = append(b.Buf, layerEncoded10.Buf...)
			}
			if len(value.Messages) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart15 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset16 := layerVectorStart15 + 4
			layerLength13 := 0
			for layerIndex14 := range value.Messages {
				layerItemStart17 := len(b.Buf)
				layerErr18 := func() error {
					if err := layerEncodeClassMessageBody(profile, value.Messages[layerIndex14], b, state); err != nil {
						return fmt.Errorf("encode field messages element: %w", err)
					}
					return nil
				}()
				if layerErr18 != nil {
					b.Buf = b.Buf[:layerItemStart17]
					if IsLayerProjectionDrop(layerErr18) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart15]
					return fmt.Errorf("encode field messages: %w", layerErr18)
				}
				layerLength13++
			}
			b.Buf[layerCountOffset16] = byte(layerLength13)
			b.Buf[layerCountOffset16+1] = byte(layerLength13 >> 8)
			b.Buf[layerCountOffset16+2] = byte(layerLength13 >> 16)
			b.Buf[layerCountOffset16+3] = byte(layerLength13 >> 24)
			if len(value.Topics) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart21 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset22 := layerVectorStart21 + 4
			layerLength19 := 0
			for layerIndex20 := range value.Topics {
				layerItemStart23 := len(b.Buf)
				layerErr24 := func() error {
					if err := layerEncodeClassForumTopicBody(profile, value.Topics[layerIndex20], b, state); err != nil {
						return fmt.Errorf("encode field topics element: %w", err)
					}
					return nil
				}()
				if layerErr24 != nil {
					b.Buf = b.Buf[:layerItemStart23]
					if IsLayerProjectionDrop(layerErr24) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart21]
					return fmt.Errorf("encode field topics: %w", layerErr24)
				}
				layerLength19++
			}
			b.Buf[layerCountOffset22] = byte(layerLength19)
			b.Buf[layerCountOffset22+1] = byte(layerLength19 >> 8)
			b.Buf[layerCountOffset22+2] = byte(layerLength19 >> 16)
			b.Buf[layerCountOffset22+3] = byte(layerLength19 >> 24)
			if len(value.Chats) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart27 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset28 := layerVectorStart27 + 4
			layerLength25 := 0
			for layerIndex26 := range value.Chats {
				layerItemStart29 := len(b.Buf)
				layerErr30 := func() error {
					if err := layerEncodeClassChatBody(profile, value.Chats[layerIndex26], b, state); err != nil {
						return fmt.Errorf("encode field chats element: %w", err)
					}
					return nil
				}()
				if layerErr30 != nil {
					b.Buf = b.Buf[:layerItemStart29]
					if IsLayerProjectionDrop(layerErr30) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart27]
					return fmt.Errorf("encode field chats: %w", layerErr30)
				}
				layerLength25++
			}
			b.Buf[layerCountOffset28] = byte(layerLength25)
			b.Buf[layerCountOffset28+1] = byte(layerLength25 >> 8)
			b.Buf[layerCountOffset28+2] = byte(layerLength25 >> 16)
			b.Buf[layerCountOffset28+3] = byte(layerLength25 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart33 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset34 := layerVectorStart33 + 4
			layerLength31 := 0
			for layerIndex32 := range value.Users {
				layerItemStart35 := len(b.Buf)
				layerErr36 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex32], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr36 != nil {
					b.Buf = b.Buf[:layerItemStart35]
					if IsLayerProjectionDrop(layerErr36) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart33]
					return fmt.Errorf("encode field users: %w", layerErr36)
				}
				layerLength31++
			}
			b.Buf[layerCountOffset34] = byte(layerLength31)
			b.Buf[layerCountOffset34+1] = byte(layerLength31 >> 8)
			b.Buf[layerCountOffset34+2] = byte(layerLength31 >> 16)
			b.Buf[layerCountOffset34+3] = byte(layerLength31 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesMessagesSlice, WireID: 0x5f206716, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire5f206716(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesMessagesSlice, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeMessagesMessagesSlice, WireID: 0x5f206716, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x5f206716); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x5f206716: %w", err)
	}
	return layerDecodeWire5f206716Bare(profile, b, state)

}

func layerDecodeWire5f206716Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesMessagesSlice, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesMessagesSlice)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded37 := wireFlags0.Has(1)
			var layerDecoded38 int
			layerPrimitive39, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field count: %w", err)
			}
			layerDecoded38 = layerPrimitive39
			var layerDecoded40 int
			if wireFlags0.Has(0) {
				layerPrimitive41, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field next_rate: %w", err)
				}
				layerDecoded40 = layerPrimitive41
			}
			var layerDecoded42 int
			if wireFlags0.Has(2) {
				layerPrimitive43, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field offset_id_offset: %w", err)
				}
				layerDecoded42 = layerPrimitive43
			}
			var layerDecoded44 tg.SearchPostsFlood
			if wireFlags0.Has(3) {
				layerConcrete45, err := layerDecodeWire3e0b5b6a(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field search_flood: %w", err)
				}
				layerDecoded44 = *layerConcrete45
			}
			var layerDecoded46 []tg.MessageClass
			layerDecodeState47, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field messages vector depth: %w", err)
			}
			layerLength48, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState47)
			if err != nil {
				return nil, fmt.Errorf("decode field messages: %w", err)
			}
			var layerVector49 []tg.MessageClass
			if layerLength48 > 0 {
				capacity := layerLength48
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector49 = make([]tg.MessageClass, 0, capacity)
			}
			for index := 0; index < layerLength48; index++ {
				var element tg.MessageClass
				layerClass50, err := layerDecodeClassMessage(profile, b, &layerDecodeState47)
				if err != nil {
					return nil, fmt.Errorf("decode field messages element: %w", err)
				}
				element = layerClass50
				layerVector49 = append(layerVector49, element)
			}
			layerDecoded46 = layerVector49
			var layerDecoded51 []tg.ForumTopicClass
			layerDecodeState52, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field topics vector depth: %w", err)
			}
			layerLength53, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState52)
			if err != nil {
				return nil, fmt.Errorf("decode field topics: %w", err)
			}
			var layerVector54 []tg.ForumTopicClass
			if layerLength53 > 0 {
				capacity := layerLength53
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector54 = make([]tg.ForumTopicClass, 0, capacity)
			}
			for index := 0; index < layerLength53; index++ {
				var element tg.ForumTopicClass
				layerClass55, err := layerDecodeClassForumTopic(profile, b, &layerDecodeState52)
				if err != nil {
					return nil, fmt.Errorf("decode field topics element: %w", err)
				}
				element = layerClass55
				layerVector54 = append(layerVector54, element)
			}
			layerDecoded51 = layerVector54
			var layerDecoded56 []tg.ChatClass
			layerDecodeState57, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field chats vector depth: %w", err)
			}
			layerLength58, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState57)
			if err != nil {
				return nil, fmt.Errorf("decode field chats: %w", err)
			}
			var layerVector59 []tg.ChatClass
			if layerLength58 > 0 {
				capacity := layerLength58
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector59 = make([]tg.ChatClass, 0, capacity)
			}
			for index := 0; index < layerLength58; index++ {
				var element tg.ChatClass
				layerClass60, err := layerDecodeClassChat(profile, b, &layerDecodeState57)
				if err != nil {
					return nil, fmt.Errorf("decode field chats element: %w", err)
				}
				element = layerClass60
				layerVector59 = append(layerVector59, element)
			}
			layerDecoded56 = layerVector59
			var layerDecoded61 []tg.UserClass
			layerDecodeState62, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength63, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState62)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector64 []tg.UserClass
			if layerLength63 > 0 {
				capacity := layerLength63
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector64 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength63; index++ {
				var element tg.UserClass
				layerClass65, err := layerDecodeClassUser(profile, b, &layerDecodeState62)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass65
				layerVector64 = append(layerVector64, element)
			}
			layerDecoded61 = layerVector64
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.Inexact = layerDecoded37
			}
			if true {
				value.Count = layerDecoded38
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.NextRate = layerDecoded40
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.OffsetIDOffset = layerDecoded42
			}
			if wireFlags0.Has(3) {
				value.Flags.Set(3)
				value.SearchFlood = layerDecoded44
			}
			if true {
				value.Messages = layerDecoded46
			}
			if true {
				value.Topics = layerDecoded51
			}
			if true {
				value.Chats = layerDecoded56
			}
			if true {
				value.Users = layerDecoded61
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesMessagesSlice, WireID: 0x5f206716, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire6e153f16Bare(profile LayerProfile, value *tg.MessagesStickerSet, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesStickerSet, WireID: 0x6e153f16, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire6e153f16BareBody(profile LayerProfile, value *tg.MessagesStickerSet, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire6e153f16Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire71777116Bare(profile LayerProfile, value *tg.MessageEntityDiffInsert, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageEntityDiffInsert, WireID: 0x71777116, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire71777116BareBody(profile LayerProfile, value *tg.MessageEntityDiffInsert, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire71777116Bare(profile, value, b, state)
}
func layerDecodeWire71777116(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageEntityDiffInsert, error) {
	value := new(tg.MessageEntityDiffInsert)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire7c1079d6Bare(profile LayerProfile, value *tg.UpdateEphemeralBotCallbackQuery, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateEphemeralBotCallbackQuery, WireID: 0x7c1079d6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire7c1079d6BareBody(profile LayerProfile, value *tg.UpdateEphemeralBotCallbackQuery, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire7c1079d6Bare(profile, value, b, state)
}
func layerDecodeWire7c1079d6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateEphemeralBotCallbackQuery, error) {
	value := new(tg.UpdateEphemeralBotCallbackQuery)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire88d37c56Bare(profile LayerProfile, value *tg.MessagesRecentStickers, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesRecentStickers, WireID: 0x88d37c56, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire88d37c56BareBody(profile LayerProfile, value *tg.MessagesRecentStickers, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire88d37c56Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire8caa9a96Bare(profile LayerProfile, value *tg.UpdateBotPrecheckoutQuery, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateBotPrecheckoutQuery, WireID: 0x8caa9a96, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire8caa9a96BareBody(profile LayerProfile, value *tg.UpdateBotPrecheckoutQuery, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire8caa9a96Bare(profile, value, b, state)
}
func layerDecodeWire8caa9a96(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateBotPrecheckoutQuery, error) {
	value := new(tg.UpdateBotPrecheckoutQuery)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire8d595cd6Bare(profile LayerProfile, value *tg.StoryViews, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStoryViews, WireID: 0x8d595cd6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire8d595cd6BareBody(profile LayerProfile, value *tg.StoryViews, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire8d595cd6Bare(profile, value, b, state)
}
func layerDecodeWire8d595cd6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StoryViews, error) {
	value := new(tg.StoryViews)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirea00e67d6Bare(profile LayerProfile, value *tg.Theme, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTheme, WireID: 0xa00e67d6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea00e67d6BareBody(profile LayerProfile, value *tg.Theme, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea00e67d6Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirea22cbd96Bare(profile LayerProfile, value *tg.ChatInviteExported, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChatInviteExported, WireID: 0xa22cbd96, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea22cbd96BareBody(profile LayerProfile, value *tg.ChatInviteExported, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea22cbd96Bare(profile, value, b, state)
}
func layerDecodeWirea22cbd96(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChatInviteExported, error) {
	value := new(tg.ChatInviteExported)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireafc79cd6Bare(profile LayerProfile, value *tg.TextButton, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextButton, WireID: 0xafc79cd6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireafc79cd6BareBody(profile LayerProfile, value *tg.TextButton, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireafc79cd6Bare(profile, value, b, state)
}
func layerDecodeWireafc79cd6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextButton, error) {
	value := new(tg.TextButton)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireb98cd696Bare(profile LayerProfile, value *tg.ProfileTabPosts, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeProfileTabPosts, WireID: 0xb98cd696, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb98cd696BareBody(profile LayerProfile, value *tg.ProfileTabPosts, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb98cd696Bare(profile, value, b, state)
}
func layerDecodeWireb98cd696(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ProfileTabPosts, error) {
	value := new(tg.ProfileTabPosts)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWirede5a0dd6BareBody(profile LayerProfile, value *tg.TextEmail, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassRichTextBody(profile, value.Text, b, state); err != nil {
				return fmt.Errorf("encode field text: %w", err)
			}
			if err := b.PutStringChecked(value.Email); err != nil {
				return fmt.Errorf("encode field email: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextEmail, WireID: 0xde5a0dd6, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWirede5a0dd6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextEmail, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeTextEmail, WireID: 0xde5a0dd6, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xde5a0dd6); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xde5a0dd6: %w", err)
	}
	return layerDecodeWirede5a0dd6Bare(profile, b, state)

}

func layerDecodeWirede5a0dd6Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextEmail, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.TextEmail)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.RichTextClass
			layerClass3, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field text: %w", err)
			}
			layerDecoded2 = layerClass3
			var layerDecoded4 string
			layerPrimitive5, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field email: %w", err)
			}
			layerDecoded4 = layerPrimitive5
			if true {
				value.Text = layerDecoded2
			}
			if true {
				value.Email = layerDecoded4
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeTextEmail, WireID: 0xde5a0dd6, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree0804116Bare(profile LayerProfile, value *tg.WallPaperNoFile, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeWallPaperNoFile, WireID: 0xe0804116, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree0804116BareBody(profile LayerProfile, value *tg.WallPaperNoFile, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree0804116Bare(profile, value, b, state)
}
func layerDecodeWiree0804116(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.WallPaperNoFile, error) {
	value := new(tg.WallPaperNoFile)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree4c123d6Bare(profile LayerProfile, value *tg.InputGeoPointEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputGeoPointEmpty, WireID: 0xe4c123d6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree4c123d6BareBody(profile LayerProfile, value *tg.InputGeoPointEmpty, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree4c123d6Bare(profile, value, b, state)
}
func layerDecodeWiree4c123d6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputGeoPointEmpty, error) {
	value := new(tg.InputGeoPointEmpty)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree537ced6Bare(profile LayerProfile, value *tg.SecureValueErrorSelfie, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSecureValueErrorSelfie, WireID: 0xe537ced6, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree537ced6BareBody(profile LayerProfile, value *tg.SecureValueErrorSelfie, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree537ced6Bare(profile, value, b, state)
}
func layerDecodeWiree537ced6(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SecureValueErrorSelfie, error) {
	value := new(tg.SecureValueErrorSelfie)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireeafdf716Bare(profile LayerProfile, value *tg.MessagesReactions, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesReactions, WireID: 0xeafdf716, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireeafdf716BareBody(profile LayerProfile, value *tg.MessagesReactions, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireeafdf716Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireee7a1596Bare(profile LayerProfile, value *tg.MessageActionSuggestedPostApproval, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionSuggestedPostApproval, WireID: 0xee7a1596, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireee7a1596BareBody(profile LayerProfile, value *tg.MessageActionSuggestedPostApproval, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireee7a1596Bare(profile, value, b, state)
}
func layerDecodeWireee7a1596(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionSuggestedPostApproval, error) {
	value := new(tg.MessageActionSuggestedPostApproval)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWireef7ff916BareBody(profile LayerProfile, value *tg.StatsMegagroupStats, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			b.PutID(0xb637edaf)
			if err := layerEncodeWireb637edafBareBody(profile, &(value.Period), b, state); err != nil {
				return fmt.Errorf("encode field period: %w", err)
			}
			b.PutID(0xcb43acde)
			if err := layerEncodeWirecb43acdeBareBody(profile, &(value.Members), b, state); err != nil {
				return fmt.Errorf("encode field members: %w", err)
			}
			b.PutID(0xcb43acde)
			if err := layerEncodeWirecb43acdeBareBody(profile, &(value.Messages), b, state); err != nil {
				return fmt.Errorf("encode field messages: %w", err)
			}
			b.PutID(0xcb43acde)
			if err := layerEncodeWirecb43acdeBareBody(profile, &(value.Viewers), b, state); err != nil {
				return fmt.Errorf("encode field viewers: %w", err)
			}
			b.PutID(0xcb43acde)
			if err := layerEncodeWirecb43acdeBareBody(profile, &(value.Posters), b, state); err != nil {
				return fmt.Errorf("encode field posters: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.GrowthGraph, b, state); err != nil {
				return fmt.Errorf("encode field growth_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.MembersGraph, b, state); err != nil {
				return fmt.Errorf("encode field members_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.NewMembersBySourceGraph, b, state); err != nil {
				return fmt.Errorf("encode field new_members_by_source_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.LanguagesGraph, b, state); err != nil {
				return fmt.Errorf("encode field languages_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.MessagesGraph, b, state); err != nil {
				return fmt.Errorf("encode field messages_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.ActionsGraph, b, state); err != nil {
				return fmt.Errorf("encode field actions_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.TopHoursGraph, b, state); err != nil {
				return fmt.Errorf("encode field top_hours_graph: %w", err)
			}
			if err := layerEncodeClassStatsGraphBody(profile, value.WeekdaysGraph, b, state); err != nil {
				return fmt.Errorf("encode field weekdays_graph: %w", err)
			}
			if len(value.TopPosters) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart24 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset25 := layerVectorStart24 + 4
			layerLength22 := 0
			for layerIndex23 := range value.TopPosters {
				layerItemStart26 := len(b.Buf)
				layerErr27 := func() error {
					b.PutID(0x9d04af9b)
					if err := layerEncodeWire9d04af9bBareBody(profile, &(value.TopPosters[layerIndex23]), b, state); err != nil {
						return fmt.Errorf("encode field top_posters element: %w", err)
					}
					return nil
				}()
				if layerErr27 != nil {
					b.Buf = b.Buf[:layerItemStart26]
					if IsLayerProjectionDrop(layerErr27) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart24]
					return fmt.Errorf("encode field top_posters: %w", layerErr27)
				}
				layerLength22++
			}
			b.Buf[layerCountOffset25] = byte(layerLength22)
			b.Buf[layerCountOffset25+1] = byte(layerLength22 >> 8)
			b.Buf[layerCountOffset25+2] = byte(layerLength22 >> 16)
			b.Buf[layerCountOffset25+3] = byte(layerLength22 >> 24)
			if len(value.TopAdmins) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart30 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset31 := layerVectorStart30 + 4
			layerLength28 := 0
			for layerIndex29 := range value.TopAdmins {
				layerItemStart32 := len(b.Buf)
				layerErr33 := func() error {
					b.PutID(0xd7584c87)
					if err := layerEncodeWired7584c87BareBody(profile, &(value.TopAdmins[layerIndex29]), b, state); err != nil {
						return fmt.Errorf("encode field top_admins element: %w", err)
					}
					return nil
				}()
				if layerErr33 != nil {
					b.Buf = b.Buf[:layerItemStart32]
					if IsLayerProjectionDrop(layerErr33) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart30]
					return fmt.Errorf("encode field top_admins: %w", layerErr33)
				}
				layerLength28++
			}
			b.Buf[layerCountOffset31] = byte(layerLength28)
			b.Buf[layerCountOffset31+1] = byte(layerLength28 >> 8)
			b.Buf[layerCountOffset31+2] = byte(layerLength28 >> 16)
			b.Buf[layerCountOffset31+3] = byte(layerLength28 >> 24)
			if len(value.TopInviters) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart36 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset37 := layerVectorStart36 + 4
			layerLength34 := 0
			for layerIndex35 := range value.TopInviters {
				layerItemStart38 := len(b.Buf)
				layerErr39 := func() error {
					b.PutID(0x535f779d)
					if err := layerEncodeWire535f779dBareBody(profile, &(value.TopInviters[layerIndex35]), b, state); err != nil {
						return fmt.Errorf("encode field top_inviters element: %w", err)
					}
					return nil
				}()
				if layerErr39 != nil {
					b.Buf = b.Buf[:layerItemStart38]
					if IsLayerProjectionDrop(layerErr39) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart36]
					return fmt.Errorf("encode field top_inviters: %w", layerErr39)
				}
				layerLength34++
			}
			b.Buf[layerCountOffset37] = byte(layerLength34)
			b.Buf[layerCountOffset37+1] = byte(layerLength34 >> 8)
			b.Buf[layerCountOffset37+2] = byte(layerLength34 >> 16)
			b.Buf[layerCountOffset37+3] = byte(layerLength34 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart42 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset43 := layerVectorStart42 + 4
			layerLength40 := 0
			for layerIndex41 := range value.Users {
				layerItemStart44 := len(b.Buf)
				layerErr45 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex41], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr45 != nil {
					b.Buf = b.Buf[:layerItemStart44]
					if IsLayerProjectionDrop(layerErr45) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart42]
					return fmt.Errorf("encode field users: %w", layerErr45)
				}
				layerLength40++
			}
			b.Buf[layerCountOffset43] = byte(layerLength40)
			b.Buf[layerCountOffset43+1] = byte(layerLength40 >> 8)
			b.Buf[layerCountOffset43+2] = byte(layerLength40 >> 16)
			b.Buf[layerCountOffset43+3] = byte(layerLength40 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStatsMegagroupStats, WireID: 0xef7ff916, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireef7ff916(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StatsMegagroupStats, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeStatsMegagroupStats, WireID: 0xef7ff916, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xef7ff916); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xef7ff916: %w", err)
	}
	return layerDecodeWireef7ff916Bare(profile, b, state)

}

func layerDecodeWireef7ff916Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StatsMegagroupStats, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.StatsMegagroupStats)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded46 tg.StatsDateRangeDays
			layerConcrete47, err := layerDecodeWireb637edaf(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field period: %w", err)
			}
			layerDecoded46 = *layerConcrete47
			var layerDecoded48 tg.StatsAbsValueAndPrev
			layerConcrete49, err := layerDecodeWirecb43acde(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field members: %w", err)
			}
			layerDecoded48 = *layerConcrete49
			var layerDecoded50 tg.StatsAbsValueAndPrev
			layerConcrete51, err := layerDecodeWirecb43acde(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field messages: %w", err)
			}
			layerDecoded50 = *layerConcrete51
			var layerDecoded52 tg.StatsAbsValueAndPrev
			layerConcrete53, err := layerDecodeWirecb43acde(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field viewers: %w", err)
			}
			layerDecoded52 = *layerConcrete53
			var layerDecoded54 tg.StatsAbsValueAndPrev
			layerConcrete55, err := layerDecodeWirecb43acde(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field posters: %w", err)
			}
			layerDecoded54 = *layerConcrete55
			var layerDecoded56 tg.StatsGraphClass
			layerClass57, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field growth_graph: %w", err)
			}
			layerDecoded56 = layerClass57
			var layerDecoded58 tg.StatsGraphClass
			layerClass59, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field members_graph: %w", err)
			}
			layerDecoded58 = layerClass59
			var layerDecoded60 tg.StatsGraphClass
			layerClass61, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field new_members_by_source_graph: %w", err)
			}
			layerDecoded60 = layerClass61
			var layerDecoded62 tg.StatsGraphClass
			layerClass63, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field languages_graph: %w", err)
			}
			layerDecoded62 = layerClass63
			var layerDecoded64 tg.StatsGraphClass
			layerClass65, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field messages_graph: %w", err)
			}
			layerDecoded64 = layerClass65
			var layerDecoded66 tg.StatsGraphClass
			layerClass67, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field actions_graph: %w", err)
			}
			layerDecoded66 = layerClass67
			var layerDecoded68 tg.StatsGraphClass
			layerClass69, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field top_hours_graph: %w", err)
			}
			layerDecoded68 = layerClass69
			var layerDecoded70 tg.StatsGraphClass
			layerClass71, err := layerDecodeClassStatsGraph(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field weekdays_graph: %w", err)
			}
			layerDecoded70 = layerClass71
			var layerDecoded72 []tg.StatsGroupTopPoster
			layerDecodeState73, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field top_posters vector depth: %w", err)
			}
			layerLength74, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState73)
			if err != nil {
				return nil, fmt.Errorf("decode field top_posters: %w", err)
			}
			var layerVector75 []tg.StatsGroupTopPoster
			if layerLength74 > 0 {
				capacity := layerLength74
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector75 = make([]tg.StatsGroupTopPoster, 0, capacity)
			}
			for index := 0; index < layerLength74; index++ {
				var element tg.StatsGroupTopPoster
				layerConcrete76, err := layerDecodeWire9d04af9b(profile, b, &layerDecodeState73)
				if err != nil {
					return nil, fmt.Errorf("decode field top_posters element: %w", err)
				}
				element = *layerConcrete76
				layerVector75 = append(layerVector75, element)
			}
			layerDecoded72 = layerVector75
			var layerDecoded77 []tg.StatsGroupTopAdmin
			layerDecodeState78, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field top_admins vector depth: %w", err)
			}
			layerLength79, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState78)
			if err != nil {
				return nil, fmt.Errorf("decode field top_admins: %w", err)
			}
			var layerVector80 []tg.StatsGroupTopAdmin
			if layerLength79 > 0 {
				capacity := layerLength79
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector80 = make([]tg.StatsGroupTopAdmin, 0, capacity)
			}
			for index := 0; index < layerLength79; index++ {
				var element tg.StatsGroupTopAdmin
				layerConcrete81, err := layerDecodeWired7584c87(profile, b, &layerDecodeState78)
				if err != nil {
					return nil, fmt.Errorf("decode field top_admins element: %w", err)
				}
				element = *layerConcrete81
				layerVector80 = append(layerVector80, element)
			}
			layerDecoded77 = layerVector80
			var layerDecoded82 []tg.StatsGroupTopInviter
			layerDecodeState83, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field top_inviters vector depth: %w", err)
			}
			layerLength84, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState83)
			if err != nil {
				return nil, fmt.Errorf("decode field top_inviters: %w", err)
			}
			var layerVector85 []tg.StatsGroupTopInviter
			if layerLength84 > 0 {
				capacity := layerLength84
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector85 = make([]tg.StatsGroupTopInviter, 0, capacity)
			}
			for index := 0; index < layerLength84; index++ {
				var element tg.StatsGroupTopInviter
				layerConcrete86, err := layerDecodeWire535f779d(profile, b, &layerDecodeState83)
				if err != nil {
					return nil, fmt.Errorf("decode field top_inviters element: %w", err)
				}
				element = *layerConcrete86
				layerVector85 = append(layerVector85, element)
			}
			layerDecoded82 = layerVector85
			var layerDecoded87 []tg.UserClass
			layerDecodeState88, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength89, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState88)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector90 []tg.UserClass
			if layerLength89 > 0 {
				capacity := layerLength89
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector90 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength89; index++ {
				var element tg.UserClass
				layerClass91, err := layerDecodeClassUser(profile, b, &layerDecodeState88)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass91
				layerVector90 = append(layerVector90, element)
			}
			layerDecoded87 = layerVector90
			if true {
				value.Period = layerDecoded46
			}
			if true {
				value.Members = layerDecoded48
			}
			if true {
				value.Messages = layerDecoded50
			}
			if true {
				value.Viewers = layerDecoded52
			}
			if true {
				value.Posters = layerDecoded54
			}
			if true {
				value.GrowthGraph = layerDecoded56
			}
			if true {
				value.MembersGraph = layerDecoded58
			}
			if true {
				value.NewMembersBySourceGraph = layerDecoded60
			}
			if true {
				value.LanguagesGraph = layerDecoded62
			}
			if true {
				value.MessagesGraph = layerDecoded64
			}
			if true {
				value.ActionsGraph = layerDecoded66
			}
			if true {
				value.TopHoursGraph = layerDecoded68
			}
			if true {
				value.WeekdaysGraph = layerDecoded70
			}
			if true {
				value.TopPosters = layerDecoded72
			}
			if true {
				value.TopAdmins = layerDecoded77
			}
			if true {
				value.TopInviters = layerDecoded82
			}
			if true {
				value.Users = layerDecoded87
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeStatsMegagroupStats, WireID: 0xef7ff916, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiref0e3e596Bare(profile LayerProfile, value *tg.MessagesDialogsNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesDialogsNotModified, WireID: 0xf0e3e596, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiref0e3e596BareBody(profile LayerProfile, value *tg.MessagesDialogsNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiref0e3e596Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirefae69f56Bare(profile LayerProfile, value *tg.MessageActionCustomAction, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionCustomAction, WireID: 0xfae69f56, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirefae69f56BareBody(profile LayerProfile, value *tg.MessageActionCustomAction, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirefae69f56Bare(profile, value, b, state)
}
func layerDecodeWirefae69f56(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionCustomAction, error) {
	value := new(tg.MessageActionCustomAction)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
