// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

func layerEncodeWire31a2a35eBareBody(profile LayerProfile, value *tg.BotsRequestWebViewButtonRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			if err := layerEncodeClassInputUserBody(profile, value.UserID, b, state); err != nil {
				return fmt.Errorf("encode field user_id: %w", err)
			}
			if err := layerEncodeFamilyKeyboardButtonBody(profile, &(value.Button), b, state); err != nil {
				return fmt.Errorf("encode field button: %w", err)
			}
			return nil

		}
	case LayerProfile229:
		{
			if err := layerEncodeClassInputUserBody(profile, value.UserID, b, state); err != nil {
				return fmt.Errorf("encode field user_id: %w", err)
			}
			b.PutID(0x2f67a72f)
			if err := layerEncodeWire2f67a72fBareBody(profile, &(value.Button), b, state); err != nil {
				return fmt.Errorf("encode field button: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodBotsRequestWebViewButton, WireID: 0x31a2a35e, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire31a2a35e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.BotsRequestWebViewButtonRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	case LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodBotsRequestWebViewButton, WireID: 0x31a2a35e, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x31a2a35e); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x31a2a35e: %w", err)
	}
	return layerDecodeWire31a2a35eBare(profile, b, state)

}

func layerDecodeWire31a2a35eBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.BotsRequestWebViewButtonRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.BotsRequestWebViewButtonRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var layerDecoded3 tg.InputUserClass
			layerClass4, err := layerDecodeClassInputUser(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field user_id: %w", err)
			}
			layerDecoded3 = layerClass4
			var layerDecoded5 tg.KeyboardButton
			layerID7, err := b.PeekID()
			if err != nil {
				return nil, fmt.Errorf("decode field button constructor: %w", err)
			}
			var layerConcrete6 *tg.KeyboardButton
			switch layerID7 {
			case 0x02b78156:
				layerConcrete6, err = layerDecodeWire02b78156(profile, b, state)
			case 0x7d170cff:
				layerConcrete6, err = layerDecodeWire7d170cff(profile, b, state)
			case 0xaa40f94d:
				layerConcrete6, err = layerDecodeWireaa40f94d(profile, b, state)
			case 0x5b0f15f5:
				layerConcrete6, err = layerDecodeWire5b0f15f5(profile, b, state)
			case 0x417efd8f:
				layerConcrete6, err = layerDecodeWire417efd8f(profile, b, state)
			case 0x7a11d782:
				layerConcrete6, err = layerDecodeWire7a11d782(profile, b, state)
			case 0xe15c4370:
				layerConcrete6, err = layerDecodeWiree15c4370(profile, b, state)
			default:
				return nil, &LayerCodecError{Operation: "decode", Profile: profile, WireID: layerID7, Reason: "wire ID is not a constructor of exact singular class profile"}
			}
			if err != nil {
				return nil, fmt.Errorf("decode field button: %w", err)
			}
			layerDecoded5 = *layerConcrete6
			if true {
				value.UserID = layerDecoded3
			}
			if true {
				value.Button = layerDecoded5
			}
			return value, nil

		}
	case LayerProfile229:
		{
			var layerDecoded3 tg.InputUserClass
			layerClass4, err := layerDecodeClassInputUser(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field user_id: %w", err)
			}
			layerDecoded3 = layerClass4
			var layerDecoded5 tg.KeyboardButton
			layerConcrete6, err := layerDecodeWire2f67a72f(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field button: %w", err)
			}
			layerDecoded5 = *layerConcrete6
			if true {
				value.UserID = layerDecoded3
			}
			if true {
				value.Button = layerDecoded5
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodBotsRequestWebViewButton, WireID: 0x31a2a35e, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire3751b49eBare(profile LayerProfile, value *tg.InputMessagesFilterMusic, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputMessagesFilterMusic, WireID: 0x3751b49e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire3751b49eBareBody(profile LayerProfile, value *tg.InputMessagesFilterMusic, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire3751b49eBare(profile, value, b, state)
}
func layerDecodeWire3751b49e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputMessagesFilterMusic, error) {
	value := new(tg.InputMessagesFilterMusic)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire390d5c5eBareBody(profile LayerProfile, value *tg.AuthLoginTokenSuccess, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassAuthAuthorizationBody(profile, value.Authorization, b, state); err != nil {
				return fmt.Errorf("encode field authorization: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthLoginTokenSuccess, WireID: 0x390d5c5e, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire390d5c5e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AuthLoginTokenSuccess, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeAuthLoginTokenSuccess, WireID: 0x390d5c5e, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x390d5c5e); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x390d5c5e: %w", err)
	}
	return layerDecodeWire390d5c5eBare(profile, b, state)

}

func layerDecodeWire390d5c5eBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AuthLoginTokenSuccess, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.AuthLoginTokenSuccess)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.AuthAuthorizationClass
			layerClass3, err := layerDecodeClassAuthAuthorization(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field authorization: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Authorization = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthLoginTokenSuccess, WireID: 0x390d5c5e, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire4119b95eBare(profile LayerProfile, value *tg.InputReplyToEphemeralMessage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputReplyToEphemeralMessage, WireID: 0x4119b95e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire4119b95eBareBody(profile LayerProfile, value *tg.InputReplyToEphemeralMessage, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire4119b95eBare(profile, value, b, state)
}
func layerDecodeWire4119b95e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputReplyToEphemeralMessage, error) {
	value := new(tg.InputReplyToEphemeralMessage)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire57de635eBare(profile LayerProfile, value *tg.MessageActionSuggestProfilePhoto, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionSuggestProfilePhoto, WireID: 0x57de635e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire57de635eBareBody(profile LayerProfile, value *tg.MessageActionSuggestProfilePhoto, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire57de635eBare(profile, value, b, state)
}
func layerDecodeWire57de635e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionSuggestProfilePhoto, error) {
	value := new(tg.MessageActionSuggestProfilePhoto)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire87d0759eBare(profile LayerProfile, value *tg.HelpCountriesList, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeHelpCountriesList, WireID: 0x87d0759e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire87d0759eBareBody(profile LayerProfile, value *tg.HelpCountriesList, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire87d0759eBare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire9375341eBare(profile LayerProfile, value *tg.UpdateSavedGifs, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedGifs, WireID: 0x9375341e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9375341eBareBody(profile LayerProfile, value *tg.UpdateSavedGifs, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9375341eBare(profile, value, b, state)
}
func layerDecodeWire9375341e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateSavedGifs, error) {
	value := new(tg.UpdateSavedGifs)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire9f84f49eBare(profile LayerProfile, value *tg.MessageMediaUnsupported, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageMediaUnsupported, WireID: 0x9f84f49e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9f84f49eBareBody(profile LayerProfile, value *tg.MessageMediaUnsupported, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9f84f49eBare(profile, value, b, state)
}
func layerDecodeWire9f84f49e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageMediaUnsupported, error) {
	value := new(tg.MessageMediaUnsupported)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire9fc55fdeBare(profile LayerProfile, value *tg.InputMediaTodo, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputMediaTodo, WireID: 0x9fc55fde, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9fc55fdeBareBody(profile LayerProfile, value *tg.InputMediaTodo, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9fc55fdeBare(profile, value, b, state)
}
func layerDecodeWire9fc55fde(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputMediaTodo, error) {
	value := new(tg.InputMediaTodo)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirea2a5371eBare(profile LayerProfile, value *tg.PeerChannel, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePeerChannel, WireID: 0xa2a5371e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea2a5371eBareBody(profile LayerProfile, value *tg.PeerChannel, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea2a5371eBare(profile, value, b, state)
}
func layerDecodeWirea2a5371e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PeerChannel, error) {
	value := new(tg.PeerChannel)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireab0f6b1eBare(profile LayerProfile, value *tg.UpdatePhoneCall, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdatePhoneCall, WireID: 0xab0f6b1e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireab0f6b1eBareBody(profile LayerProfile, value *tg.UpdatePhoneCall, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireab0f6b1eBare(profile, value, b, state)
}
func layerDecodeWireab0f6b1e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePhoneCall, error) {
	value := new(tg.UpdatePhoneCall)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWireac81bbdeBareBody(profile LayerProfile, value *tg.MessagesToggleSavedDialogPinRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.Pinned {
				wireFlags0.Set(0)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if err := layerEncodeClassInputDialogPeerBody(profile, value.Peer, b, state); err != nil {
				return fmt.Errorf("encode field peer: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesToggleSavedDialogPin, WireID: 0xac81bbde, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireac81bbde(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesToggleSavedDialogPinRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodMessagesToggleSavedDialogPin, WireID: 0xac81bbde, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xac81bbde); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xac81bbde: %w", err)
	}
	return layerDecodeWireac81bbdeBare(profile, b, state)

}

func layerDecodeWireac81bbdeBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesToggleSavedDialogPinRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesToggleSavedDialogPinRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded2 := wireFlags0.Has(0)
			var layerDecoded3 tg.InputDialogPeerClass
			layerClass4, err := layerDecodeClassInputDialogPeer(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field peer: %w", err)
			}
			layerDecoded3 = layerClass4
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Pinned = layerDecoded2
			}
			if true {
				value.Peer = layerDecoded3
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesToggleSavedDialogPin, WireID: 0xac81bbde, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWireba7bb15eBareBody(profile LayerProfile, value *tg.PollResults, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if value.Flags.Has(3) && value.RecentVoters == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePollResults, Reason: "malformed canonical value: explicit flag has nil interface field recent_voters"}
			}
			if value.Flags.Has(4) && value.SolutionEntities == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePollResults, Reason: "malformed canonical value: explicit flag has nil interface field solution_entities"}
			}
			if value.Flags.Has(5) && value.SolutionMedia == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePollResults, Reason: "malformed canonical value: explicit flag has nil interface field solution_media"}
			}
			layerEncoded8 := &bin.Buffer{}
			layerPresent16 := (value.Flags.Has(1) || value.Results != nil)
			if layerPresent16 {
				layerErr9 := func() error {
					if len(value.Results) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerVectorStart12 := len(layerEncoded8.Buf)
					layerEncoded8.PutVectorHeader(0)
					layerCountOffset13 := layerVectorStart12 + 4
					layerLength10 := 0
					for layerIndex11 := range value.Results {
						layerItemStart14 := len(layerEncoded8.Buf)
						layerErr15 := func() error {
							layerEncoded8.PutID(0x3645230a)
							if err := layerEncodeWire3645230aBareBody(profile, &(value.Results[layerIndex11]), layerEncoded8, state); err != nil {
								return fmt.Errorf("encode prepared field results element: %w", err)
							}
							return nil
						}()
						if layerErr15 != nil {
							layerEncoded8.Buf = layerEncoded8.Buf[:layerItemStart14]
							if IsLayerProjectionDrop(layerErr15) {
								continue
							}
							layerEncoded8.Buf = layerEncoded8.Buf[:layerVectorStart12]
							return fmt.Errorf("encode prepared field results: %w", layerErr15)
						}
						layerLength10++
					}
					layerEncoded8.Buf[layerCountOffset13] = byte(layerLength10)
					layerEncoded8.Buf[layerCountOffset13+1] = byte(layerLength10 >> 8)
					layerEncoded8.Buf[layerCountOffset13+2] = byte(layerLength10 >> 16)
					layerEncoded8.Buf[layerCountOffset13+3] = byte(layerLength10 >> 24)
					return nil
				}()
				if layerErr9 != nil {
					if IsLayerProjectionDrop(layerErr9) {
						layerPresent16 = false
						layerEncoded8.Reset()
					} else {
						return fmt.Errorf("encode optional field results: %w", layerErr9)
					}
				}
			}
			layerEncoded17 := &bin.Buffer{}
			layerPresent25 := (value.Flags.Has(3) || value.RecentVoters != nil)
			if layerPresent25 {
				layerErr18 := func() error {
					if len(value.RecentVoters) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerVectorStart21 := len(layerEncoded17.Buf)
					layerEncoded17.PutVectorHeader(0)
					layerCountOffset22 := layerVectorStart21 + 4
					layerLength19 := 0
					for layerIndex20 := range value.RecentVoters {
						layerItemStart23 := len(layerEncoded17.Buf)
						layerErr24 := func() error {
							if err := layerEncodeClassPeerBody(profile, value.RecentVoters[layerIndex20], layerEncoded17, state); err != nil {
								return fmt.Errorf("encode prepared field recent_voters element: %w", err)
							}
							return nil
						}()
						if layerErr24 != nil {
							layerEncoded17.Buf = layerEncoded17.Buf[:layerItemStart23]
							if IsLayerProjectionDrop(layerErr24) {
								continue
							}
							layerEncoded17.Buf = layerEncoded17.Buf[:layerVectorStart21]
							return fmt.Errorf("encode prepared field recent_voters: %w", layerErr24)
						}
						layerLength19++
					}
					layerEncoded17.Buf[layerCountOffset22] = byte(layerLength19)
					layerEncoded17.Buf[layerCountOffset22+1] = byte(layerLength19 >> 8)
					layerEncoded17.Buf[layerCountOffset22+2] = byte(layerLength19 >> 16)
					layerEncoded17.Buf[layerCountOffset22+3] = byte(layerLength19 >> 24)
					return nil
				}()
				if layerErr18 != nil {
					if IsLayerProjectionDrop(layerErr18) {
						layerPresent25 = false
						layerEncoded17.Reset()
					} else {
						return fmt.Errorf("encode optional field recent_voters: %w", layerErr18)
					}
				}
			}
			layerEncoded26 := &bin.Buffer{}
			layerPresent34 := (value.Flags.Has(4) || value.Solution != "") || (value.Flags.Has(4) || value.SolutionEntities != nil)
			if layerPresent34 {
				layerErr27 := func() error {
					if len(value.SolutionEntities) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerVectorStart30 := len(layerEncoded26.Buf)
					layerEncoded26.PutVectorHeader(0)
					layerCountOffset31 := layerVectorStart30 + 4
					layerLength28 := 0
					for layerIndex29 := range value.SolutionEntities {
						layerItemStart32 := len(layerEncoded26.Buf)
						layerErr33 := func() error {
							if err := layerEncodeClassMessageEntityBody(profile, value.SolutionEntities[layerIndex29], layerEncoded26, state); err != nil {
								return fmt.Errorf("encode prepared field solution_entities element: %w", err)
							}
							return nil
						}()
						if layerErr33 != nil {
							layerEncoded26.Buf = layerEncoded26.Buf[:layerItemStart32]
							if IsLayerProjectionDrop(layerErr33) {
								continue
							}
							layerEncoded26.Buf = layerEncoded26.Buf[:layerVectorStart30]
							return fmt.Errorf("encode prepared field solution_entities: %w", layerErr33)
						}
						layerLength28++
					}
					layerEncoded26.Buf[layerCountOffset31] = byte(layerLength28)
					layerEncoded26.Buf[layerCountOffset31+1] = byte(layerLength28 >> 8)
					layerEncoded26.Buf[layerCountOffset31+2] = byte(layerLength28 >> 16)
					layerEncoded26.Buf[layerCountOffset31+3] = byte(layerLength28 >> 24)
					return nil
				}()
				if layerErr27 != nil {
					if IsLayerProjectionDrop(layerErr27) {
						layerPresent34 = false
						layerEncoded26.Reset()
					} else {
						return fmt.Errorf("encode optional field solution_entities: %w", layerErr27)
					}
				}
			}
			layerEncoded35 := &bin.Buffer{}
			layerPresent37 := (value.Flags.Has(5) || value.SolutionMedia != nil)
			if layerPresent37 {
				layerErr36 := func() error {
					if err := layerEncodeClassMessageMediaBody(profile, value.SolutionMedia, layerEncoded35, state); err != nil {
						return fmt.Errorf("encode prepared field solution_media: %w", err)
					}
					return nil
				}()
				if layerErr36 != nil {
					if IsLayerProjectionDrop(layerErr36) {
						layerPresent37 = false
						layerEncoded35.Reset()
					} else {
						return fmt.Errorf("encode optional field solution_media: %w", layerErr36)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.Min {
				wireFlags0.Set(0)
			}
			if layerPresent16 {
				wireFlags0.Set(1)
			}
			if value.Flags.Has(2) || value.TotalVoters != 0 {
				wireFlags0.Set(2)
			}
			if layerPresent25 {
				wireFlags0.Set(3)
			}
			if ((value.Flags.Has(4) || value.Solution != "") || layerPresent34) && !layerPresent34 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePollResults, Reason: "shared flag group flags.4 projected only partially"}
			}
			if (value.Flags.Has(4) || value.Solution != "") || layerPresent34 {
				wireFlags0.Set(4)
			}
			if layerPresent37 {
				wireFlags0.Set(5)
			}
			if value.Flags.Has(6) || value.HasUnreadVotes {
				wireFlags0.Set(6)
			}
			if value.Flags.Has(7) || value.CanViewStats {
				wireFlags0.Set(7)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if wireFlags0.Has(1) {
				b.Buf = append(b.Buf, layerEncoded8.Buf...)
			}
			if wireFlags0.Has(2) {
				b.PutInt(value.TotalVoters)
			}
			if wireFlags0.Has(3) {
				b.Buf = append(b.Buf, layerEncoded17.Buf...)
			}
			if wireFlags0.Has(4) {
				if err := b.PutStringChecked(value.Solution); err != nil {
					return fmt.Errorf("encode field solution: %w", err)
				}
			}
			if wireFlags0.Has(4) {
				b.Buf = append(b.Buf, layerEncoded26.Buf...)
			}
			if wireFlags0.Has(5) {
				b.Buf = append(b.Buf, layerEncoded35.Buf...)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePollResults, WireID: 0xba7bb15e, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireba7bb15e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PollResults, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypePollResults, WireID: 0xba7bb15e, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xba7bb15e); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xba7bb15e: %w", err)
	}
	return layerDecodeWireba7bb15eBare(profile, b, state)

}

func layerDecodeWireba7bb15eBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PollResults, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PollResults)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded38 := wireFlags0.Has(0)
			layerDecoded39 := wireFlags0.Has(6)
			layerDecoded40 := wireFlags0.Has(7)
			var layerDecoded41 []tg.PollAnswerVoters
			if wireFlags0.Has(1) {
				layerDecodeState42, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field results vector depth: %w", err)
				}
				layerLength43, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState42)
				if err != nil {
					return nil, fmt.Errorf("decode field results: %w", err)
				}
				var layerVector44 []tg.PollAnswerVoters
				if layerLength43 > 0 {
					capacity := layerLength43
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector44 = make([]tg.PollAnswerVoters, 0, capacity)
				}
				for index := 0; index < layerLength43; index++ {
					var element tg.PollAnswerVoters
					layerConcrete45, err := layerDecodeWire3645230a(profile, b, &layerDecodeState42)
					if err != nil {
						return nil, fmt.Errorf("decode field results element: %w", err)
					}
					element = *layerConcrete45
					layerVector44 = append(layerVector44, element)
				}
				layerDecoded41 = layerVector44
			}
			var layerDecoded46 int
			if wireFlags0.Has(2) {
				layerPrimitive47, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field total_voters: %w", err)
				}
				layerDecoded46 = layerPrimitive47
			}
			var layerDecoded48 []tg.PeerClass
			if wireFlags0.Has(3) {
				layerDecodeState49, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field recent_voters vector depth: %w", err)
				}
				layerLength50, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState49)
				if err != nil {
					return nil, fmt.Errorf("decode field recent_voters: %w", err)
				}
				var layerVector51 []tg.PeerClass
				if layerLength50 > 0 {
					capacity := layerLength50
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector51 = make([]tg.PeerClass, 0, capacity)
				}
				for index := 0; index < layerLength50; index++ {
					var element tg.PeerClass
					layerClass52, err := layerDecodeClassPeer(profile, b, &layerDecodeState49)
					if err != nil {
						return nil, fmt.Errorf("decode field recent_voters element: %w", err)
					}
					element = layerClass52
					layerVector51 = append(layerVector51, element)
				}
				layerDecoded48 = layerVector51
			}
			var layerDecoded53 string
			if wireFlags0.Has(4) {
				layerPrimitive54, err := b.String()
				if err != nil {
					return nil, fmt.Errorf("decode field solution: %w", err)
				}
				layerDecoded53 = layerPrimitive54
			}
			var layerDecoded55 []tg.MessageEntityClass
			if wireFlags0.Has(4) {
				layerDecodeState56, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field solution_entities vector depth: %w", err)
				}
				layerLength57, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState56)
				if err != nil {
					return nil, fmt.Errorf("decode field solution_entities: %w", err)
				}
				var layerVector58 []tg.MessageEntityClass
				if layerLength57 > 0 {
					capacity := layerLength57
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector58 = make([]tg.MessageEntityClass, 0, capacity)
				}
				for index := 0; index < layerLength57; index++ {
					var element tg.MessageEntityClass
					layerClass59, err := layerDecodeClassMessageEntity(profile, b, &layerDecodeState56)
					if err != nil {
						return nil, fmt.Errorf("decode field solution_entities element: %w", err)
					}
					element = layerClass59
					layerVector58 = append(layerVector58, element)
				}
				layerDecoded55 = layerVector58
			}
			var layerDecoded60 tg.MessageMediaClass
			if wireFlags0.Has(5) {
				layerClass61, err := layerDecodeClassMessageMedia(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field solution_media: %w", err)
				}
				layerDecoded60 = layerClass61
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Min = layerDecoded38
			}
			if wireFlags0.Has(6) {
				value.Flags.Set(6)
				value.HasUnreadVotes = layerDecoded39
			}
			if wireFlags0.Has(7) {
				value.Flags.Set(7)
				value.CanViewStats = layerDecoded40
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.Results = layerDecoded41
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.TotalVoters = layerDecoded46
			}
			if wireFlags0.Has(3) {
				value.Flags.Set(3)
				value.RecentVoters = layerDecoded48
			}
			if wireFlags0.Has(4) {
				value.Flags.Set(4)
				value.Solution = layerDecoded53
			}
			if wireFlags0.Has(4) {
				value.Flags.Set(4)
				value.SolutionEntities = layerDecoded55
			}
			if wireFlags0.Has(5) {
				value.Flags.Set(5)
				value.SolutionMedia = layerDecoded60
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypePollResults, WireID: 0xba7bb15e, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirec39a2adeBare(profile LayerProfile, value *tg.UpdateWebBrowserSettings, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateWebBrowserSettings, WireID: 0xc39a2ade, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirec39a2adeBareBody(profile LayerProfile, value *tg.UpdateWebBrowserSettings, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirec39a2adeBare(profile, value, b, state)
}
func layerDecodeWirec39a2ade(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateWebBrowserSettings, error) {
	value := new(tg.UpdateWebBrowserSettings)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirecb43acdeBare(profile LayerProfile, value *tg.StatsAbsValueAndPrev, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStatsAbsValueAndPrev, WireID: 0xcb43acde, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirecb43acdeBareBody(profile LayerProfile, value *tg.StatsAbsValueAndPrev, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirecb43acdeBare(profile, value, b, state)
}
func layerDecodeWirecb43acde(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StatsAbsValueAndPrev, error) {
	value := new(tg.StatsAbsValueAndPrev)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirecc1a241eBare(profile LayerProfile, value *tg.Config, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeConfig, WireID: 0xcc1a241e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirecc1a241eBareBody(profile LayerProfile, value *tg.Config, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirecc1a241eBare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiredc58f31eBare(profile LayerProfile, value *tg.UpdateStarGiftAuctionUserState, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateStarGiftAuctionUserState, WireID: 0xdc58f31e, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiredc58f31eBareBody(profile LayerProfile, value *tg.UpdateStarGiftAuctionUserState, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiredc58f31eBare(profile, value, b, state)
}
func layerDecodeWiredc58f31e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateStarGiftAuctionUserState, error) {
	value := new(tg.UpdateStarGiftAuctionUserState)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree5bdf8deBare(profile LayerProfile, value *tg.UpdateUserStatus, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateUserStatus, WireID: 0xe5bdf8de, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree5bdf8deBareBody(profile LayerProfile, value *tg.UpdateUserStatus, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree5bdf8deBare(profile, value, b, state)
}
func layerDecodeWiree5bdf8de(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateUserStatus, error) {
	value := new(tg.UpdateUserStatus)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWireedfc111eBareBody(profile LayerProfile, value *tg.UpdateDraftMessage, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if value.Flags.Has(1) && value.SavedPeerID == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateDraftMessage, Reason: "malformed canonical value: explicit flag has nil interface field saved_peer_id"}
			}
			layerEncoded4 := &bin.Buffer{}
			layerPresent6 := (value.Flags.Has(1) || value.SavedPeerID != nil)
			if layerPresent6 {
				layerErr5 := func() error {
					if err := layerEncodeClassPeerBody(profile, value.SavedPeerID, layerEncoded4, state); err != nil {
						return fmt.Errorf("encode prepared field saved_peer_id: %w", err)
					}
					return nil
				}()
				if layerErr5 != nil {
					if IsLayerProjectionDrop(layerErr5) {
						layerPresent6 = false
						layerEncoded4.Reset()
					} else {
						return fmt.Errorf("encode optional field saved_peer_id: %w", layerErr5)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.TopMsgID != 0 {
				wireFlags0.Set(0)
			}
			if layerPresent6 {
				wireFlags0.Set(1)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if err := layerEncodeClassPeerBody(profile, value.Peer, b, state); err != nil {
				return fmt.Errorf("encode field peer: %w", err)
			}
			if wireFlags0.Has(0) {
				b.PutInt(value.TopMsgID)
			}
			if wireFlags0.Has(1) {
				b.Buf = append(b.Buf, layerEncoded4.Buf...)
			}
			if err := layerEncodeClassDraftMessageBody(profile, value.Draft, b, state); err != nil {
				return fmt.Errorf("encode field draft: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateDraftMessage, WireID: 0xedfc111e, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireedfc111e(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateDraftMessage, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeUpdateDraftMessage, WireID: 0xedfc111e, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xedfc111e); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xedfc111e: %w", err)
	}
	return layerDecodeWireedfc111eBare(profile, b, state)

}

func layerDecodeWireedfc111eBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateDraftMessage, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.UpdateDraftMessage)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			var layerDecoded7 tg.PeerClass
			layerClass8, err := layerDecodeClassPeer(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field peer: %w", err)
			}
			layerDecoded7 = layerClass8
			var layerDecoded9 int
			if wireFlags0.Has(0) {
				layerPrimitive10, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field top_msg_id: %w", err)
				}
				layerDecoded9 = layerPrimitive10
			}
			var layerDecoded11 tg.PeerClass
			if wireFlags0.Has(1) {
				layerClass12, err := layerDecodeClassPeer(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field saved_peer_id: %w", err)
				}
				layerDecoded11 = layerClass12
			}
			var layerDecoded13 tg.DraftMessageClass
			layerClass14, err := layerDecodeClassDraftMessage(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field draft: %w", err)
			}
			layerDecoded13 = layerClass14
			if true {
				value.Peer = layerDecoded7
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.TopMsgID = layerDecoded9
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.SavedPeerID = layerDecoded11
			}
			if true {
				value.Draft = layerDecoded13
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateDraftMessage, WireID: 0xedfc111e, Reason: "wire ID is unavailable in exact profile"}
	}
}
