// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

func layerEncodeWire15051f54BareBody(profile LayerProfile, value *tg.PhotosPhotosSlice, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			b.PutInt(value.Count)
			if len(value.Photos) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart7 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset8 := layerVectorStart7 + 4
			layerLength5 := 0
			for layerIndex6 := range value.Photos {
				layerItemStart9 := len(b.Buf)
				layerErr10 := func() error {
					if err := layerEncodeClassPhotoBody(profile, value.Photos[layerIndex6], b, state); err != nil {
						return fmt.Errorf("encode field photos element: %w", err)
					}
					return nil
				}()
				if layerErr10 != nil {
					b.Buf = b.Buf[:layerItemStart9]
					if IsLayerProjectionDrop(layerErr10) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart7]
					return fmt.Errorf("encode field photos: %w", layerErr10)
				}
				layerLength5++
			}
			b.Buf[layerCountOffset8] = byte(layerLength5)
			b.Buf[layerCountOffset8+1] = byte(layerLength5 >> 8)
			b.Buf[layerCountOffset8+2] = byte(layerLength5 >> 16)
			b.Buf[layerCountOffset8+3] = byte(layerLength5 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart13 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset14 := layerVectorStart13 + 4
			layerLength11 := 0
			for layerIndex12 := range value.Users {
				layerItemStart15 := len(b.Buf)
				layerErr16 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex12], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr16 != nil {
					b.Buf = b.Buf[:layerItemStart15]
					if IsLayerProjectionDrop(layerErr16) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart13]
					return fmt.Errorf("encode field users: %w", layerErr16)
				}
				layerLength11++
			}
			b.Buf[layerCountOffset14] = byte(layerLength11)
			b.Buf[layerCountOffset14+1] = byte(layerLength11 >> 8)
			b.Buf[layerCountOffset14+2] = byte(layerLength11 >> 16)
			b.Buf[layerCountOffset14+3] = byte(layerLength11 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePhotosPhotosSlice, WireID: 0x15051f54, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire15051f54(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PhotosPhotosSlice, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypePhotosPhotosSlice, WireID: 0x15051f54, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x15051f54); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x15051f54: %w", err)
	}
	return layerDecodeWire15051f54Bare(profile, b, state)

}

func layerDecodeWire15051f54Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PhotosPhotosSlice, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PhotosPhotosSlice)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded17 int
			layerPrimitive18, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field count: %w", err)
			}
			layerDecoded17 = layerPrimitive18
			var layerDecoded19 []tg.PhotoClass
			layerDecodeState20, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field photos vector depth: %w", err)
			}
			layerLength21, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState20)
			if err != nil {
				return nil, fmt.Errorf("decode field photos: %w", err)
			}
			var layerVector22 []tg.PhotoClass
			if layerLength21 > 0 {
				capacity := layerLength21
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector22 = make([]tg.PhotoClass, 0, capacity)
			}
			for index := 0; index < layerLength21; index++ {
				var element tg.PhotoClass
				layerClass23, err := layerDecodeClassPhoto(profile, b, &layerDecodeState20)
				if err != nil {
					return nil, fmt.Errorf("decode field photos element: %w", err)
				}
				element = layerClass23
				layerVector22 = append(layerVector22, element)
			}
			layerDecoded19 = layerVector22
			var layerDecoded24 []tg.UserClass
			layerDecodeState25, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength26, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState25)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector27 []tg.UserClass
			if layerLength26 > 0 {
				capacity := layerLength26
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector27 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength26; index++ {
				var element tg.UserClass
				layerClass28, err := layerDecodeClassUser(profile, b, &layerDecodeState25)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass28
				layerVector27 = append(layerVector27, element)
			}
			layerDecoded24 = layerVector27
			if true {
				value.Count = layerDecoded17
			}
			if true {
				value.Photos = layerDecoded19
			}
			if true {
				value.Users = layerDecoded24
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypePhotosPhotosSlice, WireID: 0x15051f54, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire2ea2c0d4BareBody(profile LayerProfile, value *tg.AuthAuthorization, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.TmpSessions != 0 {
				wireFlags0.Set(0)
			}
			if (value.Flags.Has(1) || value.SetupPasswordRequired) || (value.Flags.Has(1) || value.OtherwiseReloginDays != 0) {
				wireFlags0.Set(1)
			}
			if value.Flags.Has(2) || value.FutureAuthToken != nil {
				wireFlags0.Set(2)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if wireFlags0.Has(1) {
				b.PutInt(value.OtherwiseReloginDays)
			}
			if wireFlags0.Has(0) {
				b.PutInt(value.TmpSessions)
			}
			if wireFlags0.Has(2) {
				if err := b.PutBytesChecked(value.FutureAuthToken); err != nil {
					return fmt.Errorf("encode field future_auth_token: %w", err)
				}
			}
			if err := layerEncodeClassUserBody(profile, value.User, b, state); err != nil {
				return fmt.Errorf("encode field user: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthAuthorization, WireID: 0x2ea2c0d4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire2ea2c0d4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AuthAuthorization, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeAuthAuthorization, WireID: 0x2ea2c0d4, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x2ea2c0d4); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x2ea2c0d4: %w", err)
	}
	return layerDecodeWire2ea2c0d4Bare(profile, b, state)

}

func layerDecodeWire2ea2c0d4Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AuthAuthorization, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.AuthAuthorization)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded2 := wireFlags0.Has(1)
			var layerDecoded3 int
			if wireFlags0.Has(1) {
				layerPrimitive4, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field otherwise_relogin_days: %w", err)
				}
				layerDecoded3 = layerPrimitive4
			}
			var layerDecoded5 int
			if wireFlags0.Has(0) {
				layerPrimitive6, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field tmp_sessions: %w", err)
				}
				layerDecoded5 = layerPrimitive6
			}
			var layerDecoded7 []byte
			if wireFlags0.Has(2) {
				layerPrimitive8, err := b.Bytes()
				if err != nil {
					return nil, fmt.Errorf("decode field future_auth_token: %w", err)
				}
				layerDecoded7 = layerPrimitive8
			}
			var layerDecoded9 tg.UserClass
			layerClass10, err := layerDecodeClassUser(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field user: %w", err)
			}
			layerDecoded9 = layerClass10
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.SetupPasswordRequired = layerDecoded2
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.OtherwiseReloginDays = layerDecoded3
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.TmpSessions = layerDecoded5
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.FutureAuthToken = layerDecoded7
			}
			if true {
				value.User = layerDecoded9
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthAuthorization, WireID: 0x2ea2c0d4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire3371c354BareBody(profile LayerProfile, value *tg.MessagesPeerDialogs, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if len(value.Dialogs) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart12 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset13 := layerVectorStart12 + 4
			layerLength10 := 0
			for layerIndex11 := range value.Dialogs {
				layerItemStart14 := len(b.Buf)
				layerErr15 := func() error {
					if err := layerEncodeClassDialogBody(profile, value.Dialogs[layerIndex11], b, state); err != nil {
						return fmt.Errorf("encode field dialogs element: %w", err)
					}
					return nil
				}()
				if layerErr15 != nil {
					b.Buf = b.Buf[:layerItemStart14]
					if IsLayerProjectionDrop(layerErr15) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart12]
					return fmt.Errorf("encode field dialogs: %w", layerErr15)
				}
				layerLength10++
			}
			b.Buf[layerCountOffset13] = byte(layerLength10)
			b.Buf[layerCountOffset13+1] = byte(layerLength10 >> 8)
			b.Buf[layerCountOffset13+2] = byte(layerLength10 >> 16)
			b.Buf[layerCountOffset13+3] = byte(layerLength10 >> 24)
			if len(value.Messages) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart18 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset19 := layerVectorStart18 + 4
			layerLength16 := 0
			for layerIndex17 := range value.Messages {
				layerItemStart20 := len(b.Buf)
				layerErr21 := func() error {
					if err := layerEncodeClassMessageBody(profile, value.Messages[layerIndex17], b, state); err != nil {
						return fmt.Errorf("encode field messages element: %w", err)
					}
					return nil
				}()
				if layerErr21 != nil {
					b.Buf = b.Buf[:layerItemStart20]
					if IsLayerProjectionDrop(layerErr21) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart18]
					return fmt.Errorf("encode field messages: %w", layerErr21)
				}
				layerLength16++
			}
			b.Buf[layerCountOffset19] = byte(layerLength16)
			b.Buf[layerCountOffset19+1] = byte(layerLength16 >> 8)
			b.Buf[layerCountOffset19+2] = byte(layerLength16 >> 16)
			b.Buf[layerCountOffset19+3] = byte(layerLength16 >> 24)
			if len(value.Chats) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart24 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset25 := layerVectorStart24 + 4
			layerLength22 := 0
			for layerIndex23 := range value.Chats {
				layerItemStart26 := len(b.Buf)
				layerErr27 := func() error {
					if err := layerEncodeClassChatBody(profile, value.Chats[layerIndex23], b, state); err != nil {
						return fmt.Errorf("encode field chats element: %w", err)
					}
					return nil
				}()
				if layerErr27 != nil {
					b.Buf = b.Buf[:layerItemStart26]
					if IsLayerProjectionDrop(layerErr27) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart24]
					return fmt.Errorf("encode field chats: %w", layerErr27)
				}
				layerLength22++
			}
			b.Buf[layerCountOffset25] = byte(layerLength22)
			b.Buf[layerCountOffset25+1] = byte(layerLength22 >> 8)
			b.Buf[layerCountOffset25+2] = byte(layerLength22 >> 16)
			b.Buf[layerCountOffset25+3] = byte(layerLength22 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart30 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset31 := layerVectorStart30 + 4
			layerLength28 := 0
			for layerIndex29 := range value.Users {
				layerItemStart32 := len(b.Buf)
				layerErr33 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex29], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr33 != nil {
					b.Buf = b.Buf[:layerItemStart32]
					if IsLayerProjectionDrop(layerErr33) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart30]
					return fmt.Errorf("encode field users: %w", layerErr33)
				}
				layerLength28++
			}
			b.Buf[layerCountOffset31] = byte(layerLength28)
			b.Buf[layerCountOffset31+1] = byte(layerLength28 >> 8)
			b.Buf[layerCountOffset31+2] = byte(layerLength28 >> 16)
			b.Buf[layerCountOffset31+3] = byte(layerLength28 >> 24)
			b.PutID(0xa56c2a3e)
			if err := layerEncodeWirea56c2a3eBareBody(profile, &(value.State), b, state); err != nil {
				return fmt.Errorf("encode field state: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesPeerDialogs, WireID: 0x3371c354, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire3371c354(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesPeerDialogs, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeMessagesPeerDialogs, WireID: 0x3371c354, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x3371c354); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x3371c354: %w", err)
	}
	return layerDecodeWire3371c354Bare(profile, b, state)

}

func layerDecodeWire3371c354Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesPeerDialogs, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesPeerDialogs)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded34 []tg.DialogClass
			layerDecodeState35, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field dialogs vector depth: %w", err)
			}
			layerLength36, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState35)
			if err != nil {
				return nil, fmt.Errorf("decode field dialogs: %w", err)
			}
			var layerVector37 []tg.DialogClass
			if layerLength36 > 0 {
				capacity := layerLength36
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector37 = make([]tg.DialogClass, 0, capacity)
			}
			for index := 0; index < layerLength36; index++ {
				var element tg.DialogClass
				layerClass38, err := layerDecodeClassDialog(profile, b, &layerDecodeState35)
				if err != nil {
					return nil, fmt.Errorf("decode field dialogs element: %w", err)
				}
				element = layerClass38
				layerVector37 = append(layerVector37, element)
			}
			layerDecoded34 = layerVector37
			var layerDecoded39 []tg.MessageClass
			layerDecodeState40, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field messages vector depth: %w", err)
			}
			layerLength41, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState40)
			if err != nil {
				return nil, fmt.Errorf("decode field messages: %w", err)
			}
			var layerVector42 []tg.MessageClass
			if layerLength41 > 0 {
				capacity := layerLength41
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector42 = make([]tg.MessageClass, 0, capacity)
			}
			for index := 0; index < layerLength41; index++ {
				var element tg.MessageClass
				layerClass43, err := layerDecodeClassMessage(profile, b, &layerDecodeState40)
				if err != nil {
					return nil, fmt.Errorf("decode field messages element: %w", err)
				}
				element = layerClass43
				layerVector42 = append(layerVector42, element)
			}
			layerDecoded39 = layerVector42
			var layerDecoded44 []tg.ChatClass
			layerDecodeState45, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field chats vector depth: %w", err)
			}
			layerLength46, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState45)
			if err != nil {
				return nil, fmt.Errorf("decode field chats: %w", err)
			}
			var layerVector47 []tg.ChatClass
			if layerLength46 > 0 {
				capacity := layerLength46
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector47 = make([]tg.ChatClass, 0, capacity)
			}
			for index := 0; index < layerLength46; index++ {
				var element tg.ChatClass
				layerClass48, err := layerDecodeClassChat(profile, b, &layerDecodeState45)
				if err != nil {
					return nil, fmt.Errorf("decode field chats element: %w", err)
				}
				element = layerClass48
				layerVector47 = append(layerVector47, element)
			}
			layerDecoded44 = layerVector47
			var layerDecoded49 []tg.UserClass
			layerDecodeState50, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength51, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState50)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector52 []tg.UserClass
			if layerLength51 > 0 {
				capacity := layerLength51
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector52 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength51; index++ {
				var element tg.UserClass
				layerClass53, err := layerDecodeClassUser(profile, b, &layerDecodeState50)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass53
				layerVector52 = append(layerVector52, element)
			}
			layerDecoded49 = layerVector52
			var layerDecoded54 tg.UpdatesState
			layerConcrete55, err := layerDecodeWirea56c2a3e(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field state: %w", err)
			}
			layerDecoded54 = *layerConcrete55
			if true {
				value.Dialogs = layerDecoded34
			}
			if true {
				value.Messages = layerDecoded39
			}
			if true {
				value.Chats = layerDecoded44
			}
			if true {
				value.Users = layerDecoded49
			}
			if true {
				value.State = layerDecoded54
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesPeerDialogs, WireID: 0x3371c354, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire3e77f614BareBody(profile LayerProfile, value *tg.InputInvoicePremiumAuthCode, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassInputStorePaymentPurposeBody(profile, value.Purpose, b, state); err != nil {
				return fmt.Errorf("encode field purpose: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputInvoicePremiumAuthCode, WireID: 0x3e77f614, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire3e77f614(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputInvoicePremiumAuthCode, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeInputInvoicePremiumAuthCode, WireID: 0x3e77f614, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x3e77f614); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x3e77f614: %w", err)
	}
	return layerDecodeWire3e77f614Bare(profile, b, state)

}

func layerDecodeWire3e77f614Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputInvoicePremiumAuthCode, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.InputInvoicePremiumAuthCode)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.InputStorePaymentPurposeClass
			layerClass3, err := layerDecodeClassInputStorePaymentPurpose(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field purpose: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Purpose = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeInputInvoicePremiumAuthCode, WireID: 0x3e77f614, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire48a30254BareBody(profile LayerProfile, value *tg.ReplyInlineMarkup, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225:
		{
			if value.Flags.Has(5) || value.ForceReply {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, Reason: "field projection rejected by policy layer-obligation/v1/field-projection/a8bcb43cf4238f8248261e234066bc4a7b226fbc6609209f33761c2d4da5b6e5"}
			}
			layerEncoded1 := &bin.Buffer{}
			layerErr2 := layerEncodeFamilyLegacyInlineKeyboardRows(profile, value.Rows, layerEncoded1, state)
			if layerErr2 != nil {
				return fmt.Errorf("encode legacy inline keyboard rows: %w", layerErr2)
			}
			b.Buf = append(b.Buf, layerEncoded1.Buf...)
			return nil

		}
	case LayerProfile226:
		{
			if value.Flags.Has(5) || value.ForceReply {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, Reason: "field projection rejected by policy layer-obligation/v1/field-projection/7f9f838ec0cfb1dbb7110fe15e0d76fe5062059d62e41ac37590026f7300d631"}
			}
			layerEncoded1 := &bin.Buffer{}
			layerErr2 := layerEncodeFamilyLegacyInlineKeyboardRows(profile, value.Rows, layerEncoded1, state)
			if layerErr2 != nil {
				return fmt.Errorf("encode legacy inline keyboard rows: %w", layerErr2)
			}
			b.Buf = append(b.Buf, layerEncoded1.Buf...)
			return nil

		}
	case LayerProfile227:
		{
			if value.Flags.Has(5) || value.ForceReply {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, Reason: "field projection rejected by policy layer-obligation/v1/field-projection/dcf09e505e960127b64b1f3a9864a0eca0c981845e423978d6833b56ed666150"}
			}
			layerEncoded1 := &bin.Buffer{}
			layerErr2 := layerEncodeFamilyLegacyInlineKeyboardRows(profile, value.Rows, layerEncoded1, state)
			if layerErr2 != nil {
				return fmt.Errorf("encode legacy inline keyboard rows: %w", layerErr2)
			}
			b.Buf = append(b.Buf, layerEncoded1.Buf...)
			return nil

		}
	case LayerProfile228:
		{
			if value.Flags.Has(5) || value.ForceReply {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, Reason: "field projection rejected by policy layer-obligation/v1/field-projection/3cdd832795e5a16171abfe4a0dc66d04f8c97b2f9ba72dcf84c6e02dd8e6e325"}
			}
			layerEncoded1 := &bin.Buffer{}
			layerErr2 := layerEncodeFamilyLegacyInlineKeyboardRows(profile, value.Rows, layerEncoded1, state)
			if layerErr2 != nil {
				return fmt.Errorf("encode legacy inline keyboard rows: %w", layerErr2)
			}
			b.Buf = append(b.Buf, layerEncoded1.Buf...)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, WireID: 0x48a30254, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire48a30254(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ReplyInlineMarkup, error) {
	switch profile {
	case LayerProfile225:

	case LayerProfile226:

	case LayerProfile227:

	case LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, WireID: 0x48a30254, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x48a30254); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x48a30254: %w", err)
	}
	return layerDecodeWire48a30254Bare(profile, b, state)

}

func layerDecodeWire48a30254Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ReplyInlineMarkup, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.ReplyInlineMarkup)
	_ = value
	switch profile {
	case LayerProfile225:
		{
			var layerDecoded3 []tg.KeyboardInlineButtonRow
			layerDecoded3, err = layerDecodeFamilyLegacyInlineKeyboardRows(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode legacy inline keyboard rows: %w", err)
			}
			if true {
				value.Rows = layerDecoded3
			}
			return value, nil

		}
	case LayerProfile226:
		{
			var layerDecoded3 []tg.KeyboardInlineButtonRow
			layerDecoded3, err = layerDecodeFamilyLegacyInlineKeyboardRows(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode legacy inline keyboard rows: %w", err)
			}
			if true {
				value.Rows = layerDecoded3
			}
			return value, nil

		}
	case LayerProfile227:
		{
			var layerDecoded3 []tg.KeyboardInlineButtonRow
			layerDecoded3, err = layerDecodeFamilyLegacyInlineKeyboardRows(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode legacy inline keyboard rows: %w", err)
			}
			if true {
				value.Rows = layerDecoded3
			}
			return value, nil

		}
	case LayerProfile228:
		{
			var layerDecoded3 []tg.KeyboardInlineButtonRow
			layerDecoded3, err = layerDecodeFamilyLegacyInlineKeyboardRows(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode legacy inline keyboard rows: %w", err)
			}
			if true {
				value.Rows = layerDecoded3
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeReplyInlineMarkup, WireID: 0x48a30254, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire60fe3294BareBody(profile LayerProfile, value *tg.DraftMessage, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if value.Flags.Has(4) && value.ReplyTo == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeDraftMessage, Reason: "malformed canonical value: explicit flag has nil interface field reply_to"}
			}
			if value.Flags.Has(3) && value.Entities == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeDraftMessage, Reason: "malformed canonical value: explicit flag has nil interface field entities"}
			}
			if value.Flags.Has(5) && value.Media == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeDraftMessage, Reason: "malformed canonical value: explicit flag has nil interface field media"}
			}
			layerEncoded7 := &bin.Buffer{}
			layerPresent9 := (value.Flags.Has(4) || value.ReplyTo != nil)
			if layerPresent9 {
				layerErr8 := func() error {
					if err := layerEncodeClassInputReplyToBody(profile, value.ReplyTo, layerEncoded7, state); err != nil {
						return fmt.Errorf("encode prepared field reply_to: %w", err)
					}
					return nil
				}()
				if layerErr8 != nil {
					if IsLayerProjectionDrop(layerErr8) {
						layerPresent9 = false
						layerEncoded7.Reset()
					} else {
						return fmt.Errorf("encode optional field reply_to: %w", layerErr8)
					}
				}
			}
			layerEncoded10 := &bin.Buffer{}
			layerPresent18 := (value.Flags.Has(3) || value.Entities != nil)
			if layerPresent18 {
				layerErr11 := func() error {
					if len(value.Entities) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerVectorStart14 := len(layerEncoded10.Buf)
					layerEncoded10.PutVectorHeader(0)
					layerCountOffset15 := layerVectorStart14 + 4
					layerLength12 := 0
					for layerIndex13 := range value.Entities {
						layerItemStart16 := len(layerEncoded10.Buf)
						layerErr17 := func() error {
							if err := layerEncodeClassMessageEntityBody(profile, value.Entities[layerIndex13], layerEncoded10, state); err != nil {
								return fmt.Errorf("encode prepared field entities element: %w", err)
							}
							return nil
						}()
						if layerErr17 != nil {
							layerEncoded10.Buf = layerEncoded10.Buf[:layerItemStart16]
							if IsLayerProjectionDrop(layerErr17) {
								continue
							}
							layerEncoded10.Buf = layerEncoded10.Buf[:layerVectorStart14]
							return fmt.Errorf("encode prepared field entities: %w", layerErr17)
						}
						layerLength12++
					}
					layerEncoded10.Buf[layerCountOffset15] = byte(layerLength12)
					layerEncoded10.Buf[layerCountOffset15+1] = byte(layerLength12 >> 8)
					layerEncoded10.Buf[layerCountOffset15+2] = byte(layerLength12 >> 16)
					layerEncoded10.Buf[layerCountOffset15+3] = byte(layerLength12 >> 24)
					return nil
				}()
				if layerErr11 != nil {
					if IsLayerProjectionDrop(layerErr11) {
						layerPresent18 = false
						layerEncoded10.Reset()
					} else {
						return fmt.Errorf("encode optional field entities: %w", layerErr11)
					}
				}
			}
			layerEncoded19 := &bin.Buffer{}
			layerPresent21 := (value.Flags.Has(5) || value.Media != nil)
			if layerPresent21 {
				layerErr20 := func() error {
					if err := layerEncodeClassInputMediaBody(profile, value.Media, layerEncoded19, state); err != nil {
						return fmt.Errorf("encode prepared field media: %w", err)
					}
					return nil
				}()
				if layerErr20 != nil {
					if IsLayerProjectionDrop(layerErr20) {
						layerPresent21 = false
						layerEncoded19.Reset()
					} else {
						return fmt.Errorf("encode optional field media: %w", layerErr20)
					}
				}
			}
			layerEncoded22 := &bin.Buffer{}
			layerPresent24 := (value.Flags.Has(8) || !value.SuggestedPost.Zero())
			if layerPresent24 {
				layerErr23 := func() error {
					layerEncoded22.PutID(0x0e8e37e5)
					if err := layerEncodeWire0e8e37e5BareBody(profile, &(value.SuggestedPost), layerEncoded22, state); err != nil {
						return fmt.Errorf("encode prepared field suggested_post: %w", err)
					}
					return nil
				}()
				if layerErr23 != nil {
					if IsLayerProjectionDrop(layerErr23) {
						layerPresent24 = false
						layerEncoded22.Reset()
					} else {
						return fmt.Errorf("encode optional field suggested_post: %w", layerErr23)
					}
				}
			}
			layerEncoded25 := &bin.Buffer{}
			layerPresent27 := (value.Flags.Has(9) || !value.RichMessage.Zero())
			if layerPresent27 {
				layerErr26 := func() error {
					layerEncoded25.PutID(0xbaf39d8b)
					if err := layerEncodeWirebaf39d8bBareBody(profile, &(value.RichMessage), layerEncoded25, state); err != nil {
						return fmt.Errorf("encode prepared field rich_message: %w", err)
					}
					return nil
				}()
				if layerErr26 != nil {
					if IsLayerProjectionDrop(layerErr26) {
						layerPresent27 = false
						layerEncoded25.Reset()
					} else {
						return fmt.Errorf("encode optional field rich_message: %w", layerErr26)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(1) || value.NoWebpage {
				wireFlags0.Set(1)
			}
			if layerPresent18 {
				wireFlags0.Set(3)
			}
			if layerPresent9 {
				wireFlags0.Set(4)
			}
			if layerPresent21 {
				wireFlags0.Set(5)
			}
			if value.Flags.Has(6) || value.InvertMedia {
				wireFlags0.Set(6)
			}
			if value.Flags.Has(7) || value.Effect != 0 {
				wireFlags0.Set(7)
			}
			if layerPresent24 {
				wireFlags0.Set(8)
			}
			if layerPresent27 {
				wireFlags0.Set(9)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if wireFlags0.Has(4) {
				b.Buf = append(b.Buf, layerEncoded7.Buf...)
			}
			if err := b.PutStringChecked(value.Message); err != nil {
				return fmt.Errorf("encode field message: %w", err)
			}
			if wireFlags0.Has(3) {
				b.Buf = append(b.Buf, layerEncoded10.Buf...)
			}
			if wireFlags0.Has(5) {
				b.Buf = append(b.Buf, layerEncoded19.Buf...)
			}
			b.PutInt(value.Date)
			if wireFlags0.Has(7) {
				b.PutLong(value.Effect)
			}
			if wireFlags0.Has(8) {
				b.Buf = append(b.Buf, layerEncoded22.Buf...)
			}
			if wireFlags0.Has(9) {
				b.Buf = append(b.Buf, layerEncoded25.Buf...)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeDraftMessage, WireID: 0x60fe3294, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire60fe3294(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.DraftMessage, error) {
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeDraftMessage, WireID: 0x60fe3294, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x60fe3294); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x60fe3294: %w", err)
	}
	return layerDecodeWire60fe3294Bare(profile, b, state)

}

func layerDecodeWire60fe3294Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.DraftMessage, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.DraftMessage)
	_ = value
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded28 := wireFlags0.Has(1)
			layerDecoded29 := wireFlags0.Has(6)
			var layerDecoded30 tg.InputReplyToClass
			if wireFlags0.Has(4) {
				layerClass31, err := layerDecodeClassInputReplyTo(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field reply_to: %w", err)
				}
				layerDecoded30 = layerClass31
			}
			var layerDecoded32 string
			layerPrimitive33, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field message: %w", err)
			}
			layerDecoded32 = layerPrimitive33
			var layerDecoded34 []tg.MessageEntityClass
			if wireFlags0.Has(3) {
				layerDecodeState35, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field entities vector depth: %w", err)
				}
				layerLength36, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState35)
				if err != nil {
					return nil, fmt.Errorf("decode field entities: %w", err)
				}
				var layerVector37 []tg.MessageEntityClass
				if layerLength36 > 0 {
					capacity := layerLength36
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector37 = make([]tg.MessageEntityClass, 0, capacity)
				}
				for index := 0; index < layerLength36; index++ {
					var element tg.MessageEntityClass
					layerClass38, err := layerDecodeClassMessageEntity(profile, b, &layerDecodeState35)
					if err != nil {
						return nil, fmt.Errorf("decode field entities element: %w", err)
					}
					element = layerClass38
					layerVector37 = append(layerVector37, element)
				}
				layerDecoded34 = layerVector37
			}
			var layerDecoded39 tg.InputMediaClass
			if wireFlags0.Has(5) {
				layerClass40, err := layerDecodeClassInputMedia(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field media: %w", err)
				}
				layerDecoded39 = layerClass40
			}
			var layerDecoded41 int
			layerPrimitive42, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field date: %w", err)
			}
			layerDecoded41 = layerPrimitive42
			var layerDecoded43 int64
			if wireFlags0.Has(7) {
				layerPrimitive44, err := b.Long()
				if err != nil {
					return nil, fmt.Errorf("decode field effect: %w", err)
				}
				layerDecoded43 = layerPrimitive44
			}
			var layerDecoded45 tg.SuggestedPost
			if wireFlags0.Has(8) {
				layerConcrete46, err := layerDecodeWire0e8e37e5(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field suggested_post: %w", err)
				}
				layerDecoded45 = *layerConcrete46
			}
			var layerDecoded47 tg.RichMessage
			if wireFlags0.Has(9) {
				layerConcrete48, err := layerDecodeWirebaf39d8b(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field rich_message: %w", err)
				}
				layerDecoded47 = *layerConcrete48
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.NoWebpage = layerDecoded28
			}
			if wireFlags0.Has(6) {
				value.Flags.Set(6)
				value.InvertMedia = layerDecoded29
			}
			if wireFlags0.Has(4) {
				value.Flags.Set(4)
				value.ReplyTo = layerDecoded30
			}
			if true {
				value.Message = layerDecoded32
			}
			if wireFlags0.Has(3) {
				value.Flags.Set(3)
				value.Entities = layerDecoded34
			}
			if wireFlags0.Has(5) {
				value.Flags.Set(5)
				value.Media = layerDecoded39
			}
			if true {
				value.Date = layerDecoded41
			}
			if wireFlags0.Has(7) {
				value.Flags.Set(7)
				value.Effect = layerDecoded43
			}
			if wireFlags0.Has(8) {
				value.Flags.Set(8)
				value.SuggestedPost = layerDecoded45
			}
			if wireFlags0.Has(9) {
				value.Flags.Set(9)
				value.RichMessage = layerDecoded47
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeDraftMessage, WireID: 0x60fe3294, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire65efe954BareBody(profile LayerProfile, value *tg.Community, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile228, LayerProfile229:
		{
			layerEncoded4 := &bin.Buffer{}
			layerPresent6 := (value.Flags.Has(14) || !value.AdminRights.Zero())
			if layerPresent6 {
				layerErr5 := func() error {
					layerEncoded4.PutID(0x5fb224d5)
					if err := layerEncodeWire5fb224d5BareBody(profile, &(value.AdminRights), layerEncoded4, state); err != nil {
						return fmt.Errorf("encode prepared field admin_rights: %w", err)
					}
					return nil
				}()
				if layerErr5 != nil {
					if IsLayerProjectionDrop(layerErr5) {
						layerPresent6 = false
						layerEncoded4.Reset()
					} else {
						return fmt.Errorf("encode optional field admin_rights: %w", layerErr5)
					}
				}
			}
			layerEncoded7 := &bin.Buffer{}
			layerPresent9 := (value.Flags.Has(18) || !value.DefaultBannedRights.Zero())
			if layerPresent9 {
				layerErr8 := func() error {
					layerEncoded7.PutID(0x9f120418)
					if err := layerEncodeWire9f120418BareBody(profile, &(value.DefaultBannedRights), layerEncoded7, state); err != nil {
						return fmt.Errorf("encode prepared field default_banned_rights: %w", err)
					}
					return nil
				}()
				if layerErr8 != nil {
					if IsLayerProjectionDrop(layerErr8) {
						layerPresent9 = false
						layerEncoded7.Reset()
					} else {
						return fmt.Errorf("encode optional field default_banned_rights: %w", layerErr8)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.Creator {
				wireFlags0.Set(0)
			}
			if value.Flags.Has(2) || value.Left {
				wireFlags0.Set(2)
			}
			if value.Flags.Has(12) || value.Min {
				wireFlags0.Set(12)
			}
			if value.Flags.Has(13) || value.AccessHash != 0 {
				wireFlags0.Set(13)
			}
			if layerPresent6 {
				wireFlags0.Set(14)
			}
			if layerPresent9 {
				wireFlags0.Set(18)
			}
			var wireFlags4 bin.Fields
			if value.Flags2.Has(20) || value.CollapsedInDialogs {
				wireFlags4.Set(20)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if err := wireFlags4.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags2: %w", err)
			}
			b.PutLong(value.ID)
			if wireFlags0.Has(13) {
				b.PutLong(value.AccessHash)
			}
			if err := b.PutStringChecked(value.Title); err != nil {
				return fmt.Errorf("encode field title: %w", err)
			}
			if err := layerEncodeClassChatPhotoBody(profile, value.Photo, b, state); err != nil {
				return fmt.Errorf("encode field photo: %w", err)
			}
			b.PutInt(value.Date)
			if wireFlags0.Has(14) {
				b.Buf = append(b.Buf, layerEncoded4.Buf...)
			}
			if wireFlags0.Has(18) {
				b.Buf = append(b.Buf, layerEncoded7.Buf...)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeCommunity, WireID: 0x65efe954, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire65efe954(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.Community, error) {
	switch profile {
	case LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeCommunity, WireID: 0x65efe954, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x65efe954); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x65efe954: %w", err)
	}
	return layerDecodeWire65efe954Bare(profile, b, state)

}

func layerDecodeWire65efe954Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.Community, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.Community)
	_ = value
	switch profile {
	case LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded10 := wireFlags0.Has(0)
			layerDecoded11 := wireFlags0.Has(2)
			layerDecoded12 := wireFlags0.Has(12)
			var wireFlags4 bin.Fields
			if err := wireFlags4.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags2: %w", err)
			}
			layerDecoded13 := wireFlags4.Has(20)
			var layerDecoded14 int64
			layerPrimitive15, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field id: %w", err)
			}
			layerDecoded14 = layerPrimitive15
			var layerDecoded16 int64
			if wireFlags0.Has(13) {
				layerPrimitive17, err := b.Long()
				if err != nil {
					return nil, fmt.Errorf("decode field access_hash: %w", err)
				}
				layerDecoded16 = layerPrimitive17
			}
			var layerDecoded18 string
			layerPrimitive19, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field title: %w", err)
			}
			layerDecoded18 = layerPrimitive19
			var layerDecoded20 tg.ChatPhotoClass
			layerClass21, err := layerDecodeClassChatPhoto(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field photo: %w", err)
			}
			layerDecoded20 = layerClass21
			var layerDecoded22 int
			layerPrimitive23, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field date: %w", err)
			}
			layerDecoded22 = layerPrimitive23
			var layerDecoded24 tg.ChatAdminRights
			if wireFlags0.Has(14) {
				layerConcrete25, err := layerDecodeWire5fb224d5(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field admin_rights: %w", err)
				}
				layerDecoded24 = *layerConcrete25
			}
			var layerDecoded26 tg.ChatBannedRights
			if wireFlags0.Has(18) {
				layerConcrete27, err := layerDecodeWire9f120418(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field default_banned_rights: %w", err)
				}
				layerDecoded26 = *layerConcrete27
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Creator = layerDecoded10
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.Left = layerDecoded11
			}
			if wireFlags0.Has(12) {
				value.Flags.Set(12)
				value.Min = layerDecoded12
			}
			if wireFlags4.Has(20) {
				value.Flags2.Set(20)
				value.CollapsedInDialogs = layerDecoded13
			}
			if true {
				value.ID = layerDecoded14
			}
			if wireFlags0.Has(13) {
				value.Flags.Set(13)
				value.AccessHash = layerDecoded16
			}
			if true {
				value.Title = layerDecoded18
			}
			if true {
				value.Photo = layerDecoded20
			}
			if true {
				value.Date = layerDecoded22
			}
			if wireFlags0.Has(14) {
				value.Flags.Set(14)
				value.AdminRights = layerDecoded24
			}
			if wireFlags0.Has(18) {
				value.Flags.Set(18)
				value.DefaultBannedRights = layerDecoded26
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeCommunity, WireID: 0x65efe954, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire7699f014Bare(profile LayerProfile, value *tg.UpdateMessagePollVote, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateMessagePollVote, WireID: 0x7699f014, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire7699f014BareBody(profile LayerProfile, value *tg.UpdateMessagePollVote, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire7699f014Bare(profile, value, b, state)
}
func layerDecodeWire7699f014(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateMessagePollVote, error) {
	value := new(tg.UpdateMessagePollVote)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire774278d4Bare(profile LayerProfile, value *tg.MessageActionStarGiftPurchaseOffer, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionStarGiftPurchaseOffer, WireID: 0x774278d4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire774278d4BareBody(profile LayerProfile, value *tg.MessageActionStarGiftPurchaseOffer, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire774278d4Bare(profile, value, b, state)
}
func layerDecodeWire774278d4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionStarGiftPurchaseOffer, error) {
	value := new(tg.MessageActionStarGiftPurchaseOffer)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire7998c914BareBody(profile LayerProfile, value *tg.PaymentsSendStarsFormRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			b.PutLong(value.FormID)
			if err := layerEncodeClassInputInvoiceBody(profile, value.Invoice, b, state); err != nil {
				return fmt.Errorf("encode field invoice: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodPaymentsSendStarsForm, WireID: 0x7998c914, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire7998c914(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentsSendStarsFormRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodPaymentsSendStarsForm, WireID: 0x7998c914, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x7998c914); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x7998c914: %w", err)
	}
	return layerDecodeWire7998c914Bare(profile, b, state)

}

func layerDecodeWire7998c914Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentsSendStarsFormRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PaymentsSendStarsFormRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 int64
			layerPrimitive3, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field form_id: %w", err)
			}
			layerDecoded2 = layerPrimitive3
			var layerDecoded4 tg.InputInvoiceClass
			layerClass5, err := layerDecodeClassInputInvoice(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field invoice: %w", err)
			}
			layerDecoded4 = layerClass5
			if true {
				value.FormID = layerDecoded2
			}
			if true {
				value.Invoice = layerDecoded4
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodPaymentsSendStarsForm, WireID: 0x7998c914, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire7fe91c14Bare(profile LayerProfile, value *tg.StatsMessageStats, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStatsMessageStats, WireID: 0x7fe91c14, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire7fe91c14BareBody(profile LayerProfile, value *tg.StatsMessageStats, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire7fe91c14Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire8a53b014Bare(profile LayerProfile, value *tg.MessageMediaToDo, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageMediaToDo, WireID: 0x8a53b014, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire8a53b014BareBody(profile LayerProfile, value *tg.MessageMediaToDo, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire8a53b014Bare(profile, value, b, state)
}
func layerDecodeWire8a53b014(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageMediaToDo, error) {
	value := new(tg.MessageMediaToDo)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire909c3f94Bare(profile LayerProfile, value *tg.PaymentRequestedInfo, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePaymentRequestedInfo, WireID: 0x909c3f94, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire909c3f94BareBody(profile LayerProfile, value *tg.PaymentRequestedInfo, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire909c3f94Bare(profile, value, b, state)
}
func layerDecodeWire909c3f94(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentRequestedInfo, error) {
	value := new(tg.PaymentRequestedInfo)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire9bad6414Bare(profile LayerProfile, value *tg.AiComposeToneDefault, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAiComposeToneDefault, WireID: 0x9bad6414, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9bad6414BareBody(profile LayerProfile, value *tg.AiComposeToneDefault, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9bad6414Bare(profile, value, b, state)
}
func layerDecodeWire9bad6414(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AiComposeToneDefault, error) {
	value := new(tg.AiComposeToneDefault)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirebf0693d4Bare(profile LayerProfile, value *tg.MessageEntityStrike, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageEntityStrike, WireID: 0xbf0693d4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirebf0693d4BareBody(profile LayerProfile, value *tg.MessageEntityStrike, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirebf0693d4Bare(profile, value, b, state)
}
func layerDecodeWirebf0693d4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageEntityStrike, error) {
	value := new(tg.MessageEntityStrike)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWired1b4ab14BareBody(profile LayerProfile, value *tg.AicomposeGetToneExampleRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassInputAiComposeToneBody(profile, value.Tone, b, state); err != nil {
				return fmt.Errorf("encode field tone: %w", err)
			}
			b.PutInt(value.Num)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodAicomposeGetToneExample, WireID: 0xd1b4ab14, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWired1b4ab14(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AicomposeGetToneExampleRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodAicomposeGetToneExample, WireID: 0xd1b4ab14, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xd1b4ab14); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xd1b4ab14: %w", err)
	}
	return layerDecodeWired1b4ab14Bare(profile, b, state)

}

func layerDecodeWired1b4ab14Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AicomposeGetToneExampleRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.AicomposeGetToneExampleRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.InputAiComposeToneClass
			layerClass3, err := layerDecodeClassInputAiComposeTone(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field tone: %w", err)
			}
			layerDecoded2 = layerClass3
			var layerDecoded4 int
			layerPrimitive5, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field num: %w", err)
			}
			layerDecoded4 = layerPrimitive5
			if true {
				value.Tone = layerDecoded2
			}
			if true {
				value.Num = layerDecoded4
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodAicomposeGetToneExample, WireID: 0xd1b4ab14, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWired95c6154Bare(profile LayerProfile, value *tg.MessageActionSecureValuesSent, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionSecureValuesSent, WireID: 0xd95c6154, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWired95c6154BareBody(profile LayerProfile, value *tg.MessageActionSecureValuesSent, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWired95c6154Bare(profile, value, b, state)
}
func layerDecodeWired95c6154(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionSecureValuesSent, error) {
	value := new(tg.MessageActionSecureValuesSent)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWiree1664194BareBody(profile LayerProfile, value *tg.ContactsBlockedSlice, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			b.PutInt(value.Count)
			if len(value.Blocked) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart9 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset10 := layerVectorStart9 + 4
			layerLength7 := 0
			for layerIndex8 := range value.Blocked {
				layerItemStart11 := len(b.Buf)
				layerErr12 := func() error {
					b.PutID(0xe8fd8014)
					if err := layerEncodeWiree8fd8014BareBody(profile, &(value.Blocked[layerIndex8]), b, state); err != nil {
						return fmt.Errorf("encode field blocked element: %w", err)
					}
					return nil
				}()
				if layerErr12 != nil {
					b.Buf = b.Buf[:layerItemStart11]
					if IsLayerProjectionDrop(layerErr12) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart9]
					return fmt.Errorf("encode field blocked: %w", layerErr12)
				}
				layerLength7++
			}
			b.Buf[layerCountOffset10] = byte(layerLength7)
			b.Buf[layerCountOffset10+1] = byte(layerLength7 >> 8)
			b.Buf[layerCountOffset10+2] = byte(layerLength7 >> 16)
			b.Buf[layerCountOffset10+3] = byte(layerLength7 >> 24)
			if len(value.Chats) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart15 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset16 := layerVectorStart15 + 4
			layerLength13 := 0
			for layerIndex14 := range value.Chats {
				layerItemStart17 := len(b.Buf)
				layerErr18 := func() error {
					if err := layerEncodeClassChatBody(profile, value.Chats[layerIndex14], b, state); err != nil {
						return fmt.Errorf("encode field chats element: %w", err)
					}
					return nil
				}()
				if layerErr18 != nil {
					b.Buf = b.Buf[:layerItemStart17]
					if IsLayerProjectionDrop(layerErr18) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart15]
					return fmt.Errorf("encode field chats: %w", layerErr18)
				}
				layerLength13++
			}
			b.Buf[layerCountOffset16] = byte(layerLength13)
			b.Buf[layerCountOffset16+1] = byte(layerLength13 >> 8)
			b.Buf[layerCountOffset16+2] = byte(layerLength13 >> 16)
			b.Buf[layerCountOffset16+3] = byte(layerLength13 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart21 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset22 := layerVectorStart21 + 4
			layerLength19 := 0
			for layerIndex20 := range value.Users {
				layerItemStart23 := len(b.Buf)
				layerErr24 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex20], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr24 != nil {
					b.Buf = b.Buf[:layerItemStart23]
					if IsLayerProjectionDrop(layerErr24) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart21]
					return fmt.Errorf("encode field users: %w", layerErr24)
				}
				layerLength19++
			}
			b.Buf[layerCountOffset22] = byte(layerLength19)
			b.Buf[layerCountOffset22+1] = byte(layerLength19 >> 8)
			b.Buf[layerCountOffset22+2] = byte(layerLength19 >> 16)
			b.Buf[layerCountOffset22+3] = byte(layerLength19 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeContactsBlockedSlice, WireID: 0xe1664194, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWiree1664194(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ContactsBlockedSlice, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeContactsBlockedSlice, WireID: 0xe1664194, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xe1664194); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xe1664194: %w", err)
	}
	return layerDecodeWiree1664194Bare(profile, b, state)

}

func layerDecodeWiree1664194Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ContactsBlockedSlice, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.ContactsBlockedSlice)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded25 int
			layerPrimitive26, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field count: %w", err)
			}
			layerDecoded25 = layerPrimitive26
			var layerDecoded27 []tg.PeerBlocked
			layerDecodeState28, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field blocked vector depth: %w", err)
			}
			layerLength29, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState28)
			if err != nil {
				return nil, fmt.Errorf("decode field blocked: %w", err)
			}
			var layerVector30 []tg.PeerBlocked
			if layerLength29 > 0 {
				capacity := layerLength29
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector30 = make([]tg.PeerBlocked, 0, capacity)
			}
			for index := 0; index < layerLength29; index++ {
				var element tg.PeerBlocked
				layerConcrete31, err := layerDecodeWiree8fd8014(profile, b, &layerDecodeState28)
				if err != nil {
					return nil, fmt.Errorf("decode field blocked element: %w", err)
				}
				element = *layerConcrete31
				layerVector30 = append(layerVector30, element)
			}
			layerDecoded27 = layerVector30
			var layerDecoded32 []tg.ChatClass
			layerDecodeState33, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field chats vector depth: %w", err)
			}
			layerLength34, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState33)
			if err != nil {
				return nil, fmt.Errorf("decode field chats: %w", err)
			}
			var layerVector35 []tg.ChatClass
			if layerLength34 > 0 {
				capacity := layerLength34
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector35 = make([]tg.ChatClass, 0, capacity)
			}
			for index := 0; index < layerLength34; index++ {
				var element tg.ChatClass
				layerClass36, err := layerDecodeClassChat(profile, b, &layerDecodeState33)
				if err != nil {
					return nil, fmt.Errorf("decode field chats element: %w", err)
				}
				element = layerClass36
				layerVector35 = append(layerVector35, element)
			}
			layerDecoded32 = layerVector35
			var layerDecoded37 []tg.UserClass
			layerDecodeState38, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength39, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState38)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector40 []tg.UserClass
			if layerLength39 > 0 {
				capacity := layerLength39
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector40 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength39; index++ {
				var element tg.UserClass
				layerClass41, err := layerDecodeClassUser(profile, b, &layerDecodeState38)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass41
				layerVector40 = append(layerVector40, element)
			}
			layerDecoded37 = layerVector40
			if true {
				value.Count = layerDecoded25
			}
			if true {
				value.Blocked = layerDecoded27
			}
			if true {
				value.Chats = layerDecoded32
			}
			if true {
				value.Users = layerDecoded37
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeContactsBlockedSlice, WireID: 0xe1664194, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree8fd8014Bare(profile LayerProfile, value *tg.PeerBlocked, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePeerBlocked, WireID: 0xe8fd8014, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree8fd8014BareBody(profile LayerProfile, value *tg.PeerBlocked, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree8fd8014Bare(profile, value, b, state)
}
func layerDecodeWiree8fd8014(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PeerBlocked, error) {
	value := new(tg.PeerBlocked)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiref16269d4Bare(profile LayerProfile, value *tg.UpdateSMSJob, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSMSJob, WireID: 0xf16269d4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiref16269d4BareBody(profile LayerProfile, value *tg.UpdateSMSJob, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiref16269d4Bare(profile, value, b, state)
}
func layerDecodeWiref16269d4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateSMSJob, error) {
	value := new(tg.UpdateSMSJob)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
