// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire023f109b(profile LayerProfile, value *tg.ForumTopicDeleted, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeForumTopicDeleted, WireID: 0x023f109b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire023f109bBare(profile LayerProfile, value *tg.ForumTopicDeleted, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeForumTopicDeleted, WireID: 0x023f109b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire023f109bBareBody(profile LayerProfile, value *tg.ForumTopicDeleted, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire023f109bBare(profile, value, b, state)
}

func layerDecodeWire023f109b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ForumTopicDeleted, error) {
	value := new(tg.ForumTopicDeleted)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire023f109bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ForumTopicDeleted, error) {
	value := new(tg.ForumTopicDeleted)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire052b08db(profile LayerProfile, value *tg.MessagesSetBotGuestChatResultRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSetBotGuestChatResult, WireID: 0x052b08db, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSetBotGuestChatResult, WireID: 0x052b08db, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0x052b08db)
		return layerEncodeWire052b08dbBareBody(profile, value, b, state)

	})
}

func layerEncodeWire052b08dbBare(profile LayerProfile, value *tg.MessagesSetBotGuestChatResultRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSetBotGuestChatResult, WireID: 0x052b08db, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire052b08dbBareBody(profile, value, b, state)
	})
}

func layerEncodeWire052b08dbBareBody(profile LayerProfile, value *tg.MessagesSetBotGuestChatResultRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225:
		{
			b.PutLong(value.QueryID)
			if err := layerEncodeClassInputBotInlineResultBody(profile, value.Result, b, state); err != nil {
				return fmt.Errorf("encode field result: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSetBotGuestChatResult, WireID: 0x052b08db, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire052b08db(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSetBotGuestChatResultRequest, error) {
	switch profile {
	case LayerProfile225:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodMessagesSetBotGuestChatResult, WireID: 0x052b08db, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x052b08db); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x052b08db: %w", err)
	}
	return layerDecodeWire052b08dbBare(profile, b, state)

}

func layerDecodeWire052b08dbBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSetBotGuestChatResultRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesSetBotGuestChatResultRequest)
	_ = value
	switch profile {
	case LayerProfile225:
		{
			var layerDecoded2 int64
			layerPrimitive3, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field query_id: %w", err)
			}
			layerDecoded2 = layerPrimitive3
			var layerDecoded4 tg.InputBotInlineResultClass
			layerClass5, err := layerDecodeClassInputBotInlineResult(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field result: %w", err)
			}
			layerDecoded4 = layerClass5
			if true {
				value.QueryID = layerDecoded2
			}
			if true {
				value.Result = layerDecoded4
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSetBotGuestChatResult, WireID: 0x052b08db, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire209b82db(profile LayerProfile, value *tg.ChannelLocation, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChannelLocation, WireID: 0x209b82db, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire209b82dbBare(profile LayerProfile, value *tg.ChannelLocation, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChannelLocation, WireID: 0x209b82db, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire209b82dbBareBody(profile LayerProfile, value *tg.ChannelLocation, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire209b82dbBare(profile, value, b, state)
}

func layerDecodeWire209b82db(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChannelLocation, error) {
	value := new(tg.ChannelLocation)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire209b82dbBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChannelLocation, error) {
	value := new(tg.ChannelLocation)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire2633421b(profile LayerProfile, value *tg.ChatFull, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, WireID: 0x2633421b, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, WireID: 0x2633421b, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0x2633421b)
		return layerEncodeWire2633421bBareBody(profile, value, b, state)

	})
}

func layerEncodeWire2633421bBare(profile LayerProfile, value *tg.ChatFull, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChatFull, WireID: 0x2633421b, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire2633421bBareBody(profile, value, b, state)
	})
}

func layerEncodeWire2633421bBareBody(profile LayerProfile, value *tg.ChatFull, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			if value.Flags.Has(2) && value.ChatPhoto == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, Reason: "malformed canonical value: explicit flag has nil interface field chat_photo"}
			}
			if value.Flags.Has(13) && value.ExportedInvite == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, Reason: "malformed canonical value: explicit flag has nil interface field exported_invite"}
			}
			if value.Flags.Has(12) && value.Call == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, Reason: "malformed canonical value: explicit flag has nil interface field call"}
			}
			if value.Flags.Has(15) && value.GroupcallDefaultJoinAs == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, Reason: "malformed canonical value: explicit flag has nil interface field groupcall_default_join_as"}
			}
			if value.Flags.Has(18) && value.AvailableReactions == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, Reason: "malformed canonical value: explicit flag has nil interface field available_reactions"}
			}
			layerEncoded11 := &bin.Buffer{}
			layerPresent13 := (value.Flags.Has(2) || value.ChatPhoto != nil)
			if layerPresent13 {
				layerErr12 := func() error {
					if err := layerEncodeClassPhotoBody(profile, value.ChatPhoto, layerEncoded11, state); err != nil {
						return fmt.Errorf("encode prepared field chat_photo: %w", err)
					}
					return nil
				}()
				if layerErr12 != nil {
					if IsLayerProjectionDrop(layerErr12) {
						layerPresent13 = false
						layerEncoded11.Reset()
					} else {
						return fmt.Errorf("encode optional field chat_photo: %w", layerErr12)
					}
				}
			}
			layerEncoded14 := &bin.Buffer{}
			layerPresent16 := (value.Flags.Has(13) || value.ExportedInvite != nil)
			if layerPresent16 {
				layerErr15 := func() error {
					if err := layerEncodeClassExportedChatInviteBody(profile, value.ExportedInvite, layerEncoded14, state); err != nil {
						return fmt.Errorf("encode prepared field exported_invite: %w", err)
					}
					return nil
				}()
				if layerErr15 != nil {
					if IsLayerProjectionDrop(layerErr15) {
						layerPresent16 = false
						layerEncoded14.Reset()
					} else {
						return fmt.Errorf("encode optional field exported_invite: %w", layerErr15)
					}
				}
			}
			layerEncoded17 := &bin.Buffer{}
			layerPresent25 := (value.Flags.Has(3) || value.BotInfo != nil)
			if layerPresent25 {
				layerErr18 := func() error {
					if len(value.BotInfo) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerVectorStart21 := len(layerEncoded17.Buf)
					layerEncoded17.PutVectorHeader(0)
					layerCountOffset22 := layerVectorStart21 + 4
					layerLength19 := 0
					for layerIndex20 := range value.BotInfo {
						layerItemStart23 := len(layerEncoded17.Buf)
						layerErr24 := func() error {
							layerEncoded17.PutID(0x4d8a0299)
							if err := layerEncodeWire4d8a0299BareBody(profile, &(value.BotInfo[layerIndex20]), layerEncoded17, state); err != nil {
								return fmt.Errorf("encode prepared field bot_info element: %w", err)
							}
							return nil
						}()
						if layerErr24 != nil {
							layerEncoded17.Buf = layerEncoded17.Buf[:layerItemStart23]
							if IsLayerProjectionDrop(layerErr24) {
								continue
							}
							layerEncoded17.Buf = layerEncoded17.Buf[:layerVectorStart21]
							return fmt.Errorf("encode prepared field bot_info: %w", layerErr24)
						}
						layerLength19++
					}
					layerEncoded17.Buf[layerCountOffset22] = byte(layerLength19)
					layerEncoded17.Buf[layerCountOffset22+1] = byte(layerLength19 >> 8)
					layerEncoded17.Buf[layerCountOffset22+2] = byte(layerLength19 >> 16)
					layerEncoded17.Buf[layerCountOffset22+3] = byte(layerLength19 >> 24)
					return nil
				}()
				if layerErr18 != nil {
					if IsLayerProjectionDrop(layerErr18) {
						layerPresent25 = false
						layerEncoded17.Reset()
					} else {
						return fmt.Errorf("encode optional field bot_info: %w", layerErr18)
					}
				}
			}
			layerEncoded26 := &bin.Buffer{}
			layerPresent28 := (value.Flags.Has(12) || value.Call != nil)
			if layerPresent28 {
				layerErr27 := func() error {
					if err := layerEncodeClassInputGroupCallBody(profile, value.Call, layerEncoded26, state); err != nil {
						return fmt.Errorf("encode prepared field call: %w", err)
					}
					return nil
				}()
				if layerErr27 != nil {
					if IsLayerProjectionDrop(layerErr27) {
						layerPresent28 = false
						layerEncoded26.Reset()
					} else {
						return fmt.Errorf("encode optional field call: %w", layerErr27)
					}
				}
			}
			layerEncoded29 := &bin.Buffer{}
			layerPresent31 := (value.Flags.Has(15) || value.GroupcallDefaultJoinAs != nil)
			if layerPresent31 {
				layerErr30 := func() error {
					if err := layerEncodeClassPeerBody(profile, value.GroupcallDefaultJoinAs, layerEncoded29, state); err != nil {
						return fmt.Errorf("encode prepared field groupcall_default_join_as: %w", err)
					}
					return nil
				}()
				if layerErr30 != nil {
					if IsLayerProjectionDrop(layerErr30) {
						layerPresent31 = false
						layerEncoded29.Reset()
					} else {
						return fmt.Errorf("encode optional field groupcall_default_join_as: %w", layerErr30)
					}
				}
			}
			layerEncoded32 := &bin.Buffer{}
			layerPresent36 := (value.Flags.Has(17) || value.RequestsPending != 0) || (value.Flags.Has(17) || value.RecentRequesters != nil)
			if layerPresent36 {
				layerErr33 := func() error {
					if len(value.RecentRequesters) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerEncoded32.PutVectorHeader(len(value.RecentRequesters))
					for layerIndex35 := range value.RecentRequesters {
						layerEncoded32.PutLong(value.RecentRequesters[layerIndex35])
					}
					return nil
				}()
				if layerErr33 != nil {
					if IsLayerProjectionDrop(layerErr33) {
						layerPresent36 = false
						layerEncoded32.Reset()
					} else {
						return fmt.Errorf("encode optional field recent_requesters: %w", layerErr33)
					}
				}
			}
			layerEncoded37 := &bin.Buffer{}
			layerPresent39 := (value.Flags.Has(18) || value.AvailableReactions != nil)
			if layerPresent39 {
				layerErr38 := func() error {
					if err := layerEncodeClassChatReactionsBody(profile, value.AvailableReactions, layerEncoded37, state); err != nil {
						return fmt.Errorf("encode prepared field available_reactions: %w", err)
					}
					return nil
				}()
				if layerErr38 != nil {
					if IsLayerProjectionDrop(layerErr38) {
						layerPresent39 = false
						layerEncoded37.Reset()
					} else {
						return fmt.Errorf("encode optional field available_reactions: %w", layerErr38)
					}
				}
			}
			var wireFlags0 bin.Fields
			if layerPresent13 {
				wireFlags0.Set(2)
			}
			if layerPresent25 {
				wireFlags0.Set(3)
			}
			if value.Flags.Has(6) || value.PinnedMsgID != 0 {
				wireFlags0.Set(6)
			}
			if value.Flags.Has(7) || value.CanSetUsername {
				wireFlags0.Set(7)
			}
			if value.Flags.Has(8) || value.HasScheduled {
				wireFlags0.Set(8)
			}
			if value.Flags.Has(11) || value.FolderID != 0 {
				wireFlags0.Set(11)
			}
			if layerPresent28 {
				wireFlags0.Set(12)
			}
			if layerPresent16 {
				wireFlags0.Set(13)
			}
			if value.Flags.Has(14) || value.TTLPeriod != 0 {
				wireFlags0.Set(14)
			}
			if layerPresent31 {
				wireFlags0.Set(15)
			}
			if value.Flags.Has(16) || value.ThemeEmoticon != "" {
				wireFlags0.Set(16)
			}
			if ((value.Flags.Has(17) || value.RequestsPending != 0) || layerPresent36) && !layerPresent36 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeChatFull, Reason: "shared flag group flags.17 projected only partially"}
			}
			if (value.Flags.Has(17) || value.RequestsPending != 0) || layerPresent36 {
				wireFlags0.Set(17)
			}
			if layerPresent39 {
				wireFlags0.Set(18)
			}
			if value.Flags.Has(19) || value.TranslationsDisabled {
				wireFlags0.Set(19)
			}
			if value.Flags.Has(20) || value.ReactionsLimit != 0 {
				wireFlags0.Set(20)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			b.PutLong(value.ID)
			if err := b.PutStringChecked(value.About); err != nil {
				return fmt.Errorf("encode field about: %w", err)
			}
			if err := layerEncodeClassChatParticipantsBody(profile, value.Participants, b, state); err != nil {
				return fmt.Errorf("encode field participants: %w", err)
			}
			if wireFlags0.Has(2) {
				b.Buf = append(b.Buf, layerEncoded11.Buf...)
			}
			b.PutID(0x99622c0c)
			if err := layerEncodeWire99622c0cBareBody(profile, &(value.NotifySettings), b, state); err != nil {
				return fmt.Errorf("encode field notify_settings: %w", err)
			}
			if wireFlags0.Has(13) {
				b.Buf = append(b.Buf, layerEncoded14.Buf...)
			}
			if wireFlags0.Has(3) {
				b.Buf = append(b.Buf, layerEncoded17.Buf...)
			}
			if wireFlags0.Has(6) {
				b.PutInt(value.PinnedMsgID)
			}
			if wireFlags0.Has(11) {
				b.PutInt(value.FolderID)
			}
			if wireFlags0.Has(12) {
				b.Buf = append(b.Buf, layerEncoded26.Buf...)
			}
			if wireFlags0.Has(14) {
				b.PutInt(value.TTLPeriod)
			}
			if wireFlags0.Has(15) {
				b.Buf = append(b.Buf, layerEncoded29.Buf...)
			}
			if wireFlags0.Has(16) {
				if err := b.PutStringChecked(value.ThemeEmoticon); err != nil {
					return fmt.Errorf("encode field theme_emoticon: %w", err)
				}
			}
			if wireFlags0.Has(17) {
				b.PutInt(value.RequestsPending)
			}
			if wireFlags0.Has(17) {
				b.Buf = append(b.Buf, layerEncoded32.Buf...)
			}
			if wireFlags0.Has(18) {
				b.Buf = append(b.Buf, layerEncoded37.Buf...)
			}
			if wireFlags0.Has(20) {
				b.PutInt(value.ReactionsLimit)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChatFull, WireID: 0x2633421b, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire2633421b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChatFull, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeChatFull, WireID: 0x2633421b, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x2633421b); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x2633421b: %w", err)
	}
	return layerDecodeWire2633421bBare(profile, b, state)

}

func layerDecodeWire2633421bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChatFull, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.ChatFull)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded40 := wireFlags0.Has(7)
			layerDecoded41 := wireFlags0.Has(8)
			layerDecoded42 := wireFlags0.Has(19)
			var layerDecoded43 int64
			layerPrimitive44, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field id: %w", err)
			}
			layerDecoded43 = layerPrimitive44
			var layerDecoded45 string
			layerPrimitive46, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field about: %w", err)
			}
			layerDecoded45 = layerPrimitive46
			var layerDecoded47 tg.ChatParticipantsClass
			layerClass48, err := layerDecodeClassChatParticipants(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field participants: %w", err)
			}
			layerDecoded47 = layerClass48
			var layerDecoded49 tg.PhotoClass
			if wireFlags0.Has(2) {
				layerClass50, err := layerDecodeClassPhoto(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field chat_photo: %w", err)
				}
				layerDecoded49 = layerClass50
			}
			var layerDecoded51 tg.PeerNotifySettings
			layerConcrete52, err := layerDecodeWire99622c0c(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field notify_settings: %w", err)
			}
			layerDecoded51 = *layerConcrete52
			var layerDecoded53 tg.ExportedChatInviteClass
			if wireFlags0.Has(13) {
				layerClass54, err := layerDecodeClassExportedChatInvite(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field exported_invite: %w", err)
				}
				layerDecoded53 = layerClass54
			}
			var layerDecoded55 []tg.BotInfo
			if wireFlags0.Has(3) {
				layerDecodeState56, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field bot_info vector depth: %w", err)
				}
				layerLength57, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState56)
				if err != nil {
					return nil, fmt.Errorf("decode field bot_info: %w", err)
				}
				var layerVector58 []tg.BotInfo
				if layerLength57 > 0 {
					capacity := layerLength57
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector58 = make([]tg.BotInfo, 0, capacity)
				}
				for index := 0; index < layerLength57; index++ {
					var element tg.BotInfo
					layerConcrete59, err := layerDecodeWire4d8a0299(profile, b, &layerDecodeState56)
					if err != nil {
						return nil, fmt.Errorf("decode field bot_info element: %w", err)
					}
					element = *layerConcrete59
					layerVector58 = append(layerVector58, element)
				}
				layerDecoded55 = layerVector58
			}
			var layerDecoded60 int
			if wireFlags0.Has(6) {
				layerPrimitive61, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field pinned_msg_id: %w", err)
				}
				layerDecoded60 = layerPrimitive61
			}
			var layerDecoded62 int
			if wireFlags0.Has(11) {
				layerPrimitive63, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field folder_id: %w", err)
				}
				layerDecoded62 = layerPrimitive63
			}
			var layerDecoded64 tg.InputGroupCallClass
			if wireFlags0.Has(12) {
				layerClass65, err := layerDecodeClassInputGroupCall(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field call: %w", err)
				}
				layerDecoded64 = layerClass65
			}
			var layerDecoded66 int
			if wireFlags0.Has(14) {
				layerPrimitive67, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field ttl_period: %w", err)
				}
				layerDecoded66 = layerPrimitive67
			}
			var layerDecoded68 tg.PeerClass
			if wireFlags0.Has(15) {
				layerClass69, err := layerDecodeClassPeer(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field groupcall_default_join_as: %w", err)
				}
				layerDecoded68 = layerClass69
			}
			var layerDecoded70 string
			if wireFlags0.Has(16) {
				layerPrimitive71, err := b.String()
				if err != nil {
					return nil, fmt.Errorf("decode field theme_emoticon: %w", err)
				}
				layerDecoded70 = layerPrimitive71
			}
			var layerDecoded72 int
			if wireFlags0.Has(17) {
				layerPrimitive73, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field requests_pending: %w", err)
				}
				layerDecoded72 = layerPrimitive73
			}
			var layerDecoded74 []int64
			if wireFlags0.Has(17) {
				layerDecodeState75, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field recent_requesters vector depth: %w", err)
				}
				layerLength76, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState75)
				if err != nil {
					return nil, fmt.Errorf("decode field recent_requesters: %w", err)
				}
				var layerVector77 []int64
				if layerLength76 > 0 {
					capacity := layerLength76
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector77 = make([]int64, 0, capacity)
				}
				for index := 0; index < layerLength76; index++ {
					var element int64
					layerPrimitive78, err := b.Long()
					if err != nil {
						return nil, fmt.Errorf("decode field recent_requesters element: %w", err)
					}
					element = layerPrimitive78
					layerVector77 = append(layerVector77, element)
				}
				layerDecoded74 = layerVector77
			}
			var layerDecoded79 tg.ChatReactionsClass
			if wireFlags0.Has(18) {
				layerClass80, err := layerDecodeClassChatReactions(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field available_reactions: %w", err)
				}
				layerDecoded79 = layerClass80
			}
			var layerDecoded81 int
			if wireFlags0.Has(20) {
				layerPrimitive82, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field reactions_limit: %w", err)
				}
				layerDecoded81 = layerPrimitive82
			}
			if wireFlags0.Has(7) {
				value.Flags.Set(7)
				value.CanSetUsername = layerDecoded40
			}
			if wireFlags0.Has(8) {
				value.Flags.Set(8)
				value.HasScheduled = layerDecoded41
			}
			if wireFlags0.Has(19) {
				value.Flags.Set(19)
				value.TranslationsDisabled = layerDecoded42
			}
			if true {
				value.ID = layerDecoded43
			}
			if true {
				value.About = layerDecoded45
			}
			if true {
				value.Participants = layerDecoded47
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.ChatPhoto = layerDecoded49
			}
			if true {
				value.NotifySettings = layerDecoded51
			}
			if wireFlags0.Has(13) {
				value.Flags.Set(13)
				value.ExportedInvite = layerDecoded53
			}
			if wireFlags0.Has(3) {
				value.Flags.Set(3)
				value.BotInfo = layerDecoded55
			}
			if wireFlags0.Has(6) {
				value.Flags.Set(6)
				value.PinnedMsgID = layerDecoded60
			}
			if wireFlags0.Has(11) {
				value.Flags.Set(11)
				value.FolderID = layerDecoded62
			}
			if wireFlags0.Has(12) {
				value.Flags.Set(12)
				value.Call = layerDecoded64
			}
			if wireFlags0.Has(14) {
				value.Flags.Set(14)
				value.TTLPeriod = layerDecoded66
			}
			if wireFlags0.Has(15) {
				value.Flags.Set(15)
				value.GroupcallDefaultJoinAs = layerDecoded68
			}
			if wireFlags0.Has(16) {
				value.Flags.Set(16)
				value.ThemeEmoticon = layerDecoded70
			}
			if wireFlags0.Has(17) {
				value.Flags.Set(17)
				value.RequestsPending = layerDecoded72
			}
			if wireFlags0.Has(17) {
				value.Flags.Set(17)
				value.RecentRequesters = layerDecoded74
			}
			if wireFlags0.Has(18) {
				value.Flags.Set(18)
				value.AvailableReactions = layerDecoded79
			}
			if wireFlags0.Has(20) {
				value.Flags.Set(20)
				value.ReactionsLimit = layerDecoded81
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeChatFull, WireID: 0x2633421b, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire2b96cd1b(profile LayerProfile, value *tg.AccountEmailVerified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeAccountEmailVerified, WireID: 0x2b96cd1b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire2b96cd1bBare(profile LayerProfile, value *tg.AccountEmailVerified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAccountEmailVerified, WireID: 0x2b96cd1b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire2b96cd1bBareBody(profile LayerProfile, value *tg.AccountEmailVerified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire2b96cd1bBare(profile, value, b, state)
}

func layerDecodeWire2b96cd1b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AccountEmailVerified, error) {
	value := new(tg.AccountEmailVerified)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire2b96cd1bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AccountEmailVerified, error) {
	value := new(tg.AccountEmailVerified)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire30f443db(profile LayerProfile, value *tg.UpdateRecentEmojiStatuses, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateRecentEmojiStatuses, WireID: 0x30f443db, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire30f443dbBare(profile LayerProfile, value *tg.UpdateRecentEmojiStatuses, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateRecentEmojiStatuses, WireID: 0x30f443db, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire30f443dbBareBody(profile LayerProfile, value *tg.UpdateRecentEmojiStatuses, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire30f443dbBare(profile, value, b, state)
}

func layerDecodeWire30f443db(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateRecentEmojiStatuses, error) {
	value := new(tg.UpdateRecentEmojiStatuses)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire30f443dbBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateRecentEmojiStatuses, error) {
	value := new(tg.UpdateRecentEmojiStatuses)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire31518e9b(profile LayerProfile, value *tg.MessageActionRequestedPeer, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessageActionRequestedPeer, WireID: 0x31518e9b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire31518e9bBare(profile LayerProfile, value *tg.MessageActionRequestedPeer, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionRequestedPeer, WireID: 0x31518e9b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire31518e9bBareBody(profile LayerProfile, value *tg.MessageActionRequestedPeer, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire31518e9bBare(profile, value, b, state)
}

func layerDecodeWire31518e9b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionRequestedPeer, error) {
	value := new(tg.MessageActionRequestedPeer)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire31518e9bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionRequestedPeer, error) {
	value := new(tg.MessageActionRequestedPeer)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire3407e51b(profile LayerProfile, value *tg.StickerSetMultiCovered, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeStickerSetMultiCovered, WireID: 0x3407e51b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire3407e51bBare(profile LayerProfile, value *tg.StickerSetMultiCovered, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStickerSetMultiCovered, WireID: 0x3407e51b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire3407e51bBareBody(profile LayerProfile, value *tg.StickerSetMultiCovered, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire3407e51bBare(profile, value, b, state)
}

func layerDecodeWire3407e51b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StickerSetMultiCovered, error) {
	value := new(tg.StickerSetMultiCovered)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire3407e51bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StickerSetMultiCovered, error) {
	value := new(tg.StickerSetMultiCovered)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire41bf109b(profile LayerProfile, value *tg.ExportedContactToken, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeExportedContactToken, WireID: 0x41bf109b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire41bf109bBare(profile LayerProfile, value *tg.ExportedContactToken, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeExportedContactToken, WireID: 0x41bf109b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire41bf109bBareBody(profile LayerProfile, value *tg.ExportedContactToken, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire41bf109bBare(profile, value, b, state)
}

func layerDecodeWire41bf109b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ExportedContactToken, error) {
	value := new(tg.ExportedContactToken)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire41bf109bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ExportedContactToken, error) {
	value := new(tg.ExportedContactToken)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire4792929b(profile LayerProfile, value *tg.MessageActionScreenshotTaken, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessageActionScreenshotTaken, WireID: 0x4792929b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire4792929bBare(profile LayerProfile, value *tg.MessageActionScreenshotTaken, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionScreenshotTaken, WireID: 0x4792929b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire4792929bBareBody(profile LayerProfile, value *tg.MessageActionScreenshotTaken, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire4792929bBare(profile, value, b, state)
}

func layerDecodeWire4792929b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionScreenshotTaken, error) {
	value := new(tg.MessageActionScreenshotTaken)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire4792929bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionScreenshotTaken, error) {
	value := new(tg.MessageActionScreenshotTaken)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire5f91eb5b(profile LayerProfile, value *tg.MessagesQuickRepliesNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesQuickRepliesNotModified, WireID: 0x5f91eb5b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire5f91eb5bBare(profile LayerProfile, value *tg.MessagesQuickRepliesNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesQuickRepliesNotModified, WireID: 0x5f91eb5b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire5f91eb5bBareBody(profile LayerProfile, value *tg.MessagesQuickRepliesNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire5f91eb5bBare(profile, value, b, state)
}

func layerDecodeWire5f91eb5b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesQuickRepliesNotModified, error) {
	value := new(tg.MessagesQuickRepliesNotModified)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire5f91eb5bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesQuickRepliesNotModified, error) {
	value := new(tg.MessagesQuickRepliesNotModified)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire7063c3db(profile LayerProfile, value *tg.UpdatePendingJoinRequests, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdatePendingJoinRequests, WireID: 0x7063c3db, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire7063c3dbBare(profile LayerProfile, value *tg.UpdatePendingJoinRequests, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdatePendingJoinRequests, WireID: 0x7063c3db, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire7063c3dbBareBody(profile LayerProfile, value *tg.UpdatePendingJoinRequests, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire7063c3dbBare(profile, value, b, state)
}

func layerDecodeWire7063c3db(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePendingJoinRequests, error) {
	value := new(tg.UpdatePendingJoinRequests)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire7063c3dbBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePendingJoinRequests, error) {
	value := new(tg.UpdatePendingJoinRequests)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire88f8f21b(profile LayerProfile, value *tg.PaymentFormMethod, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePaymentFormMethod, WireID: 0x88f8f21b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire88f8f21bBare(profile LayerProfile, value *tg.PaymentFormMethod, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePaymentFormMethod, WireID: 0x88f8f21b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire88f8f21bBareBody(profile LayerProfile, value *tg.PaymentFormMethod, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire88f8f21bBare(profile, value, b, state)
}

func layerDecodeWire88f8f21b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentFormMethod, error) {
	value := new(tg.PaymentFormMethod)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire88f8f21bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentFormMethod, error) {
	value := new(tg.PaymentFormMethod)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire9d04af9b(profile LayerProfile, value *tg.StatsGroupTopPoster, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeStatsGroupTopPoster, WireID: 0x9d04af9b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire9d04af9bBare(profile LayerProfile, value *tg.StatsGroupTopPoster, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStatsGroupTopPoster, WireID: 0x9d04af9b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9d04af9bBareBody(profile LayerProfile, value *tg.StatsGroupTopPoster, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9d04af9bBare(profile, value, b, state)
}

func layerDecodeWire9d04af9b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StatsGroupTopPoster, error) {
	value := new(tg.StatsGroupTopPoster)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire9d04af9bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StatsGroupTopPoster, error) {
	value := new(tg.StatsGroupTopPoster)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWireab661b5b(profile LayerProfile, value *tg.TopPeerCategoryBotsPM, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeTopPeerCategoryBotsPM, WireID: 0xab661b5b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWireab661b5bBare(profile LayerProfile, value *tg.TopPeerCategoryBotsPM, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTopPeerCategoryBotsPM, WireID: 0xab661b5b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireab661b5bBareBody(profile LayerProfile, value *tg.TopPeerCategoryBotsPM, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireab661b5bBare(profile, value, b, state)
}

func layerDecodeWireab661b5b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TopPeerCategoryBotsPM, error) {
	value := new(tg.TopPeerCategoryBotsPM)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWireab661b5bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TopPeerCategoryBotsPM, error) {
	value := new(tg.TopPeerCategoryBotsPM)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWirec9f06e1b(profile LayerProfile, value *tg.RequestPeerTypeChat, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeRequestPeerTypeChat, WireID: 0xc9f06e1b, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeRequestPeerTypeChat, WireID: 0xc9f06e1b, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0xc9f06e1b)
		return layerEncodeWirec9f06e1bBareBody(profile, value, b, state)

	})
}

func layerEncodeWirec9f06e1bBare(profile LayerProfile, value *tg.RequestPeerTypeChat, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeRequestPeerTypeChat, WireID: 0xc9f06e1b, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWirec9f06e1bBareBody(profile, value, b, state)
	})
}

func layerEncodeWirec9f06e1bBareBody(profile LayerProfile, value *tg.RequestPeerTypeChat, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			layerEncoded3 := &bin.Buffer{}
			layerPresent5 := (value.Flags.Has(1) || !value.UserAdminRights.Zero())
			if layerPresent5 {
				layerErr4 := func() error {
					layerEncoded3.PutID(0x5fb224d5)
					if err := layerEncodeWire5fb224d5BareBody(profile, &(value.UserAdminRights), layerEncoded3, state); err != nil {
						return fmt.Errorf("encode prepared field user_admin_rights: %w", err)
					}
					return nil
				}()
				if layerErr4 != nil {
					if IsLayerProjectionDrop(layerErr4) {
						layerPresent5 = false
						layerEncoded3.Reset()
					} else {
						return fmt.Errorf("encode optional field user_admin_rights: %w", layerErr4)
					}
				}
			}
			layerEncoded6 := &bin.Buffer{}
			layerPresent8 := (value.Flags.Has(2) || !value.BotAdminRights.Zero())
			if layerPresent8 {
				layerErr7 := func() error {
					layerEncoded6.PutID(0x5fb224d5)
					if err := layerEncodeWire5fb224d5BareBody(profile, &(value.BotAdminRights), layerEncoded6, state); err != nil {
						return fmt.Errorf("encode prepared field bot_admin_rights: %w", err)
					}
					return nil
				}()
				if layerErr7 != nil {
					if IsLayerProjectionDrop(layerErr7) {
						layerPresent8 = false
						layerEncoded6.Reset()
					} else {
						return fmt.Errorf("encode optional field bot_admin_rights: %w", layerErr7)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.Creator {
				wireFlags0.Set(0)
			}
			if layerPresent5 {
				wireFlags0.Set(1)
			}
			if layerPresent8 {
				wireFlags0.Set(2)
			}
			if value.Flags.Has(3) || value.HasUsername {
				wireFlags0.Set(3)
			}
			if value.Flags.Has(4) || value.Forum {
				wireFlags0.Set(4)
			}
			if value.Flags.Has(5) || value.BotParticipant {
				wireFlags0.Set(5)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if wireFlags0.Has(3) {
				b.PutBool(value.HasUsername)
			}
			if wireFlags0.Has(4) {
				b.PutBool(value.Forum)
			}
			if wireFlags0.Has(1) {
				b.Buf = append(b.Buf, layerEncoded3.Buf...)
			}
			if wireFlags0.Has(2) {
				b.Buf = append(b.Buf, layerEncoded6.Buf...)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeRequestPeerTypeChat, WireID: 0xc9f06e1b, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWirec9f06e1b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.RequestPeerTypeChat, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeRequestPeerTypeChat, WireID: 0xc9f06e1b, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xc9f06e1b); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xc9f06e1b: %w", err)
	}
	return layerDecodeWirec9f06e1bBare(profile, b, state)

}

func layerDecodeWirec9f06e1bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.RequestPeerTypeChat, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.RequestPeerTypeChat)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded9 := wireFlags0.Has(0)
			layerDecoded10 := wireFlags0.Has(5)
			var layerDecoded11 bool
			if wireFlags0.Has(3) {
				layerPrimitive12, err := b.Bool()
				if err != nil {
					return nil, fmt.Errorf("decode field has_username: %w", err)
				}
				layerDecoded11 = layerPrimitive12
			}
			var layerDecoded13 bool
			if wireFlags0.Has(4) {
				layerPrimitive14, err := b.Bool()
				if err != nil {
					return nil, fmt.Errorf("decode field forum: %w", err)
				}
				layerDecoded13 = layerPrimitive14
			}
			var layerDecoded15 tg.ChatAdminRights
			if wireFlags0.Has(1) {
				layerConcrete16, err := layerDecodeWire5fb224d5(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field user_admin_rights: %w", err)
				}
				layerDecoded15 = *layerConcrete16
			}
			var layerDecoded17 tg.ChatAdminRights
			if wireFlags0.Has(2) {
				layerConcrete18, err := layerDecodeWire5fb224d5(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field bot_admin_rights: %w", err)
				}
				layerDecoded17 = *layerConcrete18
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Creator = layerDecoded9
			}
			if wireFlags0.Has(5) {
				value.Flags.Set(5)
				value.BotParticipant = layerDecoded10
			}
			if wireFlags0.Has(3) {
				value.Flags.Set(3)
				value.HasUsername = layerDecoded11
			}
			if wireFlags0.Has(4) {
				value.Flags.Set(4)
				value.Forum = layerDecoded13
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.UserAdminRights = layerDecoded15
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.BotAdminRights = layerDecoded17
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeRequestPeerTypeChat, WireID: 0xc9f06e1b, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWired1ed9a5b(profile LayerProfile, value *tg.MessagesAvailableEffectsNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesAvailableEffectsNotModified, WireID: 0xd1ed9a5b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWired1ed9a5bBare(profile LayerProfile, value *tg.MessagesAvailableEffectsNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesAvailableEffectsNotModified, WireID: 0xd1ed9a5b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWired1ed9a5bBareBody(profile LayerProfile, value *tg.MessagesAvailableEffectsNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWired1ed9a5bBare(profile, value, b, state)
}

func layerDecodeWired1ed9a5b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesAvailableEffectsNotModified, error) {
	value := new(tg.MessagesAvailableEffectsNotModified)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWired1ed9a5bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesAvailableEffectsNotModified, error) {
	value := new(tg.MessagesAvailableEffectsNotModified)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWireedcdc05b(profile LayerProfile, value *tg.TopPeer, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeTopPeer, WireID: 0xedcdc05b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWireedcdc05bBare(profile LayerProfile, value *tg.TopPeer, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTopPeer, WireID: 0xedcdc05b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireedcdc05bBareBody(profile LayerProfile, value *tg.TopPeer, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireedcdc05bBare(profile, value, b, state)
}

func layerDecodeWireedcdc05b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TopPeer, error) {
	value := new(tg.TopPeer)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWireedcdc05bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TopPeer, error) {
	value := new(tg.TopPeer)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWiref7e8d89b(profile LayerProfile, value *tg.PrivacyValueAllowCloseFriends, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePrivacyValueAllowCloseFriends, WireID: 0xf7e8d89b, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWiref7e8d89bBare(profile LayerProfile, value *tg.PrivacyValueAllowCloseFriends, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePrivacyValueAllowCloseFriends, WireID: 0xf7e8d89b, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiref7e8d89bBareBody(profile LayerProfile, value *tg.PrivacyValueAllowCloseFriends, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiref7e8d89bBare(profile, value, b, state)
}

func layerDecodeWiref7e8d89b(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PrivacyValueAllowCloseFriends, error) {
	value := new(tg.PrivacyValueAllowCloseFriends)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWiref7e8d89bBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PrivacyValueAllowCloseFriends, error) {
	value := new(tg.PrivacyValueAllowCloseFriends)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}
