// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire049ee584Bare(profile LayerProfile, value *tg.Invoice, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInvoice, WireID: 0x049ee584, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire049ee584BareBody(profile LayerProfile, value *tg.Invoice, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire049ee584Bare(profile, value, b, state)
}
func layerDecodeWire049ee584(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.Invoice, error) {
	value := new(tg.Invoice)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire0e6e47c4BareBody(profile LayerProfile, value *tg.PageBlockBlockquoteBlocks, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if len(value.Blocks) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart6 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset7 := layerVectorStart6 + 4
			layerLength4 := 0
			for layerIndex5 := range value.Blocks {
				layerItemStart8 := len(b.Buf)
				layerErr9 := func() error {
					if err := layerEncodeClassPageBlockBody(profile, value.Blocks[layerIndex5], b, state); err != nil {
						return fmt.Errorf("encode field blocks element: %w", err)
					}
					return nil
				}()
				if layerErr9 != nil {
					b.Buf = b.Buf[:layerItemStart8]
					if IsLayerProjectionDrop(layerErr9) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart6]
					return fmt.Errorf("encode field blocks: %w", layerErr9)
				}
				layerLength4++
			}
			b.Buf[layerCountOffset7] = byte(layerLength4)
			b.Buf[layerCountOffset7+1] = byte(layerLength4 >> 8)
			b.Buf[layerCountOffset7+2] = byte(layerLength4 >> 16)
			b.Buf[layerCountOffset7+3] = byte(layerLength4 >> 24)
			if err := layerEncodeClassRichTextBody(profile, value.Caption, b, state); err != nil {
				return fmt.Errorf("encode field caption: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePageBlockBlockquoteBlocks, WireID: 0x0e6e47c4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire0e6e47c4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PageBlockBlockquoteBlocks, error) {
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypePageBlockBlockquoteBlocks, WireID: 0x0e6e47c4, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x0e6e47c4); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x0e6e47c4: %w", err)
	}
	return layerDecodeWire0e6e47c4Bare(profile, b, state)

}

func layerDecodeWire0e6e47c4Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PageBlockBlockquoteBlocks, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PageBlockBlockquoteBlocks)
	_ = value
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded10 []tg.PageBlockClass
			layerDecodeState11, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field blocks vector depth: %w", err)
			}
			layerLength12, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState11)
			if err != nil {
				return nil, fmt.Errorf("decode field blocks: %w", err)
			}
			var layerVector13 []tg.PageBlockClass
			if layerLength12 > 0 {
				capacity := layerLength12
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector13 = make([]tg.PageBlockClass, 0, capacity)
			}
			for index := 0; index < layerLength12; index++ {
				var element tg.PageBlockClass
				layerClass14, err := layerDecodeClassPageBlock(profile, b, &layerDecodeState11)
				if err != nil {
					return nil, fmt.Errorf("decode field blocks element: %w", err)
				}
				element = layerClass14
				layerVector13 = append(layerVector13, element)
			}
			layerDecoded10 = layerVector13
			var layerDecoded15 tg.RichTextClass
			layerClass16, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field caption: %w", err)
			}
			layerDecoded15 = layerClass16
			if true {
				value.Blocks = layerDecoded10
			}
			if true {
				value.Caption = layerDecoded15
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypePageBlockBlockquoteBlocks, WireID: 0x0e6e47c4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire1a542004BareBody(profile LayerProfile, value *tg.MessagesTranslateRichMessageRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile228, LayerProfile229:
		{
			if value.Flags.Has(0) && value.Peer == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, Reason: "malformed canonical value: explicit flag has nil interface field peer"}
			}
			if value.Flags.Has(1) && value.Text == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, Reason: "malformed canonical value: explicit flag has nil interface field text"}
			}
			layerEncoded5 := &bin.Buffer{}
			layerPresent7 := (value.Flags.Has(0) || value.Peer != nil) || (value.Flags.Has(0) || value.ID != nil)
			if layerPresent7 {
				layerErr6 := func() error {
					if err := layerEncodeClassInputPeerBody(profile, value.Peer, layerEncoded5, state); err != nil {
						return fmt.Errorf("encode prepared field peer: %w", err)
					}
					return nil
				}()
				if layerErr6 != nil {
					if IsLayerProjectionDrop(layerErr6) {
						layerPresent7 = false
						layerEncoded5.Reset()
					} else {
						return fmt.Errorf("encode optional field peer: %w", layerErr6)
					}
				}
			}
			layerEncoded8 := &bin.Buffer{}
			layerPresent12 := (value.Flags.Has(0) || value.Peer != nil) || (value.Flags.Has(0) || value.ID != nil)
			if layerPresent12 {
				layerErr9 := func() error {
					if len(value.ID) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerEncoded8.PutVectorHeader(len(value.ID))
					for layerIndex11 := range value.ID {
						layerEncoded8.PutInt(value.ID[layerIndex11])
					}
					return nil
				}()
				if layerErr9 != nil {
					if IsLayerProjectionDrop(layerErr9) {
						layerPresent12 = false
						layerEncoded8.Reset()
					} else {
						return fmt.Errorf("encode optional field id: %w", layerErr9)
					}
				}
			}
			layerEncoded13 := &bin.Buffer{}
			layerPresent21 := (value.Flags.Has(1) || value.Text != nil)
			if layerPresent21 {
				layerErr14 := func() error {
					if len(value.Text) > layerCodecMaxVectorElements {
						return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
					}
					layerVectorStart17 := len(layerEncoded13.Buf)
					layerEncoded13.PutVectorHeader(0)
					layerCountOffset18 := layerVectorStart17 + 4
					layerLength15 := 0
					for layerIndex16 := range value.Text {
						layerItemStart19 := len(layerEncoded13.Buf)
						layerErr20 := func() error {
							if err := layerEncodeClassInputRichMessageBody(profile, value.Text[layerIndex16], layerEncoded13, state); err != nil {
								return fmt.Errorf("encode prepared field text element: %w", err)
							}
							return nil
						}()
						if layerErr20 != nil {
							layerEncoded13.Buf = layerEncoded13.Buf[:layerItemStart19]
							if IsLayerProjectionDrop(layerErr20) {
								continue
							}
							layerEncoded13.Buf = layerEncoded13.Buf[:layerVectorStart17]
							return fmt.Errorf("encode prepared field text: %w", layerErr20)
						}
						layerLength15++
					}
					layerEncoded13.Buf[layerCountOffset18] = byte(layerLength15)
					layerEncoded13.Buf[layerCountOffset18+1] = byte(layerLength15 >> 8)
					layerEncoded13.Buf[layerCountOffset18+2] = byte(layerLength15 >> 16)
					layerEncoded13.Buf[layerCountOffset18+3] = byte(layerLength15 >> 24)
					return nil
				}()
				if layerErr14 != nil {
					if IsLayerProjectionDrop(layerErr14) {
						layerPresent21 = false
						layerEncoded13.Reset()
					} else {
						return fmt.Errorf("encode optional field text: %w", layerErr14)
					}
				}
			}
			var wireFlags0 bin.Fields
			if (layerPresent7 || layerPresent12) && !layerPresent7 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, Reason: "shared flag group flags.0 projected only partially"}
			}
			if (layerPresent7 || layerPresent12) && !layerPresent12 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, Reason: "shared flag group flags.0 projected only partially"}
			}
			if layerPresent7 || layerPresent12 {
				wireFlags0.Set(0)
			}
			if layerPresent21 {
				wireFlags0.Set(1)
			}
			if value.Flags.Has(2) || value.Tone != "" {
				wireFlags0.Set(2)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if wireFlags0.Has(0) {
				b.Buf = append(b.Buf, layerEncoded5.Buf...)
			}
			if wireFlags0.Has(0) {
				b.Buf = append(b.Buf, layerEncoded8.Buf...)
			}
			if wireFlags0.Has(1) {
				b.Buf = append(b.Buf, layerEncoded13.Buf...)
			}
			if err := b.PutStringChecked(value.ToLang); err != nil {
				return fmt.Errorf("encode field to_lang: %w", err)
			}
			if wireFlags0.Has(2) {
				if err := b.PutStringChecked(value.Tone); err != nil {
					return fmt.Errorf("encode field tone: %w", err)
				}
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, WireID: 0x1a542004, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire1a542004(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesTranslateRichMessageRequest, error) {
	switch profile {
	case LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, WireID: 0x1a542004, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x1a542004); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x1a542004: %w", err)
	}
	return layerDecodeWire1a542004Bare(profile, b, state)

}

func layerDecodeWire1a542004Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesTranslateRichMessageRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesTranslateRichMessageRequest)
	_ = value
	switch profile {
	case LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			var layerDecoded22 tg.InputPeerClass
			if wireFlags0.Has(0) {
				layerClass23, err := layerDecodeClassInputPeer(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field peer: %w", err)
				}
				layerDecoded22 = layerClass23
			}
			var layerDecoded24 []int
			if wireFlags0.Has(0) {
				layerDecodeState25, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field id vector depth: %w", err)
				}
				layerLength26, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState25)
				if err != nil {
					return nil, fmt.Errorf("decode field id: %w", err)
				}
				var layerVector27 []int
				if layerLength26 > 0 {
					capacity := layerLength26
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector27 = make([]int, 0, capacity)
				}
				for index := 0; index < layerLength26; index++ {
					var element int
					layerPrimitive28, err := b.Int()
					if err != nil {
						return nil, fmt.Errorf("decode field id element: %w", err)
					}
					element = layerPrimitive28
					layerVector27 = append(layerVector27, element)
				}
				layerDecoded24 = layerVector27
			}
			var layerDecoded29 []tg.InputRichMessageClass
			if wireFlags0.Has(1) {
				layerDecodeState30, err := layerCodecDescend(profile, "decode", state)
				if err != nil {
					return nil, fmt.Errorf("decode field text vector depth: %w", err)
				}
				layerLength31, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState30)
				if err != nil {
					return nil, fmt.Errorf("decode field text: %w", err)
				}
				var layerVector32 []tg.InputRichMessageClass
				if layerLength31 > 0 {
					capacity := layerLength31
					if capacity > bin.PreallocateLimit {
						capacity = bin.PreallocateLimit
					}
					layerVector32 = make([]tg.InputRichMessageClass, 0, capacity)
				}
				for index := 0; index < layerLength31; index++ {
					var element tg.InputRichMessageClass
					layerClass33, err := layerDecodeClassInputRichMessage(profile, b, &layerDecodeState30)
					if err != nil {
						return nil, fmt.Errorf("decode field text element: %w", err)
					}
					element = layerClass33
					layerVector32 = append(layerVector32, element)
				}
				layerDecoded29 = layerVector32
			}
			var layerDecoded34 string
			layerPrimitive35, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field to_lang: %w", err)
			}
			layerDecoded34 = layerPrimitive35
			var layerDecoded36 string
			if wireFlags0.Has(2) {
				layerPrimitive37, err := b.String()
				if err != nil {
					return nil, fmt.Errorf("decode field tone: %w", err)
				}
				layerDecoded36 = layerPrimitive37
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Peer = layerDecoded22
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.ID = layerDecoded24
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.Text = layerDecoded29
			}
			if true {
				value.ToLang = layerDecoded34
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.Tone = layerDecoded36
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesTranslateRichMessage, WireID: 0x1a542004, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire2390fe44BareBody(profile LayerProfile, value *tg.AuthSentCodeSuccess, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassAuthAuthorizationBody(profile, value.Authorization, b, state); err != nil {
				return fmt.Errorf("encode field authorization: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthSentCodeSuccess, WireID: 0x2390fe44, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire2390fe44(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AuthSentCodeSuccess, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeAuthSentCodeSuccess, WireID: 0x2390fe44, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x2390fe44); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x2390fe44: %w", err)
	}
	return layerDecodeWire2390fe44Bare(profile, b, state)

}

func layerDecodeWire2390fe44Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AuthSentCodeSuccess, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.AuthSentCodeSuccess)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.AuthAuthorizationClass
			layerClass3, err := layerDecodeClassAuthAuthorization(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field authorization: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Authorization = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeAuthSentCodeSuccess, WireID: 0x2390fe44, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire2eeed1c4Bare(profile LayerProfile, value *tg.StarGiftAuctionUserState, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStarGiftAuctionUserState, WireID: 0x2eeed1c4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire2eeed1c4BareBody(profile LayerProfile, value *tg.StarGiftAuctionUserState, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire2eeed1c4Bare(profile, value, b, state)
}
func layerDecodeWire2eeed1c4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StarGiftAuctionUserState, error) {
	value := new(tg.StarGiftAuctionUserState)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire6724abc4BareBody(profile LayerProfile, value *tg.TextBold, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassRichTextBody(profile, value.Text, b, state); err != nil {
				return fmt.Errorf("encode field text: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextBold, WireID: 0x6724abc4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire6724abc4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextBold, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeTextBold, WireID: 0x6724abc4, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x6724abc4); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x6724abc4: %w", err)
	}
	return layerDecodeWire6724abc4Bare(profile, b, state)

}

func layerDecodeWire6724abc4Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextBold, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.TextBold)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.RichTextClass
			layerClass3, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field text: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Text = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeTextBold, WireID: 0x6724abc4, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire69ef72c4Bare(profile LayerProfile, value *tg.InputDialogPeerCommunity, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputDialogPeerCommunity, WireID: 0x69ef72c4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire69ef72c4BareBody(profile LayerProfile, value *tg.InputDialogPeerCommunity, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire69ef72c4Bare(profile, value, b, state)
}
func layerDecodeWire69ef72c4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputDialogPeerCommunity, error) {
	value := new(tg.InputDialogPeerCommunity)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire71f276c4Bare(profile LayerProfile, value *tg.DisallowedGiftsSettings, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeDisallowedGiftsSettings, WireID: 0x71f276c4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire71f276c4BareBody(profile LayerProfile, value *tg.DisallowedGiftsSettings, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire71f276c4Bare(profile, value, b, state)
}
func layerDecodeWire71f276c4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.DisallowedGiftsSettings, error) {
	value := new(tg.DisallowedGiftsSettings)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire74cda504Bare(profile LayerProfile, value *tg.MessagePeerVoteInputOption, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagePeerVoteInputOption, WireID: 0x74cda504, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire74cda504BareBody(profile LayerProfile, value *tg.MessagePeerVoteInputOption, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire74cda504Bare(profile, value, b, state)
}
func layerDecodeWire74cda504(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagePeerVoteInputOption, error) {
	value := new(tg.MessagePeerVoteInputOption)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire7d748d04Bare(profile LayerProfile, value *tg.DataJSON, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeDataJSON, WireID: 0x7d748d04, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire7d748d04BareBody(profile LayerProfile, value *tg.DataJSON, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire7d748d04Bare(profile, value, b, state)
}
func layerDecodeWire7d748d04(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.DataJSON, error) {
	value := new(tg.DataJSON)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire90a6ca84Bare(profile LayerProfile, value *tg.MessageEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageEmpty, WireID: 0x90a6ca84, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire90a6ca84BareBody(profile LayerProfile, value *tg.MessageEmpty, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire90a6ca84Bare(profile, value, b, state)
}
func layerDecodeWire90a6ca84(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageEmpty, error) {
	value := new(tg.MessageEmpty)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire9cd81144BareBody(profile LayerProfile, value *tg.MessagesChatsSlice, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			b.PutInt(value.Count)
			if len(value.Chats) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart5 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset6 := layerVectorStart5 + 4
			layerLength3 := 0
			for layerIndex4 := range value.Chats {
				layerItemStart7 := len(b.Buf)
				layerErr8 := func() error {
					if err := layerEncodeClassChatBody(profile, value.Chats[layerIndex4], b, state); err != nil {
						return fmt.Errorf("encode field chats element: %w", err)
					}
					return nil
				}()
				if layerErr8 != nil {
					b.Buf = b.Buf[:layerItemStart7]
					if IsLayerProjectionDrop(layerErr8) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart5]
					return fmt.Errorf("encode field chats: %w", layerErr8)
				}
				layerLength3++
			}
			b.Buf[layerCountOffset6] = byte(layerLength3)
			b.Buf[layerCountOffset6+1] = byte(layerLength3 >> 8)
			b.Buf[layerCountOffset6+2] = byte(layerLength3 >> 16)
			b.Buf[layerCountOffset6+3] = byte(layerLength3 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesChatsSlice, WireID: 0x9cd81144, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire9cd81144(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesChatsSlice, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeMessagesChatsSlice, WireID: 0x9cd81144, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x9cd81144); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x9cd81144: %w", err)
	}
	return layerDecodeWire9cd81144Bare(profile, b, state)

}

func layerDecodeWire9cd81144Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesChatsSlice, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesChatsSlice)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded9 int
			layerPrimitive10, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field count: %w", err)
			}
			layerDecoded9 = layerPrimitive10
			var layerDecoded11 []tg.ChatClass
			layerDecodeState12, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field chats vector depth: %w", err)
			}
			layerLength13, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState12)
			if err != nil {
				return nil, fmt.Errorf("decode field chats: %w", err)
			}
			var layerVector14 []tg.ChatClass
			if layerLength13 > 0 {
				capacity := layerLength13
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector14 = make([]tg.ChatClass, 0, capacity)
			}
			for index := 0; index < layerLength13; index++ {
				var element tg.ChatClass
				layerClass15, err := layerDecodeClassChat(profile, b, &layerDecodeState12)
				if err != nil {
					return nil, fmt.Errorf("decode field chats element: %w", err)
				}
				element = layerClass15
				layerVector14 = append(layerVector14, element)
			}
			layerDecoded11 = layerVector14
			if true {
				value.Count = layerDecoded9
			}
			if true {
				value.Chats = layerDecoded11
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesChatsSlice, WireID: 0x9cd81144, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire9fbab604Bare(profile LayerProfile, value *tg.MessageActionHistoryClear, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionHistoryClear, WireID: 0x9fbab604, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9fbab604BareBody(profile LayerProfile, value *tg.MessageActionHistoryClear, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9fbab604Bare(profile, value, b, state)
}
func layerDecodeWire9fbab604(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionHistoryClear, error) {
	value := new(tg.MessageActionHistoryClear)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireac072444Bare(profile LayerProfile, value *tg.UpdateStarGiftCraftFail, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateStarGiftCraftFail, WireID: 0xac072444, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireac072444BareBody(profile LayerProfile, value *tg.UpdateStarGiftCraftFail, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireac072444Bare(profile, value, b, state)
}
func layerDecodeWireac072444(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateStarGiftCraftFail, error) {
	value := new(tg.UpdateStarGiftCraftFail)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWirec12622c4BareBody(profile LayerProfile, value *tg.TextUnderline, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassRichTextBody(profile, value.Text, b, state); err != nil {
				return fmt.Errorf("encode field text: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextUnderline, WireID: 0xc12622c4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWirec12622c4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextUnderline, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeTextUnderline, WireID: 0xc12622c4, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xc12622c4); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xc12622c4: %w", err)
	}
	return layerDecodeWirec12622c4Bare(profile, b, state)

}

func layerDecodeWirec12622c4Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextUnderline, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.TextUnderline)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.RichTextClass
			layerClass3, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field text: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Text = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeTextUnderline, WireID: 0xc12622c4, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirec3dffc04Bare(profile LayerProfile, value *tg.ChatTheme, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChatTheme, WireID: 0xc3dffc04, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirec3dffc04BareBody(profile LayerProfile, value *tg.ChatTheme, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirec3dffc04Bare(profile, value, b, state)
}
func layerDecodeWirec3dffc04(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChatTheme, error) {
	value := new(tg.ChatTheme)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWirecd24cf44BareBody(profile LayerProfile, value *tg.TextMention, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassRichTextBody(profile, value.Text, b, state); err != nil {
				return fmt.Errorf("encode field text: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextMention, WireID: 0xcd24cf44, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWirecd24cf44(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextMention, error) {
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeTextMention, WireID: 0xcd24cf44, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xcd24cf44); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xcd24cf44: %w", err)
	}
	return layerDecodeWirecd24cf44Bare(profile, b, state)

}

func layerDecodeWirecd24cf44Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextMention, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.TextMention)
	_ = value
	switch profile {
	case LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.RichTextClass
			layerClass3, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field text: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Text = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeTextMention, WireID: 0xcd24cf44, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree011e1c4Bare(profile LayerProfile, value *tg.AccountChatThemesNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAccountChatThemesNotModified, WireID: 0xe011e1c4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree011e1c4BareBody(profile LayerProfile, value *tg.AccountChatThemesNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree011e1c4Bare(profile, value, b, state)
}

func layerEncodeWireeb032884BareBody(profile LayerProfile, value *tg.ContactsSponsoredPeers, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if len(value.Peers) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart9 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset10 := layerVectorStart9 + 4
			layerLength7 := 0
			for layerIndex8 := range value.Peers {
				layerItemStart11 := len(b.Buf)
				layerErr12 := func() error {
					b.PutID(0xc69708d3)
					if err := layerEncodeWirec69708d3BareBody(profile, &(value.Peers[layerIndex8]), b, state); err != nil {
						return fmt.Errorf("encode field peers element: %w", err)
					}
					return nil
				}()
				if layerErr12 != nil {
					b.Buf = b.Buf[:layerItemStart11]
					if IsLayerProjectionDrop(layerErr12) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart9]
					return fmt.Errorf("encode field peers: %w", layerErr12)
				}
				layerLength7++
			}
			b.Buf[layerCountOffset10] = byte(layerLength7)
			b.Buf[layerCountOffset10+1] = byte(layerLength7 >> 8)
			b.Buf[layerCountOffset10+2] = byte(layerLength7 >> 16)
			b.Buf[layerCountOffset10+3] = byte(layerLength7 >> 24)
			if len(value.Chats) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart15 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset16 := layerVectorStart15 + 4
			layerLength13 := 0
			for layerIndex14 := range value.Chats {
				layerItemStart17 := len(b.Buf)
				layerErr18 := func() error {
					if err := layerEncodeClassChatBody(profile, value.Chats[layerIndex14], b, state); err != nil {
						return fmt.Errorf("encode field chats element: %w", err)
					}
					return nil
				}()
				if layerErr18 != nil {
					b.Buf = b.Buf[:layerItemStart17]
					if IsLayerProjectionDrop(layerErr18) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart15]
					return fmt.Errorf("encode field chats: %w", layerErr18)
				}
				layerLength13++
			}
			b.Buf[layerCountOffset16] = byte(layerLength13)
			b.Buf[layerCountOffset16+1] = byte(layerLength13 >> 8)
			b.Buf[layerCountOffset16+2] = byte(layerLength13 >> 16)
			b.Buf[layerCountOffset16+3] = byte(layerLength13 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart21 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset22 := layerVectorStart21 + 4
			layerLength19 := 0
			for layerIndex20 := range value.Users {
				layerItemStart23 := len(b.Buf)
				layerErr24 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex20], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr24 != nil {
					b.Buf = b.Buf[:layerItemStart23]
					if IsLayerProjectionDrop(layerErr24) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart21]
					return fmt.Errorf("encode field users: %w", layerErr24)
				}
				layerLength19++
			}
			b.Buf[layerCountOffset22] = byte(layerLength19)
			b.Buf[layerCountOffset22+1] = byte(layerLength19 >> 8)
			b.Buf[layerCountOffset22+2] = byte(layerLength19 >> 16)
			b.Buf[layerCountOffset22+3] = byte(layerLength19 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeContactsSponsoredPeers, WireID: 0xeb032884, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireeb032884(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ContactsSponsoredPeers, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeContactsSponsoredPeers, WireID: 0xeb032884, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xeb032884); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xeb032884: %w", err)
	}
	return layerDecodeWireeb032884Bare(profile, b, state)

}

func layerDecodeWireeb032884Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ContactsSponsoredPeers, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.ContactsSponsoredPeers)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded25 []tg.SponsoredPeer
			layerDecodeState26, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field peers vector depth: %w", err)
			}
			layerLength27, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState26)
			if err != nil {
				return nil, fmt.Errorf("decode field peers: %w", err)
			}
			var layerVector28 []tg.SponsoredPeer
			if layerLength27 > 0 {
				capacity := layerLength27
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector28 = make([]tg.SponsoredPeer, 0, capacity)
			}
			for index := 0; index < layerLength27; index++ {
				var element tg.SponsoredPeer
				layerConcrete29, err := layerDecodeWirec69708d3(profile, b, &layerDecodeState26)
				if err != nil {
					return nil, fmt.Errorf("decode field peers element: %w", err)
				}
				element = *layerConcrete29
				layerVector28 = append(layerVector28, element)
			}
			layerDecoded25 = layerVector28
			var layerDecoded30 []tg.ChatClass
			layerDecodeState31, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field chats vector depth: %w", err)
			}
			layerLength32, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState31)
			if err != nil {
				return nil, fmt.Errorf("decode field chats: %w", err)
			}
			var layerVector33 []tg.ChatClass
			if layerLength32 > 0 {
				capacity := layerLength32
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector33 = make([]tg.ChatClass, 0, capacity)
			}
			for index := 0; index < layerLength32; index++ {
				var element tg.ChatClass
				layerClass34, err := layerDecodeClassChat(profile, b, &layerDecodeState31)
				if err != nil {
					return nil, fmt.Errorf("decode field chats element: %w", err)
				}
				element = layerClass34
				layerVector33 = append(layerVector33, element)
			}
			layerDecoded30 = layerVector33
			var layerDecoded35 []tg.UserClass
			layerDecodeState36, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength37, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState36)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector38 []tg.UserClass
			if layerLength37 > 0 {
				capacity := layerLength37
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector38 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength37; index++ {
				var element tg.UserClass
				layerClass39, err := layerDecodeClassUser(profile, b, &layerDecodeState36)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass39
				layerVector38 = append(layerVector38, element)
			}
			layerDecoded35 = layerVector38
			if true {
				value.Peers = layerDecoded25
			}
			if true {
				value.Chats = layerDecoded30
			}
			if true {
				value.Users = layerDecoded35
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeContactsSponsoredPeers, WireID: 0xeb032884, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWireed6a8504BareBody(profile LayerProfile, value *tg.TextSubscript, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassRichTextBody(profile, value.Text, b, state); err != nil {
				return fmt.Errorf("encode field text: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextSubscript, WireID: 0xed6a8504, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireed6a8504(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextSubscript, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeTextSubscript, WireID: 0xed6a8504, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xed6a8504); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xed6a8504: %w", err)
	}
	return layerDecodeWireed6a8504Bare(profile, b, state)

}

func layerDecodeWireed6a8504Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextSubscript, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.TextSubscript)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.RichTextClass
			layerClass3, err := layerDecodeClassRichText(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field text: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Text = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeTextSubscript, WireID: 0xed6a8504, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiref18cda44Bare(profile LayerProfile, value *tg.UploadFileCDNRedirect, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUploadFileCDNRedirect, WireID: 0xf18cda44, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiref18cda44BareBody(profile LayerProfile, value *tg.UploadFileCDNRedirect, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiref18cda44Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiref9c44144Bare(profile LayerProfile, value *tg.InputMediaGeoPoint, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputMediaGeoPoint, WireID: 0xf9c44144, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiref9c44144BareBody(profile LayerProfile, value *tg.InputMediaGeoPoint, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiref9c44144Bare(profile, value, b, state)
}
func layerDecodeWiref9c44144(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputMediaGeoPoint, error) {
	value := new(tg.InputMediaGeoPoint)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWirefff8fdc4BareBody(profile LayerProfile, value *tg.InputBotInlineResultDocument, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if value.Flags.Has(1) || value.Title != "" {
				wireFlags0.Set(1)
			}
			if value.Flags.Has(2) || value.Description != "" {
				wireFlags0.Set(2)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if err := b.PutStringChecked(value.ID); err != nil {
				return fmt.Errorf("encode field id: %w", err)
			}
			if err := b.PutStringChecked(value.Type); err != nil {
				return fmt.Errorf("encode field type: %w", err)
			}
			if wireFlags0.Has(1) {
				if err := b.PutStringChecked(value.Title); err != nil {
					return fmt.Errorf("encode field title: %w", err)
				}
			}
			if wireFlags0.Has(2) {
				if err := b.PutStringChecked(value.Description); err != nil {
					return fmt.Errorf("encode field description: %w", err)
				}
			}
			if err := layerEncodeClassInputDocumentBody(profile, value.Document, b, state); err != nil {
				return fmt.Errorf("encode field document: %w", err)
			}
			if err := layerEncodeClassInputBotInlineMessageBody(profile, value.SendMessage, b, state); err != nil {
				return fmt.Errorf("encode field send_message: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputBotInlineResultDocument, WireID: 0xfff8fdc4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWirefff8fdc4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputBotInlineResultDocument, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeInputBotInlineResultDocument, WireID: 0xfff8fdc4, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xfff8fdc4); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xfff8fdc4: %w", err)
	}
	return layerDecodeWirefff8fdc4Bare(profile, b, state)

}

func layerDecodeWirefff8fdc4Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputBotInlineResultDocument, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.InputBotInlineResultDocument)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			var layerDecoded3 string
			layerPrimitive4, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field id: %w", err)
			}
			layerDecoded3 = layerPrimitive4
			var layerDecoded5 string
			layerPrimitive6, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field type: %w", err)
			}
			layerDecoded5 = layerPrimitive6
			var layerDecoded7 string
			if wireFlags0.Has(1) {
				layerPrimitive8, err := b.String()
				if err != nil {
					return nil, fmt.Errorf("decode field title: %w", err)
				}
				layerDecoded7 = layerPrimitive8
			}
			var layerDecoded9 string
			if wireFlags0.Has(2) {
				layerPrimitive10, err := b.String()
				if err != nil {
					return nil, fmt.Errorf("decode field description: %w", err)
				}
				layerDecoded9 = layerPrimitive10
			}
			var layerDecoded11 tg.InputDocumentClass
			layerClass12, err := layerDecodeClassInputDocument(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field document: %w", err)
			}
			layerDecoded11 = layerClass12
			var layerDecoded13 tg.InputBotInlineMessageClass
			layerClass14, err := layerDecodeClassInputBotInlineMessage(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field send_message: %w", err)
			}
			layerDecoded13 = layerClass14
			if true {
				value.ID = layerDecoded3
			}
			if true {
				value.Type = layerDecoded5
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.Title = layerDecoded7
			}
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.Description = layerDecoded9
			}
			if true {
				value.Document = layerDecoded11
			}
			if true {
				value.SendMessage = layerDecoded13
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeInputBotInlineResultDocument, WireID: 0xfff8fdc4, Reason: "wire ID is unavailable in exact profile"}
	}
}
