// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire05f58d0f(profile LayerProfile, value *tg.ContactsSearchRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodContactsSearch, WireID: 0x05f58d0f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire05f58d0fBare(profile LayerProfile, value *tg.ContactsSearchRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodContactsSearch, WireID: 0x05f58d0f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire05f58d0fBareBody(profile LayerProfile, value *tg.ContactsSearchRequest, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire05f58d0fBare(profile, value, b, state)
}

func layerDecodeWire05f58d0f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ContactsSearchRequest, error) {
	value := new(tg.ContactsSearchRequest)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire05f58d0fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ContactsSearchRequest, error) {
	value := new(tg.ContactsSearchRequest)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire081ccf4f(profile LayerProfile, value *tg.TextImage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeTextImage, WireID: 0x081ccf4f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire081ccf4fBare(profile LayerProfile, value *tg.TextImage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextImage, WireID: 0x081ccf4f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire081ccf4fBareBody(profile LayerProfile, value *tg.TextImage, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire081ccf4fBare(profile, value, b, state)
}

func layerDecodeWire081ccf4f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextImage, error) {
	value := new(tg.TextImage)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire081ccf4fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextImage, error) {
	value := new(tg.TextImage)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire1839490f(profile LayerProfile, value *tg.MessagesSponsoredMessagesEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesSponsoredMessagesEmpty, WireID: 0x1839490f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire1839490fBare(profile LayerProfile, value *tg.MessagesSponsoredMessagesEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesSponsoredMessagesEmpty, WireID: 0x1839490f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire1839490fBareBody(profile LayerProfile, value *tg.MessagesSponsoredMessagesEmpty, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire1839490fBare(profile, value, b, state)
}

func layerDecodeWire1839490f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSponsoredMessagesEmpty, error) {
	value := new(tg.MessagesSponsoredMessagesEmpty)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire1839490fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSponsoredMessagesEmpty, error) {
	value := new(tg.MessagesSponsoredMessagesEmpty)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire32ca960f(profile LayerProfile, value *tg.MessageEntitySpoiler, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessageEntitySpoiler, WireID: 0x32ca960f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire32ca960fBare(profile LayerProfile, value *tg.MessageEntitySpoiler, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageEntitySpoiler, WireID: 0x32ca960f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire32ca960fBareBody(profile LayerProfile, value *tg.MessageEntitySpoiler, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire32ca960fBare(profile, value, b, state)
}

func layerDecodeWire32ca960f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageEntitySpoiler, error) {
	value := new(tg.MessageEntitySpoiler)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire32ca960fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageEntitySpoiler, error) {
	value := new(tg.MessageEntitySpoiler)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire3354678f(profile LayerProfile, value *tg.UpdatePtsChanged, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdatePtsChanged, WireID: 0x3354678f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire3354678fBare(profile LayerProfile, value *tg.UpdatePtsChanged, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdatePtsChanged, WireID: 0x3354678f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire3354678fBareBody(profile LayerProfile, value *tg.UpdatePtsChanged, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire3354678fBare(profile, value, b, state)
}

func layerDecodeWire3354678f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePtsChanged, error) {
	value := new(tg.UpdatePtsChanged)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire3354678fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePtsChanged, error) {
	value := new(tg.UpdatePtsChanged)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire3504914f(profile LayerProfile, value *tg.UpdateDialogFilters, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateDialogFilters, WireID: 0x3504914f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire3504914fBare(profile LayerProfile, value *tg.UpdateDialogFilters, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateDialogFilters, WireID: 0x3504914f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire3504914fBareBody(profile LayerProfile, value *tg.UpdateDialogFilters, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire3504914fBare(profile, value, b, state)
}

func layerDecodeWire3504914f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateDialogFilters, error) {
	value := new(tg.UpdateDialogFilters)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire3504914fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateDialogFilters, error) {
	value := new(tg.UpdateDialogFilters)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire3e050d0f(profile LayerProfile, value *tg.UpdateQuickReplyMessage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateQuickReplyMessage, WireID: 0x3e050d0f, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateQuickReplyMessage, WireID: 0x3e050d0f, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0x3e050d0f)
		return layerEncodeWire3e050d0fBareBody(profile, value, b, state)

	})
}

func layerEncodeWire3e050d0fBare(profile LayerProfile, value *tg.UpdateQuickReplyMessage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateQuickReplyMessage, WireID: 0x3e050d0f, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire3e050d0fBareBody(profile, value, b, state)
	})
}

func layerEncodeWire3e050d0fBareBody(profile LayerProfile, value *tg.UpdateQuickReplyMessage, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			if err := layerEncodeClassMessageBody(profile, value.Message, b, state); err != nil {
				return fmt.Errorf("encode field message: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateQuickReplyMessage, WireID: 0x3e050d0f, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire3e050d0f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateQuickReplyMessage, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeUpdateQuickReplyMessage, WireID: 0x3e050d0f, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x3e050d0f); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x3e050d0f: %w", err)
	}
	return layerDecodeWire3e050d0fBare(profile, b, state)

}

func layerDecodeWire3e050d0fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateQuickReplyMessage, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.UpdateQuickReplyMessage)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var layerDecoded2 tg.MessageClass
			layerClass3, err := layerDecodeClassMessage(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field message: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Message = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateQuickReplyMessage, WireID: 0x3e050d0f, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire417efd8f(profile LayerProfile, value *tg.KeyboardButtonRequestPhone, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPhone, WireID: 0x417efd8f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire417efd8fBare(profile LayerProfile, value *tg.KeyboardButtonRequestPhone, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPhone, WireID: 0x417efd8f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire417efd8fBareBody(profile LayerProfile, value *tg.KeyboardButtonRequestPhone, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire417efd8fBare(profile, value, b, state)
}

func layerDecodeWire417efd8f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.KeyboardButtonRequestPhone, error) {
	value := new(tg.KeyboardButtonRequestPhone)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire417efd8fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.KeyboardButtonRequestPhone, error) {
	value := new(tg.KeyboardButtonRequestPhone)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire4203998f(profile LayerProfile, value *tg.MessagesTranslatedRichMessage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesTranslatedRichMessage, WireID: 0x4203998f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire4203998fBare(profile LayerProfile, value *tg.MessagesTranslatedRichMessage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesTranslatedRichMessage, WireID: 0x4203998f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire4203998fBareBody(profile LayerProfile, value *tg.MessagesTranslatedRichMessage, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire4203998fBare(profile, value, b, state)
}

func layerDecodeWire4203998f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesTranslatedRichMessage, error) {
	value := new(tg.MessagesTranslatedRichMessage)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire4203998fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesTranslatedRichMessage, error) {
	value := new(tg.MessagesTranslatedRichMessage)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire504aa18f(profile LayerProfile, value *tg.UpdateSentPhoneCode, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateSentPhoneCode, WireID: 0x504aa18f, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateSentPhoneCode, WireID: 0x504aa18f, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0x504aa18f)
		return layerEncodeWire504aa18fBareBody(profile, value, b, state)

	})
}

func layerEncodeWire504aa18fBare(profile LayerProfile, value *tg.UpdateSentPhoneCode, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSentPhoneCode, WireID: 0x504aa18f, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire504aa18fBareBody(profile, value, b, state)
	})
}

func layerEncodeWire504aa18fBareBody(profile LayerProfile, value *tg.UpdateSentPhoneCode, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			if err := layerEncodeClassAuthSentCodeBody(profile, value.SentCode, b, state); err != nil {
				return fmt.Errorf("encode field sent_code: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSentPhoneCode, WireID: 0x504aa18f, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire504aa18f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateSentPhoneCode, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeUpdateSentPhoneCode, WireID: 0x504aa18f, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x504aa18f); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x504aa18f: %w", err)
	}
	return layerDecodeWire504aa18fBare(profile, b, state)

}

func layerDecodeWire504aa18fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateSentPhoneCode, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.UpdateSentPhoneCode)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var layerDecoded2 tg.AuthSentCodeClass
			layerClass3, err := layerDecodeClassAuthSentCode(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field sent_code: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.SentCode = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSentPhoneCode, WireID: 0x504aa18f, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire51e6ee4f(profile LayerProfile, value *tg.StoryItemDeleted, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeStoryItemDeleted, WireID: 0x51e6ee4f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire51e6ee4fBare(profile LayerProfile, value *tg.StoryItemDeleted, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStoryItemDeleted, WireID: 0x51e6ee4f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire51e6ee4fBareBody(profile LayerProfile, value *tg.StoryItemDeleted, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire51e6ee4fBare(profile, value, b, state)
}

func layerDecodeWire51e6ee4f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StoryItemDeleted, error) {
	value := new(tg.StoryItemDeleted)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire51e6ee4fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StoryItemDeleted, error) {
	value := new(tg.StoryItemDeleted)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire811f854f(profile LayerProfile, value *tg.AccountSentEmailCode, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeAccountSentEmailCode, WireID: 0x811f854f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire811f854fBare(profile LayerProfile, value *tg.AccountSentEmailCode, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAccountSentEmailCode, WireID: 0x811f854f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire811f854fBareBody(profile LayerProfile, value *tg.AccountSentEmailCode, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire811f854fBare(profile, value, b, state)
}

func layerDecodeWire811f854f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AccountSentEmailCode, error) {
	value := new(tg.AccountSentEmailCode)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire811f854fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.AccountSentEmailCode, error) {
	value := new(tg.AccountSentEmailCode)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire840649cf(profile LayerProfile, value *tg.InputPrivacyValueAllowChatParticipants, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputPrivacyValueAllowChatParticipants, WireID: 0x840649cf, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire840649cfBare(profile LayerProfile, value *tg.InputPrivacyValueAllowChatParticipants, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputPrivacyValueAllowChatParticipants, WireID: 0x840649cf, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire840649cfBareBody(profile LayerProfile, value *tg.InputPrivacyValueAllowChatParticipants, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire840649cfBare(profile, value, b, state)
}

func layerDecodeWire840649cf(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputPrivacyValueAllowChatParticipants, error) {
	value := new(tg.InputPrivacyValueAllowChatParticipants)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire840649cfBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputPrivacyValueAllowChatParticipants, error) {
	value := new(tg.InputPrivacyValueAllowChatParticipants)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWire869d758f(profile LayerProfile, value *tg.SecureValueError, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeSecureValueError, WireID: 0x869d758f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWire869d758fBare(profile LayerProfile, value *tg.SecureValueError, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSecureValueError, WireID: 0x869d758f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire869d758fBareBody(profile LayerProfile, value *tg.SecureValueError, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire869d758fBare(profile, value, b, state)
}

func layerDecodeWire869d758f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SecureValueError, error) {
	value := new(tg.SecureValueError)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWire869d758fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SecureValueError, error) {
	value := new(tg.SecureValueError)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWirea477288f(profile LayerProfile, value *tg.UpdateGroupCallChainBlocks, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateGroupCallChainBlocks, WireID: 0xa477288f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWirea477288fBare(profile LayerProfile, value *tg.UpdateGroupCallChainBlocks, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateGroupCallChainBlocks, WireID: 0xa477288f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea477288fBareBody(profile LayerProfile, value *tg.UpdateGroupCallChainBlocks, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea477288fBare(profile, value, b, state)
}

func layerDecodeWirea477288f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateGroupCallChainBlocks, error) {
	value := new(tg.UpdateGroupCallChainBlocks)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWirea477288fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateGroupCallChainBlocks, error) {
	value := new(tg.UpdateGroupCallChainBlocks)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWirea99fca4f(profile LayerProfile, value *tg.UploadCDNFile, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUploadCDNFile, WireID: 0xa99fca4f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWirea99fca4fBare(profile LayerProfile, value *tg.UploadCDNFile, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUploadCDNFile, WireID: 0xa99fca4f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea99fca4fBareBody(profile LayerProfile, value *tg.UploadCDNFile, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea99fca4fBare(profile, value, b, state)
}

func layerDecodeWirea99fca4f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UploadCDNFile, error) {
	value := new(tg.UploadCDNFile)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWirea99fca4fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UploadCDNFile, error) {
	value := new(tg.UploadCDNFile)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWireb54b5acf(profile LayerProfile, value *tg.PeerColor, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePeerColor, WireID: 0xb54b5acf, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWireb54b5acfBare(profile LayerProfile, value *tg.PeerColor, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePeerColor, WireID: 0xb54b5acf, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb54b5acfBareBody(profile LayerProfile, value *tg.PeerColor, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb54b5acfBare(profile, value, b, state)
}

func layerDecodeWireb54b5acf(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PeerColor, error) {
	value := new(tg.PeerColor)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWireb54b5acfBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PeerColor, error) {
	value := new(tg.PeerColor)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWireb89bfccf(profile LayerProfile, value *tg.FactCheck, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeFactCheck, WireID: 0xb89bfccf, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWireb89bfccfBare(profile LayerProfile, value *tg.FactCheck, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeFactCheck, WireID: 0xb89bfccf, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb89bfccfBareBody(profile LayerProfile, value *tg.FactCheck, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb89bfccfBare(profile, value, b, state)
}

func layerDecodeWireb89bfccf(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.FactCheck, error) {
	value := new(tg.FactCheck)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWireb89bfccfBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.FactCheck, error) {
	value := new(tg.FactCheck)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWireb98886cf(profile LayerProfile, value *tg.InputUserEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputUserEmpty, WireID: 0xb98886cf, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWireb98886cfBare(profile LayerProfile, value *tg.InputUserEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputUserEmpty, WireID: 0xb98886cf, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb98886cfBareBody(profile LayerProfile, value *tg.InputUserEmpty, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb98886cfBare(profile, value, b, state)
}

func layerDecodeWireb98886cf(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputUserEmpty, error) {
	value := new(tg.InputUserEmpty)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWireb98886cfBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputUserEmpty, error) {
	value := new(tg.InputUserEmpty)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWirec10eb2cf(profile LayerProfile, value *tg.InputPaymentCredentialsSaved, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputPaymentCredentialsSaved, WireID: 0xc10eb2cf, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWirec10eb2cfBare(profile LayerProfile, value *tg.InputPaymentCredentialsSaved, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputPaymentCredentialsSaved, WireID: 0xc10eb2cf, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirec10eb2cfBareBody(profile LayerProfile, value *tg.InputPaymentCredentialsSaved, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirec10eb2cfBare(profile, value, b, state)
}

func layerDecodeWirec10eb2cf(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputPaymentCredentialsSaved, error) {
	value := new(tg.InputPaymentCredentialsSaved)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWirec10eb2cfBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputPaymentCredentialsSaved, error) {
	value := new(tg.InputPaymentCredentialsSaved)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWired8aa840f(profile LayerProfile, value *tg.InputGroupCall, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeInputGroupCall, WireID: 0xd8aa840f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWired8aa840fBare(profile LayerProfile, value *tg.InputGroupCall, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputGroupCall, WireID: 0xd8aa840f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWired8aa840fBareBody(profile LayerProfile, value *tg.InputGroupCall, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWired8aa840fBare(profile, value, b, state)
}

func layerDecodeWired8aa840f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputGroupCall, error) {
	value := new(tg.InputGroupCall)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWired8aa840fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputGroupCall, error) {
	value := new(tg.InputGroupCall)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWiredc3d824f(profile LayerProfile, value *tg.TextEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeTextEmpty, WireID: 0xdc3d824f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWiredc3d824fBare(profile LayerProfile, value *tg.TextEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeTextEmpty, WireID: 0xdc3d824f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiredc3d824fBareBody(profile LayerProfile, value *tg.TextEmpty, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiredc3d824fBare(profile, value, b, state)
}

func layerDecodeWiredc3d824f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextEmpty, error) {
	value := new(tg.TextEmpty)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWiredc3d824fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.TextEmpty, error) {
	value := new(tg.TextEmpty)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWiredc8b44cf(profile LayerProfile, value *tg.SMSJobsEligibleToJoin, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeSMSJobsEligibleToJoin, WireID: 0xdc8b44cf, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWiredc8b44cfBare(profile LayerProfile, value *tg.SMSJobsEligibleToJoin, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSMSJobsEligibleToJoin, WireID: 0xdc8b44cf, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiredc8b44cfBareBody(profile LayerProfile, value *tg.SMSJobsEligibleToJoin, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiredc8b44cfBare(profile, value, b, state)
}

func layerDecodeWiredc8b44cf(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SMSJobsEligibleToJoin, error) {
	value := new(tg.SMSJobsEligibleToJoin)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWiredc8b44cfBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SMSJobsEligibleToJoin, error) {
	value := new(tg.SMSJobsEligibleToJoin)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWireeb983f8f(profile LayerProfile, value *tg.PaymentsCheckedGiftCode, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, WireID: 0xeb983f8f, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, WireID: 0xeb983f8f, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0xeb983f8f)
		return layerEncodeWireeb983f8fBareBody(profile, value, b, state)

	})
}

func layerEncodeWireeb983f8fBare(profile LayerProfile, value *tg.PaymentsCheckedGiftCode, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, WireID: 0xeb983f8f, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWireeb983f8fBareBody(profile, value, b, state)
	})
}

func layerEncodeWireeb983f8fBareBody(profile LayerProfile, value *tg.PaymentsCheckedGiftCode, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			if value.Flags.Has(4) && value.FromID == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, Reason: "malformed canonical value: explicit flag has nil interface field from_id"}
			}
			layerEncoded6 := &bin.Buffer{}
			layerPresent8 := (value.Flags.Has(4) || value.FromID != nil)
			if layerPresent8 {
				layerErr7 := func() error {
					if err := layerEncodeClassPeerBody(profile, value.FromID, layerEncoded6, state); err != nil {
						return fmt.Errorf("encode prepared field from_id: %w", err)
					}
					return nil
				}()
				if layerErr7 != nil {
					if IsLayerProjectionDrop(layerErr7) {
						layerPresent8 = false
						layerEncoded6.Reset()
					} else {
						return fmt.Errorf("encode optional field from_id: %w", layerErr7)
					}
				}
			}
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.ToID != 0 {
				wireFlags0.Set(0)
			}
			if value.Flags.Has(1) || value.UsedDate != 0 {
				wireFlags0.Set(1)
			}
			if value.Flags.Has(2) || value.ViaGiveaway {
				wireFlags0.Set(2)
			}
			if value.Flags.Has(3) || value.GiveawayMsgID != 0 {
				wireFlags0.Set(3)
			}
			if layerPresent8 {
				wireFlags0.Set(4)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if wireFlags0.Has(4) {
				b.Buf = append(b.Buf, layerEncoded6.Buf...)
			}
			if wireFlags0.Has(3) {
				b.PutInt(value.GiveawayMsgID)
			}
			if wireFlags0.Has(0) {
				b.PutLong(value.ToID)
			}
			b.PutInt(value.Date)
			b.PutInt(value.Days)
			if wireFlags0.Has(1) {
				b.PutInt(value.UsedDate)
			}
			if len(value.Chats) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart11 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset12 := layerVectorStart11 + 4
			layerLength9 := 0
			for layerIndex10 := range value.Chats {
				layerItemStart13 := len(b.Buf)
				layerErr14 := func() error {
					if err := layerEncodeClassChatBody(profile, value.Chats[layerIndex10], b, state); err != nil {
						return fmt.Errorf("encode field chats element: %w", err)
					}
					return nil
				}()
				if layerErr14 != nil {
					b.Buf = b.Buf[:layerItemStart13]
					if IsLayerProjectionDrop(layerErr14) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart11]
					return fmt.Errorf("encode field chats: %w", layerErr14)
				}
				layerLength9++
			}
			b.Buf[layerCountOffset12] = byte(layerLength9)
			b.Buf[layerCountOffset12+1] = byte(layerLength9 >> 8)
			b.Buf[layerCountOffset12+2] = byte(layerLength9 >> 16)
			b.Buf[layerCountOffset12+3] = byte(layerLength9 >> 24)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart17 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset18 := layerVectorStart17 + 4
			layerLength15 := 0
			for layerIndex16 := range value.Users {
				layerItemStart19 := len(b.Buf)
				layerErr20 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex16], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr20 != nil {
					b.Buf = b.Buf[:layerItemStart19]
					if IsLayerProjectionDrop(layerErr20) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart17]
					return fmt.Errorf("encode field users: %w", layerErr20)
				}
				layerLength15++
			}
			b.Buf[layerCountOffset18] = byte(layerLength15)
			b.Buf[layerCountOffset18+1] = byte(layerLength15 >> 8)
			b.Buf[layerCountOffset18+2] = byte(layerLength15 >> 16)
			b.Buf[layerCountOffset18+3] = byte(layerLength15 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, WireID: 0xeb983f8f, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireeb983f8f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentsCheckedGiftCode, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, WireID: 0xeb983f8f, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xeb983f8f); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xeb983f8f: %w", err)
	}
	return layerDecodeWireeb983f8fBare(profile, b, state)

}

func layerDecodeWireeb983f8fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentsCheckedGiftCode, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PaymentsCheckedGiftCode)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded21 := wireFlags0.Has(2)
			var layerDecoded22 tg.PeerClass
			if wireFlags0.Has(4) {
				layerClass23, err := layerDecodeClassPeer(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field from_id: %w", err)
				}
				layerDecoded22 = layerClass23
			}
			var layerDecoded24 int
			if wireFlags0.Has(3) {
				layerPrimitive25, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field giveaway_msg_id: %w", err)
				}
				layerDecoded24 = layerPrimitive25
			}
			var layerDecoded26 int64
			if wireFlags0.Has(0) {
				layerPrimitive27, err := b.Long()
				if err != nil {
					return nil, fmt.Errorf("decode field to_id: %w", err)
				}
				layerDecoded26 = layerPrimitive27
			}
			var layerDecoded28 int
			layerPrimitive29, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field date: %w", err)
			}
			layerDecoded28 = layerPrimitive29
			var layerDecoded30 int
			layerPrimitive31, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field days: %w", err)
			}
			layerDecoded30 = layerPrimitive31
			var layerDecoded32 int
			if wireFlags0.Has(1) {
				layerPrimitive33, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field used_date: %w", err)
				}
				layerDecoded32 = layerPrimitive33
			}
			var layerDecoded34 []tg.ChatClass
			layerDecodeState35, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field chats vector depth: %w", err)
			}
			layerLength36, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState35)
			if err != nil {
				return nil, fmt.Errorf("decode field chats: %w", err)
			}
			var layerVector37 []tg.ChatClass
			if layerLength36 > 0 {
				capacity := layerLength36
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector37 = make([]tg.ChatClass, 0, capacity)
			}
			for index := 0; index < layerLength36; index++ {
				var element tg.ChatClass
				layerClass38, err := layerDecodeClassChat(profile, b, &layerDecodeState35)
				if err != nil {
					return nil, fmt.Errorf("decode field chats element: %w", err)
				}
				element = layerClass38
				layerVector37 = append(layerVector37, element)
			}
			layerDecoded34 = layerVector37
			var layerDecoded39 []tg.UserClass
			layerDecodeState40, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength41, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState40)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector42 []tg.UserClass
			if layerLength41 > 0 {
				capacity := layerLength41
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector42 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength41; index++ {
				var element tg.UserClass
				layerClass43, err := layerDecodeClassUser(profile, b, &layerDecodeState40)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass43
				layerVector42 = append(layerVector42, element)
			}
			layerDecoded39 = layerVector42
			if wireFlags0.Has(2) {
				value.Flags.Set(2)
				value.ViaGiveaway = layerDecoded21
			}
			if wireFlags0.Has(4) {
				value.Flags.Set(4)
				value.FromID = layerDecoded22
			}
			if wireFlags0.Has(3) {
				value.Flags.Set(3)
				value.GiveawayMsgID = layerDecoded24
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.ToID = layerDecoded26
			}
			if true {
				value.Date = layerDecoded28
			}
			if true {
				value.Days = layerDecoded30
			}
			if wireFlags0.Has(1) {
				value.Flags.Set(1)
				value.UsedDate = layerDecoded32
			}
			if true {
				value.Chats = layerDecoded34
			}
			if true {
				value.Users = layerDecoded39
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckedGiftCode, WireID: 0xeb983f8f, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire. The allocation-free scanner has already
// proven the complete transitive wire graph, so no historical field program
// is emitted here.
func layerEncodeWirefe41b34f(profile LayerProfile, value *tg.GlobalPrivacySettings, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeGlobalPrivacySettings, WireID: 0xfe41b34f, Reason: "nil canonical value"}
	}
	return value.Encode(b)
}
func layerEncodeWirefe41b34fBare(profile LayerProfile, value *tg.GlobalPrivacySettings, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeGlobalPrivacySettings, WireID: 0xfe41b34f, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirefe41b34fBareBody(profile LayerProfile, value *tg.GlobalPrivacySettings, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirefe41b34fBare(profile, value, b, state)
}

func layerDecodeWirefe41b34f(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.GlobalPrivacySettings, error) {
	value := new(tg.GlobalPrivacySettings)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
func layerDecodeWirefe41b34fBare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.GlobalPrivacySettings, error) {
	value := new(tg.GlobalPrivacySettings)
	if err := value.DecodeBare(b); err != nil {
		return nil, err
	}
	return value, nil
}
