// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire283bd312Bare(profile LayerProfile, value *tg.UpdateBotPurchasedPaidMedia, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateBotPurchasedPaidMedia, WireID: 0x283bd312, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire283bd312BareBody(profile LayerProfile, value *tg.UpdateBotPurchasedPaidMedia, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire283bd312Bare(profile, value, b, state)
}
func layerDecodeWire283bd312(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateBotPurchasedPaidMedia, error) {
	value := new(tg.UpdateBotPurchasedPaidMedia)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire2a862092BareBody(profile LayerProfile, value *tg.MessagesUploadImportedMediaRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassInputPeerBody(profile, value.Peer, b, state); err != nil {
				return fmt.Errorf("encode field peer: %w", err)
			}
			b.PutLong(value.ImportID)
			if err := b.PutStringChecked(value.FileName); err != nil {
				return fmt.Errorf("encode field file_name: %w", err)
			}
			if err := layerEncodeClassInputMediaBody(profile, value.Media, b, state); err != nil {
				return fmt.Errorf("encode field media: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesUploadImportedMedia, WireID: 0x2a862092, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire2a862092(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesUploadImportedMediaRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodMessagesUploadImportedMedia, WireID: 0x2a862092, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x2a862092); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x2a862092: %w", err)
	}
	return layerDecodeWire2a862092Bare(profile, b, state)

}

func layerDecodeWire2a862092Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesUploadImportedMediaRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesUploadImportedMediaRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded3 tg.InputPeerClass
			layerClass4, err := layerDecodeClassInputPeer(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field peer: %w", err)
			}
			layerDecoded3 = layerClass4
			var layerDecoded5 int64
			layerPrimitive6, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field import_id: %w", err)
			}
			layerDecoded5 = layerPrimitive6
			var layerDecoded7 string
			layerPrimitive8, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field file_name: %w", err)
			}
			layerDecoded7 = layerPrimitive8
			var layerDecoded9 tg.InputMediaClass
			layerClass10, err := layerDecodeClassInputMedia(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field media: %w", err)
			}
			layerDecoded9 = layerClass10
			if true {
				value.Peer = layerDecoded3
			}
			if true {
				value.ImportID = layerDecoded5
			}
			if true {
				value.FileName = layerDecoded7
			}
			if true {
				value.Media = layerDecoded9
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesUploadImportedMedia, WireID: 0x2a862092, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire31bb5d52Bare(profile LayerProfile, value *tg.ChannelAdminLogEventActionChangeWallpaper, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChannelAdminLogEventActionChangeWallpaper, WireID: 0x31bb5d52, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire31bb5d52BareBody(profile LayerProfile, value *tg.ChannelAdminLogEventActionChangeWallpaper, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire31bb5d52Bare(profile, value, b, state)
}
func layerDecodeWire31bb5d52(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChannelAdminLogEventActionChangeWallpaper, error) {
	value := new(tg.ChannelAdminLogEventActionChangeWallpaper)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire50f5c392Bare(profile LayerProfile, value *tg.InputMessagesFilterVoice, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputMessagesFilterVoice, WireID: 0x50f5c392, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire50f5c392BareBody(profile LayerProfile, value *tg.InputMessagesFilterVoice, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire50f5c392Bare(profile, value, b, state)
}
func layerDecodeWire50f5c392(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputMessagesFilterVoice, error) {
	value := new(tg.InputMessagesFilterVoice)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire5c467992Bare(profile LayerProfile, value *tg.InputNotifyForumTopic, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputNotifyForumTopic, WireID: 0x5c467992, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire5c467992BareBody(profile LayerProfile, value *tg.InputNotifyForumTopic, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire5c467992Bare(profile, value, b, state)
}
func layerDecodeWire5c467992(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputNotifyForumTopic, error) {
	value := new(tg.InputNotifyForumTopic)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire60682812Bare(profile LayerProfile, value *tg.StarsTransactionPeerAds, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStarsTransactionPeerAds, WireID: 0x60682812, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire60682812BareBody(profile LayerProfile, value *tg.StarsTransactionPeerAds, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire60682812Bare(profile, value, b, state)
}
func layerDecodeWire60682812(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StarsTransactionPeerAds, error) {
	value := new(tg.StarsTransactionPeerAds)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire6410a5d2Bare(profile LayerProfile, value *tg.StickerSetCovered, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStickerSetCovered, WireID: 0x6410a5d2, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire6410a5d2BareBody(profile LayerProfile, value *tg.StickerSetCovered, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire6410a5d2Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire683b2c52Bare(profile LayerProfile, value *tg.UpdatePinnedForumTopic, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdatePinnedForumTopic, WireID: 0x683b2c52, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire683b2c52BareBody(profile LayerProfile, value *tg.UpdatePinnedForumTopic, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire683b2c52Bare(profile, value, b, state)
}
func layerDecodeWire683b2c52(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePinnedForumTopic, error) {
	value := new(tg.UpdatePinnedForumTopic)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire691e9052Bare(profile LayerProfile, value *tg.UpdateInlineBotCallbackQuery, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateInlineBotCallbackQuery, WireID: 0x691e9052, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire691e9052BareBody(profile LayerProfile, value *tg.UpdateInlineBotCallbackQuery, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire691e9052Bare(profile, value, b, state)
}
func layerDecodeWire691e9052(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateInlineBotCallbackQuery, error) {
	value := new(tg.UpdateInlineBotCallbackQuery)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire8af09dd2Bare(profile LayerProfile, value *tg.MessagesFoundStickerSets, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesFoundStickerSets, WireID: 0x8af09dd2, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire8af09dd2BareBody(profile LayerProfile, value *tg.MessagesFoundStickerSets, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire8af09dd2Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire95d2ac92Bare(profile LayerProfile, value *tg.MessageActionChannelCreate, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionChannelCreate, WireID: 0x95d2ac92, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire95d2ac92BareBody(profile LayerProfile, value *tg.MessageActionChannelCreate, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire95d2ac92Bare(profile, value, b, state)
}
func layerDecodeWire95d2ac92(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionChannelCreate, error) {
	value := new(tg.MessageActionChannelCreate)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire9852d6d2Bare(profile LayerProfile, value *tg.BotCommand, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeBotCommand, WireID: 0x9852d6d2, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire9852d6d2BareBody(profile LayerProfile, value *tg.BotCommand, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire9852d6d2Bare(profile, value, b, state)
}
func layerDecodeWire9852d6d2(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.BotCommand, error) {
	value := new(tg.BotCommand)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirea6f8f452Bare(profile LayerProfile, value *tg.WebAuthorization, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeWebAuthorization, WireID: 0xa6f8f452, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea6f8f452BareBody(profile LayerProfile, value *tg.WebAuthorization, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea6f8f452Bare(profile, value, b, state)
}
func layerDecodeWirea6f8f452(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.WebAuthorization, error) {
	value := new(tg.WebAuthorization)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireb2da71d2Bare(profile LayerProfile, value *tg.RecentMeURLChat, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeRecentMeURLChat, WireID: 0xb2da71d2, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb2da71d2BareBody(profile LayerProfile, value *tg.RecentMeURLChat, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb2da71d2Bare(profile, value, b, state)
}
func layerDecodeWireb2da71d2(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.RecentMeURLChat, error) {
	value := new(tg.RecentMeURLChat)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireb74ba9d2Bare(profile LayerProfile, value *tg.ContactsContactsNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeContactsContactsNotModified, WireID: 0xb74ba9d2, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb74ba9d2BareBody(profile LayerProfile, value *tg.ContactsContactsNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb74ba9d2Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirec32d5b12Bare(profile LayerProfile, value *tg.UpdateDeleteChannelMessages, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateDeleteChannelMessages, WireID: 0xc32d5b12, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirec32d5b12BareBody(profile LayerProfile, value *tg.UpdateDeleteChannelMessages, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirec32d5b12Bare(profile, value, b, state)
}
func layerDecodeWirec32d5b12(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateDeleteChannelMessages, error) {
	value := new(tg.UpdateDeleteChannelMessages)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree1037f92Bare(profile LayerProfile, value *tg.MessageActionChatMigrateTo, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionChatMigrateTo, WireID: 0xe1037f92, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree1037f92BareBody(profile LayerProfile, value *tg.MessageActionChatMigrateTo, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree1037f92Bare(profile, value, b, state)
}
func layerDecodeWiree1037f92(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionChatMigrateTo, error) {
	value := new(tg.MessageActionChatMigrateTo)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree7e82e12Bare(profile LayerProfile, value *tg.PendingSuggestion, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePendingSuggestion, WireID: 0xe7e82e12, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree7e82e12BareBody(profile LayerProfile, value *tg.PendingSuggestion, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree7e82e12Bare(profile, value, b, state)
}
func layerDecodeWiree7e82e12(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PendingSuggestion, error) {
	value := new(tg.PendingSuggestion)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree8625e92Bare(profile LayerProfile, value *tg.InputInvoiceStarGift, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputInvoiceStarGift, WireID: 0xe8625e92, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree8625e92BareBody(profile LayerProfile, value *tg.InputInvoiceStarGift, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree8625e92Bare(profile, value, b, state)
}
func layerDecodeWiree8625e92(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputInvoiceStarGift, error) {
	value := new(tg.InputInvoiceStarGift)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireebe07752Bare(profile LayerProfile, value *tg.UpdatePeerBlocked, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdatePeerBlocked, WireID: 0xebe07752, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireebe07752BareBody(profile LayerProfile, value *tg.UpdatePeerBlocked, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireebe07752Bare(profile, value, b, state)
}
func layerDecodeWireebe07752(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePeerBlocked, error) {
	value := new(tg.UpdatePeerBlocked)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiref92424d2Bare(profile LayerProfile, value *tg.ChannelAdminLogEventActionParticipantMute, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeChannelAdminLogEventActionParticipantMute, WireID: 0xf92424d2, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiref92424d2BareBody(profile LayerProfile, value *tg.ChannelAdminLogEventActionParticipantMute, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiref92424d2Bare(profile, value, b, state)
}
func layerDecodeWiref92424d2(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.ChannelAdminLogEventActionParticipantMute, error) {
	value := new(tg.ChannelAdminLogEventActionParticipantMute)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirefe333952Bare(profile LayerProfile, value *tg.StarGiftAuctionStateNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStarGiftAuctionStateNotModified, WireID: 0xfe333952, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirefe333952BareBody(profile LayerProfile, value *tg.StarGiftAuctionStateNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirefe333952Bare(profile, value, b, state)
}
func layerDecodeWirefe333952(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StarGiftAuctionStateNotModified, error) {
	value := new(tg.StarGiftAuctionStateNotModified)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
