// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire027477b4Bare(profile LayerProfile, value *tg.SecureRequiredTypeOneOf, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSecureRequiredTypeOneOf, WireID: 0x027477b4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire027477b4BareBody(profile LayerProfile, value *tg.SecureRequiredTypeOneOf, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire027477b4Bare(profile, value, b, state)
}
func layerDecodeWire027477b4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SecureRequiredTypeOneOf, error) {
	value := new(tg.SecureRequiredTypeOneOf)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire1bf89d74(profile LayerProfile, value *tg.MessagesSendMultiMediaRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, WireID: 0x1bf89d74, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, WireID: 0x1bf89d74, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0x1bf89d74)
		return layerEncodeWire1bf89d74BareBody(profile, value, b, state)

	})
}

func layerEncodeWire1bf89d74Bare(profile LayerProfile, value *tg.MessagesSendMultiMediaRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, WireID: 0x1bf89d74, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire1bf89d74BareBody(profile, value, b, state)
	})
}

func layerEncodeWire1bf89d74BareBody(profile LayerProfile, value *tg.MessagesSendMultiMediaRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			if value.Flags.Has(0) && value.ReplyTo == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, Reason: "malformed canonical value: explicit flag has nil interface field reply_to"}
			}
			if value.Flags.Has(13) && value.SendAs == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, Reason: "malformed canonical value: explicit flag has nil interface field send_as"}
			}
			if value.Flags.Has(17) && value.QuickReplyShortcut == nil {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, Reason: "malformed canonical value: explicit flag has nil interface field quick_reply_shortcut"}
			}
			layerEncoded7 := &bin.Buffer{}
			layerPresent9 := (value.Flags.Has(0) || value.ReplyTo != nil)
			if layerPresent9 {
				layerErr8 := func() error {
					if err := layerEncodeClassInputReplyToBody(profile, value.ReplyTo, layerEncoded7, state); err != nil {
						return fmt.Errorf("encode prepared field reply_to: %w", err)
					}
					return nil
				}()
				if layerErr8 != nil {
					if IsLayerProjectionDrop(layerErr8) {
						layerPresent9 = false
						layerEncoded7.Reset()
					} else {
						return fmt.Errorf("encode optional field reply_to: %w", layerErr8)
					}
				}
			}
			layerEncoded10 := &bin.Buffer{}
			layerPresent12 := (value.Flags.Has(13) || value.SendAs != nil)
			if layerPresent12 {
				layerErr11 := func() error {
					if err := layerEncodeClassInputPeerBody(profile, value.SendAs, layerEncoded10, state); err != nil {
						return fmt.Errorf("encode prepared field send_as: %w", err)
					}
					return nil
				}()
				if layerErr11 != nil {
					if IsLayerProjectionDrop(layerErr11) {
						layerPresent12 = false
						layerEncoded10.Reset()
					} else {
						return fmt.Errorf("encode optional field send_as: %w", layerErr11)
					}
				}
			}
			layerEncoded13 := &bin.Buffer{}
			layerPresent15 := (value.Flags.Has(17) || value.QuickReplyShortcut != nil)
			if layerPresent15 {
				layerErr14 := func() error {
					if err := layerEncodeClassInputQuickReplyShortcutBody(profile, value.QuickReplyShortcut, layerEncoded13, state); err != nil {
						return fmt.Errorf("encode prepared field quick_reply_shortcut: %w", err)
					}
					return nil
				}()
				if layerErr14 != nil {
					if IsLayerProjectionDrop(layerErr14) {
						layerPresent15 = false
						layerEncoded13.Reset()
					} else {
						return fmt.Errorf("encode optional field quick_reply_shortcut: %w", layerErr14)
					}
				}
			}
			var wireFlags0 bin.Fields
			if layerPresent9 {
				wireFlags0.Set(0)
			}
			if value.Flags.Has(5) || value.Silent {
				wireFlags0.Set(5)
			}
			if value.Flags.Has(6) || value.Background {
				wireFlags0.Set(6)
			}
			if value.Flags.Has(7) || value.ClearDraft {
				wireFlags0.Set(7)
			}
			if value.Flags.Has(10) || value.ScheduleDate != 0 {
				wireFlags0.Set(10)
			}
			if layerPresent12 {
				wireFlags0.Set(13)
			}
			if value.Flags.Has(14) || value.Noforwards {
				wireFlags0.Set(14)
			}
			if value.Flags.Has(15) || value.UpdateStickersetsOrder {
				wireFlags0.Set(15)
			}
			if value.Flags.Has(16) || value.InvertMedia {
				wireFlags0.Set(16)
			}
			if layerPresent15 {
				wireFlags0.Set(17)
			}
			if value.Flags.Has(18) || value.Effect != 0 {
				wireFlags0.Set(18)
			}
			if value.Flags.Has(19) || value.AllowPaidFloodskip {
				wireFlags0.Set(19)
			}
			if value.Flags.Has(21) || value.AllowPaidStars != 0 {
				wireFlags0.Set(21)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if err := layerEncodeClassInputPeerBody(profile, value.Peer, b, state); err != nil {
				return fmt.Errorf("encode field peer: %w", err)
			}
			if wireFlags0.Has(0) {
				b.Buf = append(b.Buf, layerEncoded7.Buf...)
			}
			if len(value.MultiMedia) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart18 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset19 := layerVectorStart18 + 4
			layerLength16 := 0
			for layerIndex17 := range value.MultiMedia {
				layerItemStart20 := len(b.Buf)
				layerErr21 := func() error {
					b.PutID(0x1cc6e91f)
					if err := layerEncodeWire1cc6e91fBareBody(profile, &(value.MultiMedia[layerIndex17]), b, state); err != nil {
						return fmt.Errorf("encode field multi_media element: %w", err)
					}
					return nil
				}()
				if layerErr21 != nil {
					b.Buf = b.Buf[:layerItemStart20]
					if IsLayerProjectionDrop(layerErr21) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart18]
					return fmt.Errorf("encode field multi_media: %w", layerErr21)
				}
				layerLength16++
			}
			b.Buf[layerCountOffset19] = byte(layerLength16)
			b.Buf[layerCountOffset19+1] = byte(layerLength16 >> 8)
			b.Buf[layerCountOffset19+2] = byte(layerLength16 >> 16)
			b.Buf[layerCountOffset19+3] = byte(layerLength16 >> 24)
			if wireFlags0.Has(10) {
				b.PutInt(value.ScheduleDate)
			}
			if wireFlags0.Has(13) {
				b.Buf = append(b.Buf, layerEncoded10.Buf...)
			}
			if wireFlags0.Has(17) {
				b.Buf = append(b.Buf, layerEncoded13.Buf...)
			}
			if wireFlags0.Has(18) {
				b.PutLong(value.Effect)
			}
			if wireFlags0.Has(21) {
				b.PutLong(value.AllowPaidStars)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, WireID: 0x1bf89d74, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire1bf89d74(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSendMultiMediaRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, WireID: 0x1bf89d74, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x1bf89d74); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x1bf89d74: %w", err)
	}
	return layerDecodeWire1bf89d74Bare(profile, b, state)

}

func layerDecodeWire1bf89d74Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSendMultiMediaRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesSendMultiMediaRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded22 := wireFlags0.Has(5)
			layerDecoded23 := wireFlags0.Has(6)
			layerDecoded24 := wireFlags0.Has(7)
			layerDecoded25 := wireFlags0.Has(14)
			layerDecoded26 := wireFlags0.Has(15)
			layerDecoded27 := wireFlags0.Has(16)
			layerDecoded28 := wireFlags0.Has(19)
			var layerDecoded29 tg.InputPeerClass
			layerClass30, err := layerDecodeClassInputPeer(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field peer: %w", err)
			}
			layerDecoded29 = layerClass30
			var layerDecoded31 tg.InputReplyToClass
			if wireFlags0.Has(0) {
				layerClass32, err := layerDecodeClassInputReplyTo(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field reply_to: %w", err)
				}
				layerDecoded31 = layerClass32
			}
			var layerDecoded33 []tg.InputSingleMedia
			layerDecodeState34, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field multi_media vector depth: %w", err)
			}
			layerLength35, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState34)
			if err != nil {
				return nil, fmt.Errorf("decode field multi_media: %w", err)
			}
			var layerVector36 []tg.InputSingleMedia
			if layerLength35 > 0 {
				capacity := layerLength35
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector36 = make([]tg.InputSingleMedia, 0, capacity)
			}
			for index := 0; index < layerLength35; index++ {
				var element tg.InputSingleMedia
				layerConcrete37, err := layerDecodeWire1cc6e91f(profile, b, &layerDecodeState34)
				if err != nil {
					return nil, fmt.Errorf("decode field multi_media element: %w", err)
				}
				element = *layerConcrete37
				layerVector36 = append(layerVector36, element)
			}
			layerDecoded33 = layerVector36
			var layerDecoded38 int
			if wireFlags0.Has(10) {
				layerPrimitive39, err := b.Int()
				if err != nil {
					return nil, fmt.Errorf("decode field schedule_date: %w", err)
				}
				layerDecoded38 = layerPrimitive39
			}
			var layerDecoded40 tg.InputPeerClass
			if wireFlags0.Has(13) {
				layerClass41, err := layerDecodeClassInputPeer(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field send_as: %w", err)
				}
				layerDecoded40 = layerClass41
			}
			var layerDecoded42 tg.InputQuickReplyShortcutClass
			if wireFlags0.Has(17) {
				layerClass43, err := layerDecodeClassInputQuickReplyShortcut(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode field quick_reply_shortcut: %w", err)
				}
				layerDecoded42 = layerClass43
			}
			var layerDecoded44 int64
			if wireFlags0.Has(18) {
				layerPrimitive45, err := b.Long()
				if err != nil {
					return nil, fmt.Errorf("decode field effect: %w", err)
				}
				layerDecoded44 = layerPrimitive45
			}
			var layerDecoded46 int64
			if wireFlags0.Has(21) {
				layerPrimitive47, err := b.Long()
				if err != nil {
					return nil, fmt.Errorf("decode field allow_paid_stars: %w", err)
				}
				layerDecoded46 = layerPrimitive47
			}
			if wireFlags0.Has(5) {
				value.Flags.Set(5)
				value.Silent = layerDecoded22
			}
			if wireFlags0.Has(6) {
				value.Flags.Set(6)
				value.Background = layerDecoded23
			}
			if wireFlags0.Has(7) {
				value.Flags.Set(7)
				value.ClearDraft = layerDecoded24
			}
			if wireFlags0.Has(14) {
				value.Flags.Set(14)
				value.Noforwards = layerDecoded25
			}
			if wireFlags0.Has(15) {
				value.Flags.Set(15)
				value.UpdateStickersetsOrder = layerDecoded26
			}
			if wireFlags0.Has(16) {
				value.Flags.Set(16)
				value.InvertMedia = layerDecoded27
			}
			if wireFlags0.Has(19) {
				value.Flags.Set(19)
				value.AllowPaidFloodskip = layerDecoded28
			}
			if true {
				value.Peer = layerDecoded29
			}
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.ReplyTo = layerDecoded31
			}
			if true {
				value.MultiMedia = layerDecoded33
			}
			if wireFlags0.Has(10) {
				value.Flags.Set(10)
				value.ScheduleDate = layerDecoded38
			}
			if wireFlags0.Has(13) {
				value.Flags.Set(13)
				value.SendAs = layerDecoded40
			}
			if wireFlags0.Has(17) {
				value.Flags.Set(17)
				value.QuickReplyShortcut = layerDecoded42
			}
			if wireFlags0.Has(18) {
				value.Flags.Set(18)
				value.Effect = layerDecoded44
			}
			if wireFlags0.Has(21) {
				value.Flags.Set(21)
				value.AllowPaidStars = layerDecoded46
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSendMultiMedia, WireID: 0x1bf89d74, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerEncodeWire315a4974(profile LayerProfile, value *tg.UsersUsersSlice, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUsersUsersSlice, WireID: 0x315a4974, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUsersUsersSlice, WireID: 0x315a4974, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0x315a4974)
		return layerEncodeWire315a4974BareBody(profile, value, b, state)

	})
}

func layerEncodeWire315a4974Bare(profile LayerProfile, value *tg.UsersUsersSlice, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUsersUsersSlice, WireID: 0x315a4974, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire315a4974BareBody(profile, value, b, state)
	})
}

func layerEncodeWire315a4974BareBody(profile LayerProfile, value *tg.UsersUsersSlice, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			b.PutInt(value.Count)
			if len(value.Users) > layerCodecMaxVectorElements {
				return &LayerCodecError{Operation: "encode", Profile: profile, Reason: "vector length exceeds generated limit"}
			}
			layerVectorStart5 := len(b.Buf)
			b.PutVectorHeader(0)
			layerCountOffset6 := layerVectorStart5 + 4
			layerLength3 := 0
			for layerIndex4 := range value.Users {
				layerItemStart7 := len(b.Buf)
				layerErr8 := func() error {
					if err := layerEncodeClassUserBody(profile, value.Users[layerIndex4], b, state); err != nil {
						return fmt.Errorf("encode field users element: %w", err)
					}
					return nil
				}()
				if layerErr8 != nil {
					b.Buf = b.Buf[:layerItemStart7]
					if IsLayerProjectionDrop(layerErr8) {
						continue
					}
					b.Buf = b.Buf[:layerVectorStart5]
					return fmt.Errorf("encode field users: %w", layerErr8)
				}
				layerLength3++
			}
			b.Buf[layerCountOffset6] = byte(layerLength3)
			b.Buf[layerCountOffset6+1] = byte(layerLength3 >> 8)
			b.Buf[layerCountOffset6+2] = byte(layerLength3 >> 16)
			b.Buf[layerCountOffset6+3] = byte(layerLength3 >> 24)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUsersUsersSlice, WireID: 0x315a4974, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire315a4974(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UsersUsersSlice, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeUsersUsersSlice, WireID: 0x315a4974, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x315a4974); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x315a4974: %w", err)
	}
	return layerDecodeWire315a4974Bare(profile, b, state)

}

func layerDecodeWire315a4974Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UsersUsersSlice, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.UsersUsersSlice)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var layerDecoded9 int
			layerPrimitive10, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode field count: %w", err)
			}
			layerDecoded9 = layerPrimitive10
			var layerDecoded11 []tg.UserClass
			layerDecodeState12, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength13, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState12)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector14 []tg.UserClass
			if layerLength13 > 0 {
				capacity := layerLength13
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector14 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength13; index++ {
				var element tg.UserClass
				layerClass15, err := layerDecodeClassUser(profile, b, &layerDecodeState12)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass15
				layerVector14 = append(layerVector14, element)
			}
			layerDecoded11 = layerVector14
			if true {
				value.Count = layerDecoded9
			}
			if true {
				value.Users = layerDecoded11
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeUsersUsersSlice, WireID: 0x315a4974, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire5060a3f4Bare(profile LayerProfile, value *tg.MessageActionSetChatWallPaper, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionSetChatWallPaper, WireID: 0x5060a3f4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire5060a3f4BareBody(profile LayerProfile, value *tg.MessageActionSetChatWallPaper, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire5060a3f4Bare(profile, value, b, state)
}
func layerDecodeWire5060a3f4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionSetChatWallPaper, error) {
	value := new(tg.MessageActionSetChatWallPaper)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire56e0d474Bare(profile LayerProfile, value *tg.MessageMediaGeo, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageMediaGeo, WireID: 0x56e0d474, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire56e0d474BareBody(profile LayerProfile, value *tg.MessageMediaGeo, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire56e0d474Bare(profile, value, b, state)
}
func layerDecodeWire56e0d474(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageMediaGeo, error) {
	value := new(tg.MessageMediaGeo)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire5dab1af4Bare(profile LayerProfile, value *tg.ExportedMessageLink, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeExportedMessageLink, WireID: 0x5dab1af4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire5dab1af4BareBody(profile LayerProfile, value *tg.ExportedMessageLink, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire5dab1af4Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire6010c534Bare(profile LayerProfile, value *tg.MessagesFoundStickersNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesFoundStickersNotModified, WireID: 0x6010c534, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire6010c534BareBody(profile LayerProfile, value *tg.MessagesFoundStickersNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire6010c534Bare(profile, value, b, state)
}
func layerDecodeWire6010c534(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesFoundStickersNotModified, error) {
	value := new(tg.MessagesFoundStickersNotModified)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire6f7863f4Bare(profile LayerProfile, value *tg.UpdateRecentReactions, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateRecentReactions, WireID: 0x6f7863f4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire6f7863f4BareBody(profile LayerProfile, value *tg.UpdateRecentReactions, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire6f7863f4Bare(profile, value, b, state)
}
func layerDecodeWire6f7863f4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateRecentReactions, error) {
	value := new(tg.UpdateRecentReactions)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire761e6af4Bare(profile LayerProfile, value *tg.MessageEntityBankCard, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageEntityBankCard, WireID: 0x761e6af4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire761e6af4BareBody(profile LayerProfile, value *tg.MessageEntityBankCard, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire761e6af4Bare(profile, value, b, state)
}
func layerDecodeWire761e6af4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageEntityBankCard, error) {
	value := new(tg.MessageEntityBankCard)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWire774bbdf4(profile LayerProfile, value *tg.MessagesChatInviteJoinResultWebView, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile226:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "policy layer-obligation/v1/required/cd9125a49bb4740f5108e644ca0a2323925d40a81a9df4f50e3bafc49ba167d7 rejects canonical-to-profile"}
		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "wire ID is unavailable in exact profile"}
		}

	})
}

func layerEncodeWire774bbdf4Bare(profile LayerProfile, value *tg.MessagesChatInviteJoinResultWebView, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWire774bbdf4BareBody(profile, value, b, state)
	})
}

func layerEncodeWire774bbdf4BareBody(profile LayerProfile, value *tg.MessagesChatInviteJoinResultWebView, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile226:
		{
			return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "policy layer-obligation/v1/required/cd9125a49bb4740f5108e644ca0a2323925d40a81a9df4f50e3bafc49ba167d7 rejects canonical-to-profile"}
		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire774bbdf4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesChatInviteJoinResultWebView, error) {
	switch profile {
	case LayerProfile226:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x774bbdf4); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x774bbdf4: %w", err)
	}
	return layerDecodeWire774bbdf4Bare(profile, b, state)

}

func layerDecodeWire774bbdf4Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesChatInviteJoinResultWebView, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesChatInviteJoinResultWebView)
	_ = value
	switch profile {
	case LayerProfile226:
		{
			var layerDecoded1 int64
			layerPrimitive2, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field bot_id: %w", err)
			}
			layerDecoded1 = layerPrimitive2
			var layerDecoded3 string
			layerPrimitive4, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field url: %w", err)
			}
			layerDecoded3 = layerPrimitive4
			var layerDecoded5 int64
			layerPrimitive6, err := b.Long()
			if err != nil {
				return nil, fmt.Errorf("decode field query_id: %w", err)
			}
			layerDecoded5 = layerPrimitive6
			var layerDecoded7 []tg.UserClass
			layerDecodeState8, err := layerCodecDescend(profile, "decode", state)
			if err != nil {
				return nil, fmt.Errorf("decode field users vector depth: %w", err)
			}
			layerLength9, err := layerDecodeVectorLength(profile, nil, b, true, &layerDecodeState8)
			if err != nil {
				return nil, fmt.Errorf("decode field users: %w", err)
			}
			var layerVector10 []tg.UserClass
			if layerLength9 > 0 {
				capacity := layerLength9
				if capacity > bin.PreallocateLimit {
					capacity = bin.PreallocateLimit
				}
				layerVector10 = make([]tg.UserClass, 0, capacity)
			}
			for index := 0; index < layerLength9; index++ {
				var element tg.UserClass
				layerClass11, err := layerDecodeClassUser(profile, b, &layerDecodeState8)
				if err != nil {
					return nil, fmt.Errorf("decode field users element: %w", err)
				}
				element = layerClass11
				layerVector10 = append(layerVector10, element)
			}
			layerDecoded7 = layerVector10
			if true {
				value.BotID = layerDecoded1
			}
			_ = layerDecoded3 // explicitly consumed and dropped historical field url
			if true {
				value.QueryID = layerDecoded5
			}
			if true {
				value.Users = layerDecoded7
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesChatInviteJoinResultWebView, WireID: 0x774bbdf4, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire7780bcb4Bare(profile LayerProfile, value *tg.GroupCallDiscarded, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeGroupCallDiscarded, WireID: 0x7780bcb4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire7780bcb4BareBody(profile LayerProfile, value *tg.GroupCallDiscarded, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire7780bcb4Bare(profile, value, b, state)
}
func layerDecodeWire7780bcb4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.GroupCallDiscarded, error) {
	value := new(tg.GroupCallDiscarded)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWireaeaf9e74(profile LayerProfile, value *tg.UpdateSavedDialogPinned, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedDialogPinned, WireID: 0xaeaf9e74, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		switch profile {
		case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

		default:
			return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedDialogPinned, WireID: 0xaeaf9e74, Reason: "wire ID is unavailable in exact profile"}
		}

		b.PutID(0xaeaf9e74)
		return layerEncodeWireaeaf9e74BareBody(profile, value, b, state)

	})
}

func layerEncodeWireaeaf9e74Bare(profile LayerProfile, value *tg.UpdateSavedDialogPinned, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedDialogPinned, WireID: 0xaeaf9e74, Reason: "nil canonical value"}
	}
	return layerCodecEncodeAtomic(profile, b, func() error {
		return layerEncodeWireaeaf9e74BareBody(profile, value, b, state)
	})
}

func layerEncodeWireaeaf9e74BareBody(profile LayerProfile, value *tg.UpdateSavedDialogPinned, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if value.Flags.Has(0) || value.Pinned {
				wireFlags0.Set(0)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode flags flags: %w", err)
			}
			if err := layerEncodeClassDialogPeerBody(profile, value.Peer, b, state); err != nil {
				return fmt.Errorf("encode field peer: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedDialogPinned, WireID: 0xaeaf9e74, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireaeaf9e74(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateSavedDialogPinned, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedDialogPinned, WireID: 0xaeaf9e74, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xaeaf9e74); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xaeaf9e74: %w", err)
	}
	return layerDecodeWireaeaf9e74Bare(profile, b, state)

}

func layerDecodeWireaeaf9e74Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateSavedDialogPinned, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.UpdateSavedDialogPinned)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode flags flags: %w", err)
			}
			layerDecoded2 := wireFlags0.Has(0)
			var layerDecoded3 tg.DialogPeerClass
			layerClass4, err := layerDecodeClassDialogPeer(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field peer: %w", err)
			}
			layerDecoded3 = layerClass4
			if wireFlags0.Has(0) {
				value.Flags.Set(0)
				value.Pinned = layerDecoded2
			}
			if true {
				value.Peer = layerDecoded3
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateSavedDialogPinned, WireID: 0xaeaf9e74, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireb81c7034Bare(profile LayerProfile, value *tg.SendAsPeer, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSendAsPeer, WireID: 0xb81c7034, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb81c7034BareBody(profile LayerProfile, value *tg.SendAsPeer, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb81c7034Bare(profile, value, b, state)
}
func layerDecodeWireb81c7034(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SendAsPeer, error) {
	value := new(tg.SendAsPeer)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWired072acb4Bare(profile LayerProfile, value *tg.RestrictionReason, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeRestrictionReason, WireID: 0xd072acb4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWired072acb4BareBody(profile LayerProfile, value *tg.RestrictionReason, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWired072acb4Bare(profile, value, b, state)
}
func layerDecodeWired072acb4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.RestrictionReason, error) {
	value := new(tg.RestrictionReason)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWired29a27f4Bare(profile LayerProfile, value *tg.UpdateChannelMessageForwards, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdateChannelMessageForwards, WireID: 0xd29a27f4, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWired29a27f4BareBody(profile LayerProfile, value *tg.UpdateChannelMessageForwards, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWired29a27f4Bare(profile, value, b, state)
}
func layerDecodeWired29a27f4(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdateChannelMessageForwards, error) {
	value := new(tg.UpdateChannelMessageForwards)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWired5e58274Bare(profile LayerProfile, value *tg.PaymentsCheckCanSendGiftResultFail, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePaymentsCheckCanSendGiftResultFail, WireID: 0xd5e58274, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWired5e58274BareBody(profile LayerProfile, value *tg.PaymentsCheckCanSendGiftResultFail, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWired5e58274Bare(profile, value, b, state)
}
func layerDecodeWired5e58274(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PaymentsCheckCanSendGiftResultFail, error) {
	value := new(tg.PaymentsCheckCanSendGiftResultFail)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiredb64fd34Bare(profile LayerProfile, value *tg.AccountTmpPassword, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeAccountTmpPassword, WireID: 0xdb64fd34, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiredb64fd34BareBody(profile LayerProfile, value *tg.AccountTmpPassword, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiredb64fd34Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWiree3af4434Bare(profile LayerProfile, value *tg.InputMediaPhoto, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputMediaPhoto, WireID: 0xe3af4434, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWiree3af4434BareBody(profile LayerProfile, value *tg.InputMediaPhoto, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWiree3af4434Bare(profile, value, b, state)
}
func layerDecodeWiree3af4434(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputMediaPhoto, error) {
	value := new(tg.InputMediaPhoto)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
