// Code generated by gotdgen, DO NOT EDIT.

package tlprofile

import (
	"errors"
	"fmt"

	"github.com/iamxvbaba/td/bin"
	"github.com/iamxvbaba/td/tg"
)

var (
	_ = errors.Is
	_ = fmt.Stringer(nil)
	_ = bin.Buffer{}
	_ = tg.Layer
)

func layerEncodeWire0a4314f5BareBody(profile LayerProfile, value *tg.MessagesSendWebViewResultMessageRequest, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := b.PutStringChecked(value.BotQueryID); err != nil {
				return fmt.Errorf("encode field bot_query_id: %w", err)
			}
			if err := layerEncodeClassInputBotInlineResultBody(profile, value.Result, b, state); err != nil {
				return fmt.Errorf("encode field result: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSendWebViewResultMessage, WireID: 0x0a4314f5, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire0a4314f5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSendWebViewResultMessageRequest, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticMethodMessagesSendWebViewResultMessage, WireID: 0x0a4314f5, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x0a4314f5); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x0a4314f5: %w", err)
	}
	return layerDecodeWire0a4314f5Bare(profile, b, state)

}

func layerDecodeWire0a4314f5Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessagesSendWebViewResultMessageRequest, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.MessagesSendWebViewResultMessageRequest)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 string
			layerPrimitive3, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode field bot_query_id: %w", err)
			}
			layerDecoded2 = layerPrimitive3
			var layerDecoded4 tg.InputBotInlineResultClass
			layerClass5, err := layerDecodeClassInputBotInlineResult(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field result: %w", err)
			}
			layerDecoded4 = layerClass5
			if true {
				value.BotQueryID = layerDecoded2
			}
			if true {
				value.Result = layerDecoded4
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticMethodMessagesSendWebViewResultMessage, WireID: 0x0a4314f5, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire1abfb575Bare(profile LayerProfile, value *tg.InputDocument, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputDocument, WireID: 0x1abfb575, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire1abfb575BareBody(profile LayerProfile, value *tg.InputDocument, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire1abfb575Bare(profile, value, b, state)
}
func layerDecodeWire1abfb575(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputDocument, error) {
	value := new(tg.InputDocument)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire30535af5Bare(profile LayerProfile, value *tg.PhoneCall, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePhoneCall, WireID: 0x30535af5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire30535af5BareBody(profile LayerProfile, value *tg.PhoneCall, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire30535af5Bare(profile, value, b, state)
}
func layerDecodeWire30535af5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PhoneCall, error) {
	value := new(tg.PhoneCall)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire560f8935Bare(profile LayerProfile, value *tg.MessagesSentEncryptedMessage, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesSentEncryptedMessage, WireID: 0x560f8935, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire560f8935BareBody(profile LayerProfile, value *tg.MessagesSentEncryptedMessage, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire560f8935Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire59e65335Bare(profile LayerProfile, value *tg.MessagesEmojiGameUnavailable, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesEmojiGameUnavailable, WireID: 0x59e65335, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire59e65335BareBody(profile LayerProfile, value *tg.MessagesEmojiGameUnavailable, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire59e65335Bare(profile, value, b, state)
}

func layerEncodeWire5b0f15f5BareBody(profile LayerProfile, value *tg.KeyboardButton, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			historicalPresent1, historicalValue1, historicalValue2, historicalValue3, historicalValue4, historicalValue5, historicalHookErr := layerAdaptLegacyKeyboardButtonRequestPeerEncode(profile, value)
			if historicalHookErr != nil {
				return fmt.Errorf("adapt historical constructor for encoding: %w", historicalHookErr)
			}
			layerHistoricalPresent1 := historicalPresent1
			layerHistoricalEncoded2 := &bin.Buffer{}
			if layerHistoricalPresent1 {
				layerHistoricalErr3 := func() error {
					layerHistoricalEncoded2.PutID(0x4fdd3430)
					if err := layerEncodeWire4fdd3430BareBody(profile, &(historicalValue1), layerHistoricalEncoded2, state); err != nil {
						return fmt.Errorf("encode historical field style: %w", err)
					}
					return nil
				}()
				if layerHistoricalErr3 != nil {
					if IsLayerProjectionDrop(layerHistoricalErr3) {
						layerHistoricalPresent1 = false
						layerHistoricalEncoded2.Reset()
					} else {
						return fmt.Errorf("encode historical optional field style: %w", layerHistoricalErr3)
					}
				}
			}
			if (layerHistoricalPresent1) && !layerHistoricalPresent1 {
				return &LayerCodecError{Operation: "encode", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPeer, WireID: 0x5b0f15f5, Reason: "historical adapter returned a partial shared flag group flags.10"}
			}
			var wireFlags0 bin.Fields
			if layerHistoricalPresent1 {
				wireFlags0.Set(10)
			}
			if err := wireFlags0.Encode(b); err != nil {
				return fmt.Errorf("encode historical flags flags: %w", err)
			}
			if wireFlags0.Has(10) {
				b.Buf = append(b.Buf, layerHistoricalEncoded2.Buf...)
			}
			if err := b.PutStringChecked(historicalValue2); err != nil {
				return fmt.Errorf("encode historical field text: %w", err)
			}
			b.PutInt(historicalValue3)
			if err := layerEncodeClassRequestPeerTypeBody(profile, historicalValue4, b, state); err != nil {
				return fmt.Errorf("encode historical field peer_type: %w", err)
			}
			b.PutInt(historicalValue5)
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPeer, WireID: 0x5b0f15f5, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWire5b0f15f5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.KeyboardButton, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPeer, WireID: 0x5b0f15f5, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0x5b0f15f5); err != nil {
		return nil, fmt.Errorf("consume layer wire 0x5b0f15f5: %w", err)
	}
	return layerDecodeWire5b0f15f5Bare(profile, b, state)

}

func layerDecodeWire5b0f15f5Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.KeyboardButton, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.KeyboardButton)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228:
		{
			var wireFlags0 bin.Fields
			if err := wireFlags0.Decode(b); err != nil {
				return nil, fmt.Errorf("decode historical flags flags: %w", err)
			}
			historicalPresent1 := wireFlags0.Has(10)
			var historicalValue1 tg.KeyboardButtonStyle
			if historicalPresent1 {
				layerConcrete1, err := layerDecodeWire4fdd3430(profile, b, state)
				if err != nil {
					return nil, fmt.Errorf("decode historical field style: %w", err)
				}
				historicalValue1 = *layerConcrete1
			}
			var historicalValue2 string
			layerPrimitive2, err := b.String()
			if err != nil {
				return nil, fmt.Errorf("decode historical field text: %w", err)
			}
			historicalValue2 = layerPrimitive2
			var historicalValue3 int
			layerPrimitive3, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode historical field button_id: %w", err)
			}
			historicalValue3 = layerPrimitive3
			var historicalValue4 tg.RequestPeerTypeClass
			layerClass4, err := layerDecodeClassRequestPeerType(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode historical field peer_type: %w", err)
			}
			historicalValue4 = layerClass4
			var historicalValue5 int
			layerPrimitive5, err := b.Int()
			if err != nil {
				return nil, fmt.Errorf("decode historical field max_quantity: %w", err)
			}
			historicalValue5 = layerPrimitive5
			adapted, err := layerAdaptLegacyKeyboardButtonRequestPeerDecode(profile, historicalPresent1, historicalValue1, historicalValue2, historicalValue3, historicalValue4, historicalValue5)
			if err != nil {
				return nil, fmt.Errorf("adapt historical constructor after decoding: %w", err)
			}
			if adapted == nil {
				return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPeer, WireID: 0x5b0f15f5, Reason: "historical adapter returned nil canonical value"}
			}
			return adapted, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypeKeyboardButtonRequestPeer, WireID: 0x5b0f15f5, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire5ce14175Bare(profile LayerProfile, value *tg.PopularContact, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePopularContact, WireID: 0x5ce14175, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire5ce14175BareBody(profile LayerProfile, value *tg.PopularContact, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire5ce14175Bare(profile, value, b, state)
}
func layerDecodeWire5ce14175(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PopularContact, error) {
	value := new(tg.PopularContact)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire8e1a1775Bare(profile LayerProfile, value *tg.NearestDC, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeNearestDC, WireID: 0x8e1a1775, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire8e1a1775BareBody(profile LayerProfile, value *tg.NearestDC, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire8e1a1775Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWire98f6ac75Bare(profile LayerProfile, value *tg.HelpPromoDataEmpty, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeHelpPromoDataEmpty, WireID: 0x98f6ac75, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWire98f6ac75BareBody(profile LayerProfile, value *tg.HelpPromoDataEmpty, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWire98f6ac75Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirea8763ab5Bare(profile LayerProfile, value *tg.InputMediaDocument, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeInputMediaDocument, WireID: 0xa8763ab5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirea8763ab5BareBody(profile LayerProfile, value *tg.InputMediaDocument, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirea8763ab5Bare(profile, value, b, state)
}
func layerDecodeWirea8763ab5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.InputMediaDocument, error) {
	value := new(tg.InputMediaDocument)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireb457b375Bare(profile LayerProfile, value *tg.StarsTransactionPeerAppStore, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeStarsTransactionPeerAppStore, WireID: 0xb457b375, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb457b375BareBody(profile LayerProfile, value *tg.StarsTransactionPeerAppStore, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb457b375Bare(profile, value, b, state)
}
func layerDecodeWireb457b375(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.StarsTransactionPeerAppStore, error) {
	value := new(tg.StarsTransactionPeerAppStore)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireb4c38cb5Bare(profile LayerProfile, value *tg.MessageActionWebViewDataSent, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessageActionWebViewDataSent, WireID: 0xb4c38cb5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireb4c38cb5BareBody(profile LayerProfile, value *tg.MessageActionWebViewDataSent, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireb4c38cb5Bare(profile, value, b, state)
}
func layerDecodeWireb4c38cb5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.MessageActionWebViewDataSent, error) {
	value := new(tg.MessageActionWebViewDataSent)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireba8d5f35Bare(profile LayerProfile, value *tg.EphemeralSendMessageRequest, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticMethodEphemeralSendMessage, WireID: 0xba8d5f35, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireba8d5f35BareBody(profile LayerProfile, value *tg.EphemeralSendMessageRequest, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireba8d5f35Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirec0e24635Bare(profile LayerProfile, value *tg.MessagesDhConfigNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesDhConfigNotModified, WireID: 0xc0e24635, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirec0e24635BareBody(profile LayerProfile, value *tg.MessagesDhConfigNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirec0e24635Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirede266ef5Bare(profile LayerProfile, value *tg.ContactsTopPeersNotModified, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeContactsTopPeersNotModified, WireID: 0xde266ef5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirede266ef5BareBody(profile LayerProfile, value *tg.ContactsTopPeersNotModified, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirede266ef5Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireeb50adf5Bare(profile LayerProfile, value *tg.MessagesBotApp, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeMessagesBotApp, WireID: 0xeb50adf5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireeb50adf5BareBody(profile LayerProfile, value *tg.MessagesBotApp, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireeb50adf5Bare(profile, value, b, state)
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWireed85eab5Bare(profile LayerProfile, value *tg.UpdatePinnedMessages, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeUpdatePinnedMessages, WireID: 0xed85eab5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWireed85eab5BareBody(profile LayerProfile, value *tg.UpdatePinnedMessages, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWireed85eab5Bare(profile, value, b, state)
}
func layerDecodeWireed85eab5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.UpdatePinnedMessages, error) {
	value := new(tg.UpdatePinnedMessages)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}

func layerEncodeWireef1751b5BareBody(profile LayerProfile, value *tg.PageBlockChannel, b *bin.Buffer, state *layerCodecState) error {
	child, err := layerCodecDescend(profile, "encode", state)
	if err != nil {
		return err
	}
	state = &child
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			if err := layerEncodeClassChatBody(profile, value.Channel, b, state); err != nil {
				return fmt.Errorf("encode field channel: %w", err)
			}
			return nil

		}
	default:
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypePageBlockChannel, WireID: 0xef1751b5, Reason: "wire ID is unavailable in exact profile"}
	}
}

func layerDecodeWireef1751b5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PageBlockChannel, error) {
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:

	default:
		return nil, &LayerCodecError{Operation: "decode", Profile: profile, Semantic: LayerSemanticTypePageBlockChannel, WireID: 0xef1751b5, Reason: "wire ID is unavailable in exact profile"}
	}

	if err := b.ConsumeID(0xef1751b5); err != nil {
		return nil, fmt.Errorf("consume layer wire 0xef1751b5: %w", err)
	}
	return layerDecodeWireef1751b5Bare(profile, b, state)

}

func layerDecodeWireef1751b5Bare(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.PageBlockChannel, error) {
	child, err := layerCodecDescend(profile, "decode", state)
	if err != nil {
		return nil, err
	}
	state = &child
	value := new(tg.PageBlockChannel)
	_ = value
	switch profile {
	case LayerProfile225, LayerProfile226, LayerProfile227, LayerProfile228, LayerProfile229:
		{
			var layerDecoded2 tg.ChatClass
			layerClass3, err := layerDecodeClassChat(profile, b, state)
			if err != nil {
				return nil, fmt.Errorf("decode field channel: %w", err)
			}
			layerDecoded2 = layerClass3
			if true {
				value.Channel = layerDecoded2
			}
			return value, nil

		}
	default:
		return nil, &LayerCodecError{Operation: "decode-bare", Profile: profile, Semantic: LayerSemanticTypePageBlockChannel, WireID: 0xef1751b5, Reason: "wire ID is unavailable in exact profile"}
	}
}

// Canonical-direct exact wire; the scanner has validated its transitive graph.
func layerEncodeWirefd5ec8f5Bare(profile LayerProfile, value *tg.SendMessageCancelAction, b *bin.Buffer, state *layerCodecState) error {
	if value == nil {
		return &LayerCodecError{Operation: "encode-bare", Profile: profile, Semantic: LayerSemanticTypeSendMessageCancelAction, WireID: 0xfd5ec8f5, Reason: "nil canonical value"}
	}
	return value.EncodeBare(b)
}
func layerEncodeWirefd5ec8f5BareBody(profile LayerProfile, value *tg.SendMessageCancelAction, b *bin.Buffer, state *layerCodecState) error {
	return layerEncodeWirefd5ec8f5Bare(profile, value, b, state)
}
func layerDecodeWirefd5ec8f5(profile LayerProfile, b *bin.Buffer, state *layerCodecState) (*tg.SendMessageCancelAction, error) {
	value := new(tg.SendMessageCancelAction)
	if err := value.Decode(b); err != nil {
		return nil, err
	}
	return value, nil
}
